Chapter 1. Task 5.
KFalcon2022/intensive-tasks pull request #101
Opened 2023-11-20 15:47 UTC by tvadim1

2023-11-22 20:29 UTC, EvgeneZhurov requested changes

2023-11-22 21:06 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +    private static double invEps;
благодарю за ревью. метод static void print(String keyword, double[] array) на 56 строке использует invEpsilon для округления (Math.rint(invEps * d) / invEps. Решил попробовать округлить.  Убрал из кода.

вторая статическая переменная areaByHeron применяется в статичном методе getInscribedCircleRadius(double a, double b, double c) - вычисление радиуса через площадь и getCircumradius(double a, double b, double c) - вычисление внешнего радиуса.

2023-11-22 21:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +    private static double invEps;
Можно еще вопрос. Курс рассчитан на самых начинающих. Не проще ли стать ревьюером, если знаете материал? Люди ждут проверки решения днями.

2023-11-22 23:03 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +    private static double invEps;
Если честно, это первый раз, когда получилось встроить функциональный подход в практическую задачу и додуматься, что "О, это можно применить тут" - было очень круто.  О лямбда-функциях, я узнал буквально 3 недели назад, начав проходить курс "дорогу осилит идущий" (правда темы в разнобой читаю - по наитию), тогда же началось путешествие после 4 летнего перерыва после окончания института по этой специальности, но так повернулась жизнь, что находился в другой сфере (строительство) и выпал, в разговоре с одногруппником месяца полтора назад спрашивал "а какая сейчас IDE лучше JetBrains или Idea? :D 
Но прочитав пост на Пикабу, пришел интерес, которого даже в институте не было, и ваши курсы очень сильно мотивировали, я видел как вы писали в чате интенсива "что нужно пахать", и вот как-то эта фраза ваша прям запала в голову, что ведь действительно только такая установка и может быть. Как бы я давно этих слов от кого-либо не слышал, и какое-то переосмысление пришло что ли. Поэтому решаю всё что дают, как могу, но, к сожалению, это не делает мои решения хорошими: вы, Колоколов Евгений и Юлия Помидорка - все указали на мой неправильный стиль программирования (например, вы указали, что я называю переменные неправильно, не amoutOfFlats, а flatAmount, сказали посмотреть статью про магическое число и я даже не знал, что нужно постоянно сознательно придерживаться подхода, чтобы читаемость была выше всегда, что это как аналогия с принципами SOLID, которых нужно придерживаться, т.е. избегать магических чисел в коде), Евгений Колоколов указал, что я массивы статичные не именую константами и называю их неправильным форматом, что давать длинное имя методу - моветон, Юлия - что я неправильно понимал, как работает if-else, и когда добавил return неправильно понимал, как он работает. И уверен, что есть масса вещей, которые мне неизвестны. Вы указали в своем видеоуроке "нужно отрабатывать базу". У меня нет практики, никогда не работав программистом, база хромает. Поэтому, не думаю, что могу дать компетентное суждение о коде того или иного участника, т.е. могу, но скорее всего не замечу плохой код - получится только проверить, что он работает, не могу жестко указывать на ошибки. Мне очень интересен ваш курс, благодарен, что выделяете время на него, но у меня едва ли средний уровень.

2023-11-23 19:47 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +    private static double invEps;
Хорошо, принято

2023-11-23 20:04 UTC, EvgeneZhurov requested changes

2023-11-23 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double hp = 0.5 * (a + b + c);
нужно давать информативные имена

2023-11-23 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return a * b * c / 4 / areaByHeron;
лучше избегать  / / таких делений - это читается хуже. Лучше поправить во всех формулах

2023-11-23 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return a * b * c / 4 / areaByHeron;
Засчитано

2023-11-23 20:05 UTC, closed without merging

2023-11-23 20:29 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return a * b * c / 4 / areaByHeron;
понял, теперь больше не буду так писать, просто иногда опасаюсь запутаться в скобках

2023-11-23 20:30 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return a * b * c / 4 / areaByHeron;
Благодарю