Chapter 1 Task1
KFalcon2022/intensive-tasks pull request #104
Opened 2023-11-20 16:44 UTC by KungFU13

2023-11-20 18:28 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:
111, 112, 113, 114

2023-11-20 18:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static String getAgeString(String name, int age) {
Не надо менять сигнатуру вызываемого метода.

2023-11-20 18:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (!isYearsNoMore127AndNonNegative(age)) {
Лучше переименовать метод чтобы не использовать отрицание.

2023-11-20 18:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static boolean isYearsNoMore127AndNonNegative(int age) {
Проверка входных данных называется валидация. Можно попробовать использовать в названии

2023-11-20 19:21 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static String getAgeString(String name, int age) {
Исправил

2023-11-20 19:59 UTC, ekolokolov requested changes
Не корректное исполнение на значениях: 
1, 2, 3, 4
Expected :Вам 1 год
Actual   :Вам 1 лет

2023-11-22 08:26 UTC, ekolokolov requested changes
Исправь форматирование и оформление кода

2023-11-22 08:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static boolean YearsNoMore127AndNonNegative(int age) {
Название метода ВСЕГДА с маленькой буквы. 
Так же название должно быть "простым". Использование слова And - не то чтобы запрещено, но признак "проказы". Надо исбавиться. 
Подумай ЧТО делает этот метод, а не КАК.

2023-11-22 08:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            result = ": Вам " + age + " год";
Можно возвращать сразу ответ, а не переприсваивать его в переменную result. 
`return  "Вам " + age + " год"` ( и двоеточие в начале убери, оно там вообще не нужно)

2023-11-22 08:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (!YearsNoMore127AndNonNegative(age)) {
вместо добавления отрицания лучше переименовать метод. 
Сравни 
`if (isGood()) { }` или `if (!isBad()) { }` - одно и то же.

2023-11-22 19:35 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static boolean YearsNoMore127AndNonNegative(int age) {
решил вообще убрать метод.

2023-11-22 19:35 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            result = ": Вам " + age + " год";
исправил

2023-11-22 19:35 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (!YearsNoMore127AndNonNegative(age)) {
решил вообще убрать метод.

2023-11-23 06:28 UTC, ekolokolov approved these changes
Зачтено

2023-11-23 06:28 UTC, closed without merging