Task1
KFalcon2022/intensive-tasks pull request #105
Opened 2023-11-20 16:44 UTC by reilan86

Вариант решения задачи 1

2023-11-20 18:25 UTC, ekolokolov requested changes
Нужно переделать без множественной конвертации в строки и чары

2023-11-20 18:25 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            String ageString = Integer.toString(age);
Нет ни какой необходимости приводить число к строке. 
Чтобы получить значение "в конце числа" - можно использовать оператор % - который возвращает остаток от деления.

2023-11-20 18:25 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age > 127||age <0) {
Не забываем про фарматирование

2023-11-20 19:02 UTC, reilan86 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age > 127||age <0) {
Исправлено

2023-11-21 08:52 UTC, ekolokolov requested changes

2023-11-21 08:52 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        System.out.println("Вам " + age + getAgeString(age));
Не, вот так делать не надо. Метод должен вернуть всю строку.

2023-11-21 12:42 UTC, reilan86 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        System.out.println("Вам " + age + getAgeString(age));
Надеюсь понял правильно.в третьей задаче под упростить Вы имели ввиду "return year % 4 == 0 && year % 100 != 0 || year % 400 == 0;"? просто там пулреквест закрыт, а понять правильно ли я понял хотелось бы.

2023-11-21 18:22 UTC, ekolokolov approved these changes
Зачтено

2023-11-21 18:22 UTC, closed without merging