Вариант решения задачи 1-2
KFalcon2022/intensive-tasks pull request #106
Opened 2023-11-20 16:45 UTC by reilan86

2023-11-20 20:57 UTC, KFalcon2022 requested changes

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                    resultString = flatNumber + " кв – " + flatEnterance + " подъезд, " + flatFloor + " этаж, слева от лифта, влево";
Почему решил не делать return прямо из case? 

Кроме того, сама конструкция позволяет писать return перед собой, если немного доработать: [ссылка](https://medium.com/@javatechie/the-evolution-of-switch-statement-from-java-7-to-java-17-4b5eee8d29b7#:~:text=Return%20value%20through%20arrow)

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        else {
если в if'е делаешь return, нет смысла писать else - код и там сюда не дойдет, если уже попал в if

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String resultString="";
переменные стоит объявлять как можно ближе к месту их использования

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            int flatEnterance = (flatNumber - 1) / (floorAmount * flatOnFloor) + 1;
Рекомендую не злоупотреблять предлогами в названиях переменных. Здесь могу предложить что-то вроде flatOnFloor-> floorCapacity

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            int flatCoordinates = (flatNumber - 1) % flatOnFloor + 1;
Coordinates - множественное число, но тип переменной - число. Одно число:) мб лучше Position или что-то подобное?

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            int flatCoordinates = (flatNumber - 1) % flatOnFloor + 1;
И, кажется, можно было упростить арифметику, если правой-правой позиции на этаже присвоить нулевую позицию

2023-11-20 20:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
При внесении правок - напиши в ЛС. https://t.me/ironicMotherfucker

2023-11-21 13:15 UTC, reilan86 commented
Сегодня вообще день открытий по return, спасибо за информацию перечитал, так же визуально облегчил строку вывода, и надеюсь правильно понял по исправлению арифметики.

2023-11-21 18:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +               default -> "";
логичнее ожидать чего-то осмысленного. "Ошибка расчета" или подобное.

2023-11-21 18:04 UTC, closed without merging