Вариант решения задачи 1-4
KFalcon2022/intensive-tasks pull request #108
Opened 2023-11-20 16:46 UTC by reilan86

2023-11-21 11:59 UTC, PomidorkaYulia requested changes

2023-11-21 11:59 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
>          //        Место для вашего кода
Некорректно отрабатывает на данных:
1) a,b,c -  все равны нулю - должно быть бесконечное множество решений, а выдает одно
2) при a,b - нули, а c не ноль - вместо нет решений выдает - одно решение
3) если квадратное уравнение вырожденно - т.е. превращается в линейное при a=0 - неверный ответ

2023-11-21 13:12 UTC, reilan86 commented
Исправил, виноват пересмотрите пожалуйста.

2023-11-21 16:33 UTC, PomidorkaYulia requested changes

2023-11-21 16:33 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        return null; // Заглушка. При реализации - удалить
Сорри что душню:
Количество решений: 1. Корень: -0.0 - наверное -0 как то не очень выглядит? 
и еще - не нужно делать else  - можно просто делать if -> return следующий if-> return. И получается если условие выполнится - вернется нужное значение - не выполнится - перейдет к следующему условию. Будет лучше читаться и меньше строк кода получится. И дискриминант тоже можно вычислять вне else. И даже вложенных ифов не будет. Попробуете переделать? если что приходите - вместе разберем (@yulia_sidorenkova в телеграме), в целом это решение рабочее.

2023-11-21 17:04 UTC, reilan86 commented
Исправил, надеюсь все требования понял правильно.

2023-11-21 17:19 UTC, reilan86 commented
в последнем комите изменил вывод убрав if и else, надеюсь теперь все правильно.

2023-11-22 06:21 UTC, PomidorkaYulia commented
Отлично) все верно поняли. Засчитано

2023-11-22 06:22 UTC, PomidorkaYulia approved these changes

2023-11-22 06:23 UTC, closed without merging