Вариант решения задачи 1-5
KFalcon2022/intensive-tasks pull request #109
Opened 2023-11-20 16:46 UTC by reilan86

2023-11-21 16:00 UTC, reilan86 commented
Последний (7deed0b) включает исправления в формулах и является окончательным для меня на данном этапе :)

2023-11-21 16:49 UTC, reilan86 commented
[b77c8a7](https://github.com/KFalcon2022/intensive-tasks/pull/109/commits/b77c8a726a8a44330ee4fd9177261e79a9129a01) Является окончательным

2023-11-22 20:40 UTC, EvgeneZhurov requested changes

2023-11-22 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        System.out.println("1. Площадь треугольника по формуле Герона " + areaByHeron(a, b, c));
double a = 12;
        double b = 13;
        double c = 5;
ожидается  30.0
8. Нахождения cos угла С между сторонами a и b, затем преобразование его в sin с последующим расчетом площади через него NaN

2023-11-22 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        heightsArray[0] = (2 * areaHeron) / a;
пробел

2023-11-22 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        return heightsArray;
пробел, в подобных местах тоже

2023-11-22 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        heightsArray[2] = (2 * areaHeron) / c;
пробел

2023-11-22 23:32 UTC, reilan86 commented
Ошибку в последнем методе исправил, но я выбрал не удачный угол он не возвращал 30.0 результат возврата был 29.999999 решением с моей стороны было произвести вычисления для каждого из трех кейсов нахождения площади.

2023-11-23 21:11 UTC, EvgeneZhurov requested changes

2023-11-23 21:11 UTC, EvgeneZhurov commented on README.md
> +Репозиторий разбит на 5 разделов, каждый из которых содержит 5 тематических задач. Каждая задача находится в своем
У меня просьба. У Вас сейчас стоит 14 файлов в изменении. Я сделаю Request changes, нужно 1 изменение в ветке.

2023-11-23 21:33 UTC, EvgeneZhurov commented on README.md
> +Репозиторий разбит на 5 разделов, каждый из которых содержит 5 тематических задач. Каждая задача находится в своем
Принято.

2023-11-23 21:33 UTC, closed without merging