task1
KFalcon2022/intensive-tasks pull request #111
Opened 2023-11-20 16:54 UTC by smmotor

2023-11-20 18:51 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:
21, 22, 23,24, 31, 32 и так далее.

2023-11-21 10:31 UTC, smmotor commented
Здравствуйте, переделал 1 задачу

2023-11-22 08:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age > 0 && age < 130) {
0 - корректный возраст

2023-11-22 08:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            else if (age % 10 == 1) {
else на одной строке с фигурной строчкой `} else if () {`

2023-11-22 08:30 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else {
Проверку некоррекности можно сделать в самом начале 
```Java
        if (age < 0 || age > 127) {
            return "Введен некорректный возраст";
        }
```

2023-11-22 12:32 UTC, smmotor commented
Добрый день, исправил форматирование и проверку на корректность добавил в начало

2023-11-23 06:29 UTC, ekolokolov approved these changes
Зачтено

2023-11-23 06:29 UTC, closed without merging