Task4
KFalcon2022/intensive-tasks pull request #119
Opened 2023-11-20 17:36 UTC by EAnchugov

2023-11-21 17:01 UTC, PomidorkaYulia requested changes

2023-11-21 17:01 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
>          //        Место для вашего кода
Для (0,0,5) - должно быть нет решений а возвращает бесконечное количество решений.

2023-11-21 17:01 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (d < 0) return "Количество решений: 0.";
Каждый  if - одинаковое замечание. можно отделять еще пустыми строками ифы друг от друга.

2023-11-22 11:11 UTC, PomidorkaYulia requested changes

2023-11-22 12:44 UTC, EAnchugov commented
У меня 5 задача висит 2 день в пулах. Кому написать, чтобы посмотрели?

2023-11-23 15:49 UTC, PomidorkaYulia approved these changes

2023-11-23 15:50 UTC, closed without merging