Task2
KFalcon2022/intensive-tasks pull request #121
Opened 2023-11-20 17:36 UTC by EAnchugov

2023-11-20 20:38 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +//        return null; // Заглушка. При реализации - удалить
Каждая задача должна быть отдельным Pull request'ом. В соответствии с названием проверяю только задачу 2

2023-11-20 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        if (flatNumber > floorAmount * entranceAmount * 4 || flatNumber < 0) return "Нет такой квартиры";
Стоит внимательно прочесть https://github.com/KFalcon2022/intensive-tasks#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0

Особенно п.9

2023-11-20 20:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
Может ли быть квартира с номером 0?

2023-11-20 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        if (flatPosition == 1)
Кажется, switch-case подошел бы лучше

2023-11-20 20:45 UTC, KFalcon2022 requested changes

2023-11-20 20:45 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж , справа от лифта, вправо";
Еще раз подчеркну, что стоит ознакомиться с правилами оформления кода. При внесении правок - сообщи в ЛС.

2023-11-20 20:45 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж , справа от лифта, вправо";
https://t.me/ironicMotherfucker

2023-11-20 20:46 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж , справа от лифта, вправо";
Кроме того, не вижу твой гитхаб в таблице с участниками. Решим в ЛС

2023-11-20 22:19 UTC, EAnchugov commented
Поправил

2023-11-22 20:01 UTC, KFalcon2022 requested changes

2023-11-22 20:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age < 5 ) return "Вам" + age + "года";
Не внесены запрошенные исправления

2023-11-24 13:16 UTC, EAnchugov commented
Замечания относились к таску 1, я просто убрал его решение, чтобы нее смущало.

2023-12-04 20:43 UTC, KFalcon2022 approved these changes

2023-12-04 20:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
Не исправлено замечание, но считаю его мелким. Задача засчитана

2023-12-04 20:43 UTC, closed without merging