Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #133
Opened 2023-11-20 21:16 UTC by gsv96

2023-11-22 12:18 UTC, PomidorkaYulia requested changes

2023-11-22 12:18 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            else if (a == 0 && b == 0) {return numberOfSolutions + 1 + ". Корень: " + c + ".";}
После return нет смысла в else -  можно просто без него.
Это условие не корректное если a == 0 && b == 0 а с!=0 - тогда нет решений, а не один корень

2023-11-22 12:18 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            } else if (b == 0) {
На мой взгляд нет смысла выделать в отдельные случаи b=0 или c= 0 при a!=0  - это все замечательно почитается и через дискриминант без проблем.

2023-11-22 12:18 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +    }
if в одну строку не принято писать даже если действие выполняемое короткое. Всегда фигурные скобки и с новой строки. 
else после return не нужен, 
Можно сократить количество условий и не делать вложенные  условия. Попробуете переделать?

2023-11-22 13:27 UTC, gsv96 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +    }
Хорошо)) Просто вспомнил, что при а ==0 ур-е из квадратного превращается в линейное, при b == 0 два корня: 0 и линейное ур-е. С с ошибся, и правда,  например при с = 6:  6=0, нет решений. Про if в одну строку приму к сведению

2023-11-23 10:31 UTC, PomidorkaYulia approved these changes

2023-11-23 10:31 UTC, closed without merging