Chapter1 task1
KFalcon2022/intensive-tasks pull request #135
Opened 2023-11-20 21:24 UTC by NJmist

Решение задачи про возраст, теперь в своей ветке, извиняюсь за путаницу

2023-11-22 12:26 UTC, PomidorkaYulia requested changes

2023-11-22 12:26 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age < 0 || age > 127) {
Некорректно для данных 10-19 (Вам 10 год - выводится) и 110-119. 

После return else не нужен, можно его просто опустить - разницы не будет.

2023-11-22 18:00 UTC, NJmist commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age < 0 || age > 127) {
Поправил, вроде всё работает

2023-11-23 19:15 UTC, NJmist commented
Исправил

2023-11-24 16:45 UTC, PomidorkaYulia approved these changes

2023-11-24 16:45 UTC, closed without merging