Chapter1 task3
KFalcon2022/intensive-tasks pull request #138
Opened 2023-11-20 21:37 UTC by NJmist

Решение задачи про високосный год

2023-11-22 12:35 UTC, PomidorkaYulia requested changes

2023-11-22 12:35 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        if (year % 100 == 0 && year % 400 != 0) {
Отрабатывает корректно, но даже Идея подсказывает что можно упростить. По сути у тебя при одном наборе условий возвращается true,а во всех остальных false.
И еще - вместо 
` f (year % 400 == 0 || year % 4 == 0) {
            return true;
}`
 нужно использовать просто 
`return (year % 400 == 0 || year % 4 == 0) ;`

2023-11-22 12:35 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        if (year % 100 == 0 && year % 400 != 0) {
Идея верная - немножко еще упростить - и вообще однострочник получится.

2023-11-22 18:22 UTC, NJmist commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        if (year % 100 == 0 && year % 400 != 0) {
Теперь я понял, что мне подсказывала Идея

2023-11-24 16:47 UTC, PomidorkaYulia approved these changes

2023-11-24 16:47 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year % 400 == 0 || year % 4 == 0 && year % 100 != 0); // Теперь я лучше понимаю
Классно!

2023-11-24 16:47 UTC, closed without merging