Chapter 1 Task 5
KFalcon2022/intensive-tasks pull request #143
Opened 2023-11-21 08:35 UTC by gsv96

2023-11-22 15:57 UTC, EvgeneZhurov requested changes

2023-11-22 15:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        double circumradius = a * b * c * 0.25 * getAreaByHeron(a, b, c);
Метод выдает неверное значение

2023-11-23 16:50 UTC, gsv96 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double getAreaByHeron(double a, double b, double c) {
Метод getAreaByHeron был так назван разработчиком класса в оригинальном мастере. Исправил, сам так методы буду стараться не называть

2023-11-23 20:23 UTC, EvgeneZhurov requested changes
В целом очень достойно, засчитано.

2023-11-23 20:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        double triangleArea = Math.sqrt(halfPerimeter * (halfPerimeter - a) * (halfPerimeter - b) * (halfPerimeter - c));
можно делать return не вводя переменную, не только в этом методе. Хотя как удобно.

2023-11-23 20:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        if (a + b < c || a + c < b || b + c < a) {
подумайте о случае со сторонами 1 2 3

2023-11-23 20:24 UTC, closed without merging