task2
KFalcon2022/intensive-tasks pull request #151
Opened 2023-11-21 09:31 UTC by AlexGuSpb

2023-11-21 19:50 UTC, ekolokolov requested changes
Не корректное исполнение на данных:
(10, 3, 40)

Expected :40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо
Actual   :1 кв - 4 подъезд, 1 этаж, вправо от лифта.

2023-11-21 19:50 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return  floorNumber + " кв - " + entranceNumber + " подъезд, " + position + " этаж, " + direction
Явно перепутаны переменны. не этаж, а квартира наверное. При этом position - вроде бы не этаж. Разберись пожалуйста

2023-11-22 14:28 UTC, AlexGuSpb commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return  floorNumber + " кв - " + entranceNumber + " подъезд, " + position + " этаж, " + direction
https://github.com/AlexGuSpb/intensive-tasks/commit/ddbb286afcb30eebffb792e050ad4328ae61cb6c

2023-11-23 06:40 UTC, ekolokolov requested changes
Не корректное исполнение на данных:
10, 3, 40

Expected :40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо
Actual   :40 кв - 4 подъезд, 1 этаж, слева от лифта, влево

2023-11-24 14:02 UTC, AlexGuSpb commented
https://github.com/AlexGuSpb/intensive-tasks/commit/54846a20b6188137c65723ae5cb7179142a77725

2023-11-25 11:36 UTC, ekolokolov commented
> [AlexGuSpb@54846a2](https://github.com/AlexGuSpb/intensive-tasks/commit/54846a20b6188137c65723ae5cb7179142a77725)

Не занаю что означает этот комент, но код работает все так же не правильно.

2023-11-26 11:18 UTC, closed without merging