Часть 1 Задача 2
KFalcon2022/intensive-tasks pull request #154
Opened 2023-11-21 10:39 UTC by Kegeke

2023-11-21 10:40 UTC, Kegeke commented
Не смотрите 3 задачу, не знаю откуда она взялась

2023-11-21 20:12 UTC, ekolokolov requested changes
Высокая сложность. 
Не корректно исполняется в исключительных ситуациях:
(10, 3, 121)

Expected : Такой квартиры не существует
Actual   :

2023-11-21 20:12 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                for (int k = 1; k <= 4 ; k++) {                     //по квартирам
три вложенных цикла - это очень плохо с точки зрения производительности. 

Есть варианты без циклов. Лучше использовать их

2023-11-21 20:12 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                    if(flats == flatNumber){
Не забываем про пробелы и форматирование.

2023-11-24 09:13 UTC, Kegeke commented
Привет, запушились левые коммиты

2023-11-24 10:52 UTC, ekolokolov approved these changes
Зачтено. 

Зачел задачу 2

2023-11-24 10:52 UTC, closed without merging