Chapter 1, Task 1
KFalcon2022/intensive-tasks pull request #16
Opened 2023-11-19 09:44 UTC by EkkoXIII

2023-11-19 14:57 UTC, Zawadskiy requested changes

2023-11-19 14:57 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +                switch (age % 10) {
switch вложеніій в switch так себе идея

2023-11-19 14:57 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 10:
10-20 ну есть вариант написать єто более красиво

2023-11-19 14:57 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 10:
как вариант первіій switch заменить на if, а второй switch подкорректировать немного

2023-11-19 14:58 UTC, Zawadskiy requested changes

2023-11-19 14:58 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 10:
как насчет отрицательнііх значений?

2023-11-21 16:42 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 10:
Спасибо, поправил! Разве, что не разобрался, что со вторым switch корректировать. Работает все четко, тем не менее.

2023-11-21 16:58 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else {
Если в If есть return, то else/else if не пишем.

2023-11-21 16:58 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +                case 4: {
Джава синтаксис должен позволить писать 2, 3 , 4 -> {return ""}

Пожалуй засчитаю єту задачу.

2023-11-21 16:59 UTC, closed without merging