HomeFlatSearch
KFalcon2022/intensive-tasks pull request #160
Opened 2023-11-21 11:57 UTC by ETSphere

Странная задачка с одноэтажными подездами или я неверно её понял.

2023-11-21 15:03 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String position = getString(flatNumber);
Итак метод getString(flatNumber);. Идея хорошая, но возможно бііло заменить на switch. Для рефакторинга либо меняешь метод на switch или рефакторишь метод.

2023-11-21 15:05 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String floorPosition1 = "слева от лифта, влево";
Не вижу особого сміісла записіівать єтот текст в переменную. Єто для всех 4х записей.

2023-11-21 15:05 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String position = null;
Зачем? Можно обойтись без переменной.

2023-11-21 15:07 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            position = floorPosition1;
Как насчет return "слева от лифта, влево". Уберем else и сделаем 4 return.
If (flatNumber % 4 == 1) {
return "";
}
if (flatNumber % 4 == 2)...

2023-11-21 15:09 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int maxFlatFloor = 4;
Не єкономим на пустііх строках.

2023-11-21 15:11 UTC, Zawadskiy requested changes

2023-11-21 15:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
>  }
Отпіішите в лк и добавьте себя в табличку.

2023-11-22 09:12 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String position = null;
Это уже IDE решила вывести переменную отдельно за класс с целью использовать в дальнейшем, не стал противится.
Переделаю в switch.

2023-11-22 12:21 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            System.out.printf("Сожалеем в %d подезде, на этаже %d, нет квартиры %d, искомая ", entranceAmount, floorAmount, flatNumber);
поменял структуру согласно ТЗ, убрал самодеятельность запросов.

2023-11-22 12:31 UTC, closed without merging

2023-11-22 18:08 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                return flatNumber + " кв - " + entrance + " подъезд, " + floor + " этаж, справа от лифта, вправо";
Берем из примера задачи где находится квартира.
посколько иных примеров вывода нет - то вводимая квартира - подменяется на квартиру из примера
Примеры:
1 кв – 1 подъезд, 1 этаж, слева от лифта, влево
2 кв – 1 подъезд, 1 этаж, слева от лифта, вправо
3 кв – 1 подъезд, 1 этаж, справа от лифта, влево
4 кв – 1 подъезд, 1 этаж, справа от лифта, вправо
Если такой квартиры в доме нет, укажите это в решении.

https://geometry-math.ru/homework/Java-house.html

спасибо за ревью.