Chapter 1 Task 2
KFalcon2022/intensive-tasks pull request #168
Opened 2023-11-21 15:36 UTC by SenyaDiamond

2023-11-21 20:29 UTC, ekolokolov requested changes
Работает корректно, но решение очень переусложнено. 
Нужно упростить.

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        //Проверки входных значений
Коментарии удалить. Они не нужны

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            flatLocation += "Квартиры " + flatNumber + " в доме нет";
Можно писать сразу return без присвоения.

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            flatLocation += "Параметры дома заданы неверно";
`return "Параметры дома заданы неверно";` - вот так лучше

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        if (flatNumber % (totalFlats / entranceAmount) == 0) {
Лучше сразу корректно высчитывай номер входа. 
Такой трюк очень сложно прочитать и осознать.

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        long floorNumber = ((flatNumber - (((entranceNumber - 1) * 4L * floorAmount) + 1)) / 4) + 1;
Очень сложно. Можно на много проще.

2023-11-21 20:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        if (flatNumber > (4L * floorAmount * (entranceNumber - 1)) + (4L * (floorNumber - 1)) + 2) {
Излишне сложные вычисления. Попробуй упростить.

2023-11-22 12:36 UTC, SenyaDiamond reviewed
Внёс предложенные изменения.

2023-11-22 19:51 UTC, ekolokolov approved these changes
Зачтено

2023-11-22 19:51 UTC, closed without merging