Chapter 1, Task 2
KFalcon2022/intensive-tasks pull request #17
Opened 2023-11-19 09:45 UTC by EkkoXIII

2023-11-19 16:11 UTC, Zawadskiy requested changes

2023-11-19 16:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        if (apartNumber % (roomsPerFloor * floorsQuantity) == 0) {
можно сделать проще ведь отличие только в +1

2023-11-19 16:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            floorNum = apartNumber / roomsPerFloor - (entranceNum - 1) * floorsQuantity;
аналогично, разница в присваивании +1

2023-11-19 16:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            case 0:
для switch/case есть более красивіій вид оформления через ->

2023-11-21 17:14 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            case 0:
Поправил! + остальные комменты тоже учел

2023-11-21 18:06 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            default -> null;
Никогда у тебя не будет default.

2023-11-21 18:07 UTC, closed without merging

2023-11-21 18:12 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            default -> null;
Вот я вроде бы это и понимаю, но идея ругается: типа switch не все значения покрывает. А меня на дефолт один из имеющихся кейсов не очень хочется. В какую сторону здесь смотреть?
![image](https://github.com/KFalcon2022/intensive-tasks/assets/99017055/b0aef6ce-427b-4d55-ab10-ca4aa595ece5)

2023-11-21 18:15 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            default -> null;
можешь убрать case 0  и поставить на него default