Chapter 1 Task 2
KFalcon2022/intensive-tasks pull request #181
Opened 2023-11-21 17:44 UTC by cranium1983

2023-11-22 19:56 UTC, KFalcon2022 requested changes

2023-11-23 19:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +//       String posOnTheFloor = switch (posOnTheFloor) {
Думаю, он ругался на переменную.  String **posOnTheFloor** = switch (**posOnTheFloor**)

2023-11-23 19:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int floorNum = (flatNumber % entranceCapacity == 0) ? floorAmount : (int) Math.ceil((float) (flatNumber % entranceCapacity) / flatsOnFloorAmount);
Старайся не превышать длину строки в 120 символов. Где-то принято 140. В IDEA по умолчанию есть вертикальная черта в редакторе

2023-11-23 19:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                break;
нет смысла в break; после default

Я бы указанное поведение записал в case 0, а default оставил бы для ошибки. Завтра твой код кто-то изменит и в нем окажутся возможны 5, 6 и 10. И все это будет писаться в "справа от лифта, вправо"

2023-11-23 19:25 UTC, closed without merging

2023-11-23 19:37 UTC, cranium1983 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int floorNum = (flatNumber % entranceCapacity == 0) ? floorAmount : (int) Math.ceil((float) (flatNumber % entranceCapacity) / flatsOnFloorAmount);
да, наверняка

2023-11-23 19:37 UTC, cranium1983 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                break;
согласен