Chapter 1, Task 4
KFalcon2022/intensive-tasks pull request #183
Opened 2023-11-21 18:03 UTC by EkkoXIII

2023-11-23 13:08 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if ((a == 0) && (b == 0)) {
Некорректно работает на значениях (0,0,0) - решений  бесконечное множество. 
(0,1,2) - Количество решений: 2. Корни: -Infinity;NaN - выводит Ваша программа.

2023-11-23 13:08 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else {
Здесь else не нужен - можно обойтись без него

2023-11-23 16:02 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if ((a == 0) && (b == 0)) {
Привет! Поправил, в том числе и по второму комменту.
Нюанс: тест для 0,1,2 не совсем актуальный. Ожидает в результате 2, когда верный ответ -2

2023-11-24 16:54 UTC, PomidorkaYulia requested changes

2023-11-24 16:54 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if ((a == 0) && (b == 0)) {
Это я в курсе спасибо) учла это заранее

2023-11-24 16:54 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else {
Вот это замечание не поправили - попробуете еще раз? если что приходите - вместе разберем

2023-11-24 17:11 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else {
Странно.. Видимо не пропушил. Сейчас вроде все должно быть хорошо. Посмотрите, пожалуйста)

2023-11-28 15:23 UTC, PomidorkaYulia approved these changes

2023-11-28 15:23 UTC, closed without merging