Task4
KFalcon2022/intensive-tasks pull request #184
Opened 2023-11-21 18:24 UTC by KungFU13

2023-11-23 13:29 UTC, PomidorkaYulia requested changes

2023-11-23 13:29 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Некорректно работает для вариантов:
(0,0,0) - выводит "Количество решений: 1. Корень: NaN" - должно быть бесконечное множество решений.
(0,0,7) - Количество решений: 1. Корень: NaN - нет корней
(0, 1, 7) - Количество решений: 2. Корни: NaN; NaN - корень один 
 И еще - можно (а значит и нужно) убать else if  и вместо него оставить только if

2023-11-23 18:33 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
исправил

2023-11-24 16:52 UTC, PomidorkaYulia approved these changes

2023-11-24 16:52 UTC, closed without merging