Решение задачи 2 блока 1
KFalcon2022/intensive-tasks pull request #185
Opened 2023-11-21 18:55 UTC by sofajedi

2023-11-22 15:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        }
Не єкономим на пустііх строках.

2023-11-22 15:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int dividedByFlatsOnFloor = flatNumber % 4;
Когда міі используем что-то 1 раз нет особого сміісла вііносить в переменніе. и названия переменнііх более информативнііе.

2023-11-22 18:11 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int dividedByFlatsOnFloor = flatNumber % 4;
Поправил

2023-11-22 18:11 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        }
Поправил

2023-11-22 18:24 UTC, Zawadskiy requested changes

2023-11-22 18:24 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        switch (flatNumber % 4) {
Можно переписать через switch expression, можете почитать и переделать)

2023-11-22 18:24 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int CurrentFlatFloor = totalFlatFloor % floorAmount;
Что-то? переменная с большой буквіі?

2023-11-22 18:24 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            CurrentFlatFloor = CurrentFlatFloor + floorAmount;
сurrentFlatFloor += floorAmount;

2023-11-22 19:23 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            CurrentFlatFloor = CurrentFlatFloor + floorAmount;
Поправил

2023-11-22 19:23 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        int CurrentFlatFloor = totalFlatFloor % floorAmount;
Поправил

2023-11-22 19:23 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        switch (flatNumber % 4) {
Готово

2023-11-23 09:27 UTC, Zawadskiy requested changes

2023-11-23 09:27 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            currentFloor += floorAmount;
Вот тут лишние)

2023-11-23 09:27 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            case 0 ->" справа от лифта, вправо";
После -> пробел.

2023-11-23 09:27 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return flatNumber + " кв - " + flatEntrance + " подъезд, " + currentFloor + " Этаж" + direction;
Этаж - почему с большой где запятая?

2023-11-23 09:27 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
И вот здесь лишнее, я о других пустііх строках писал.

2023-11-23 10:01 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
Поправил

2023-11-23 10:01 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        return flatNumber + " кв - " + flatEntrance + " подъезд, " + currentFloor + " Этаж" + direction;
Поправил

2023-11-23 10:01 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            currentFloor += floorAmount;
Поправил

2023-11-23 10:16 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        };
Вот здесь біі еще пустую добавить. 
Засчитал.

2023-11-23 10:17 UTC, closed without merging