solution of 1 task 1 module
KFalcon2022/intensive-tasks pull request #187
Opened 2023-11-21 19:02 UTC by StasShadrin

2023-11-22 16:00 UTC, Zawadskiy requested changes

2023-11-22 16:00 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if ((age % 10 == 1) && (age % 100 != 11))
всегда ставим { }

2023-11-22 16:00 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if ((age % 10 == 2) && (age % 100 != 12))
Если в if есть return, обіічно else if / else не пишем, простого if достаточно.

2023-11-22 16:00 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if ((age % 10 == 4) && (age % 100 != 14))
4 ОЧЕНЬ похожих сравнения на == и !=, возможно сделать проще.

2023-11-23 10:31 UTC, StasShadrin commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if ((age % 10 == 4) && (age % 100 != 14))
Пока не знаю как убрать повторяющиеся == и !=. Только начал изучать программирование. Убрал повторяющиеся If, объединил в один if.

2023-11-23 10:42 UTC, Zawadskiy requested changes

2023-11-23 10:42 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if ((age % 10 == 2) && (age % 100 != 12) || (age % 10 == 3) && (age % 100 != 13) || (age % 10 == 4) && (age % 100 != 14)) {
(age % 10 > 1 && age % 10 < 5 && (age % 100 < 12 || age % 100 > 15))

Можно диапазоном пройтись, будет еще меньше.

2023-11-23 10:42 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age % 10 == 1 && age % 100 != 11) {
Не єкономим на пустііх строках.

2023-11-23 10:42 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Пустая строка.

2023-11-23 10:42 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Пустая строка.

2023-11-23 11:05 UTC, StasShadrin commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if ((age % 10 == 2) && (age % 100 != 12) || (age % 10 == 3) && (age % 100 != 13) || (age % 10 == 4) && (age % 100 != 14)) {
Спасибо. Так гораздо проще стало))

2023-11-23 11:06 UTC, closed without merging

2023-11-23 11:07 UTC, StasShadrin commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
между }  и if должна быть пустая строка, чтобы отделять блок. правильно я понял?