solution of second task
KFalcon2022/intensive-tasks pull request #193
Opened 2023-11-21 21:37 UTC by dorogao5

2023-11-23 07:15 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:

10, 3, 121

Expected :Такой квартиры не существует
Actual   :121 кв - 4 подъезд, 1 этаж, слева от лифта, влево

2023-11-23 07:15 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String result = String.format("%d кв - %d подъезд, %d этаж, %s", flatNumber, entranceNumber, floorNumber, placeFlat);
Можно не объявлять временную переменную.

2023-11-24 11:16 UTC, ekolokolov requested changes
Не верное исполнение на значениях 

10, 3, 40
Expected :40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо
Actual   :10 кв - 1 подъезд, 3 этаж, слева от лифта, вправо

10, 3, 41
Expected :41 кв - 2 подъезд, 1 этаж, слева от лифта, влево
Actual   :10 кв - 1 подъезд, 3 этаж, слева от лифта, вправо

2023-11-25 09:14 UTC, dorogao5 commented
![image](https://github.com/KFalcon2022/intensive-tasks/assets/145500950/213b414c-10b8-4cbc-84b7-d9c93fe33bfe)
![image](https://github.com/KFalcon2022/intensive-tasks/assets/145500950/af0a462a-d6aa-40df-ab7d-1943f68bcf6a)
Нет, у меня всё верно компилируется при данных параметрах
Видимо это какая то ошибка в тестах
Я нашел другую ошибку, когда код верено отрабатывал отрицательные номера квартиры, но всё остальное у меня работает исправно

2023-11-25 11:33 UTC, ekolokolov approved these changes
Зачтено

2023-11-25 11:33 UTC, closed without merging