Chapter 1 Task 2
KFalcon2022/intensive-tasks pull request #197
Opened 2023-11-22 04:13 UTC by DearCuba

Выполнил задание 2 в главе 1.

2023-11-23 07:26 UTC, ekolokolov requested changes

2023-11-23 07:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static void getFlatLocation(int floorAmount, int entranceAmount, int flatNum, int flatPerFloor) {
Возвращаемое значение вернуть.

2023-11-23 07:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            System.out.println(
Систем ауты убрать.

2023-11-23 07:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static int increment(int x) {
серьезно? 
Есть же встроенные в язык операторы инкремента и декремента. x++ и x--

2023-11-24 17:40 UTC, DearCuba commented
Извиняюсь за спам коммитами. Еще не совсем разобрался как и что тут работает, бывает туплю.

2023-11-24 17:40 UTC, DearCuba commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static int increment(int x) {
К моему большому стыду, это было серьезно. 
Самое страшное, что о таких операторах я знал, но ни при написании этого, ни при проверки пере отправкой меня ничего не смутило...
Спасибо, буду внимательнее.

P.S. Хорошо хоть умножение, путем написания методов на основе сложения не произвожу, есть к чему стремится))

2023-11-24 18:52 UTC, ekolokolov approved these changes
Зачтено

2023-11-24 18:52 UTC, closed without merging