Решение задачи 1 раздела 1
KFalcon2022/intensive-tasks pull request #2
Opened 2023-11-18 20:57 UTC by BigTzar

Решение задачи 1 раздела 1

2023-11-19 16:38 UTC, Zawadskiy requested changes

2023-11-19 16:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age == 0) return "лет";
всегда ставь, даже если одна строчка кода
if () {
}

єто точно отдельніій случай?

2023-11-19 16:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "лет"; // все остальные случаи, например 58, 5, 96, 109 и т.д.
перед return пустую строчку добавляй, исключение если return единственная строка

2023-12-21 13:05 UTC, EvgeneZhurov commented
Если нужна дельнейшая проверка, откройте новый PR

2023-12-21 13:05 UTC, closed without merging