Chapter 1, Task 3
KFalcon2022/intensive-tasks pull request #20
Opened 2023-11-19 10:09 UTC by EkkoXIII

2023-11-19 16:46 UTC, Zawadskiy requested changes

2023-11-19 16:46 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        return year % 4 == 0;
а как же не кратнііе 100?

2023-11-21 17:31 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        return year % 4 == 0;
Поправил!

2023-11-21 17:58 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        return ((year % 4 == 0) && (year % 100 != 0)) || ((year % 100 == 0) && (year % 400 == 0));
((year % 100 == 0) &&  - Вот єто часть не имеет сміісла)
year % 4 == 0 && year % 100 != 0 || year % 400 == 0; Вполне достаточно.

2023-11-21 18:06 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +        return ((year % 4 == 0) && (year % 100 != 0)) || ((year % 100 == 0) && (year % 400 == 0));
Спасибо! Поправил )

2023-11-21 18:13 UTC, closed without merging