Решение задачи Возраст
KFalcon2022/intensive-tasks pull request #200
Opened 2023-11-22 07:01 UTC by ichigovizor

2023-11-23 06:48 UTC, ekolokolov requested changes
Поправить форматирование

2023-11-23 06:48 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int ostatok = age % 10;
ostatok? серьезно?

2023-11-23 06:48 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if ( ostatok == 1 && age != 11 && age != 111){
} eles if () { - только так

2023-11-26 18:55 UTC, ekolokolov commented
Проверь замечания

2023-11-27 04:24 UTC, ichigovizor commented
Внес правки последним коммитом, я так понимаю, он в рамках этого пулла.

2023-11-27 06:27 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if ( modAge == 1 && age != 11 && age != 111){
Ну форматирование же.

2023-11-27 06:27 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
Пустые строки после return - не нужны

2023-11-27 06:29 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if ( ostatok == 1 && age != 11 && age != 111){
Не исправил

2023-11-27 06:29 UTC, closed without merging