Task_4
KFalcon2022/intensive-tasks pull request #202
Opened 2023-11-22 08:17 UTC by Skof1eld

2023-11-24 12:01 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:

0, 1, 2
Expected :Количество решений: 1. Корень: -2
Actual   :Количество решений: 2, x1 = -Infinity, x2 = NaN

2023-11-25 11:41 UTC, ekolokolov requested changes
Поправить названия переменных и результаты вывода

2023-11-25 11:41 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            return "Количество решений: 2. Корни: -1;1 x1 " + x1 + ", x2 = " + x2;
вот эта строка подразумевает что:
1. Решений 2
2. Корни: x=-1 и x=1.

Что такое x1 и x2 вообще не понятно =)
Переменные надо переименовать.

2023-11-25 11:41 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            double x;
Ни каких переменных x или x1,x2 и тд

2023-11-25 11:59 UTC, Skof1eld commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            return "Количество решений: 2. Корни: -1;1 x1 " + x1 + ", x2 = " + x2;
ок, исправлю, а это название ("Количество решений: 2. Корни: -1;1 ") я просто из теста)

2023-11-26 18:52 UTC, ekolokolov approved these changes
Зачтено.

С мелким замечанием

2023-11-26 18:52 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                return "Количество решений: 1" + (-b / (2 * a));
Вот тут забыл слово "Корней".

2023-11-26 18:52 UTC, closed without merging