Chapter1/task1/location_of_the_apartment_20231122_PK
KFalcon2022/intensive-tasks pull request #213
Opened 2023-11-22 11:24 UTC by PavloKutsyn

2023-11-23 07:21 UTC, ekolokolov requested changes

2023-11-23 07:21 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +/**
Коментари убрать. Они тут не нужны

2023-11-23 07:21 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String position = (flatPosition == 0) ? "to the left of the elevator, to the left" :
Попробуй почитать про switch

2023-11-23 07:21 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                                                "to the right of the elevator, to the right";
В задаче все тексты указаны на русском языке. 
Привести к соответствующему виду.

2023-11-23 15:06 UTC, PavloKutsyn commented
Доброго времени суток!
Произвел изменения как и рекомендовали, убрал комемнтарии, построил логику используя switch, текст из английского переделал в русский.

запушил изменения в гит, 
https://github.com/KFalcon2022/intensive-tasks/pull/213/commits/92fbbcaa935d0fb4b47cbdad4e96bf0852b8a2a5
пушил второй раз, потому что не мог найти на сайте куда упали исправления.

p.s.
Мне тяжело даются тернальные операторы, поэтому пробую использовать их чаще.
Дальше на интенсиве буду использовать их, если действительно будет необходимость.

2023-11-24 10:07 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                                                "to the right of the elevator, to the right";
Вывод сделал на русском

2023-11-24 10:56 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                                                "to the right of the elevator, to the right";
Там же прям в задаче есть пример что выводить. 
<img width="545" alt="image" src="https://github.com/KFalcon2022/intensive-tasks/assets/19393584/b6a995b4-5d43-4c25-9281-6fa8eec7dac6">

2023-11-24 10:58 UTC, ekolokolov commented
> p.s. Мне тяжело даются тернальные операторы, поэтому пробую использовать их чаще. Дальше на интенсиве буду использовать их, если действительно будет необходимость.

"Тернарные". это просто очень простая запись if.

2023-11-24 11:00 UTC, ekolokolov requested changes
Код "показывает погоду".

для значения (10, 3, 40) вывод 
`Подъезд: 1, этаж: 3, квартира: 10 слева от лифта, вправо`
хотя должен быть 
`Подъезд: 2, этаж: 1, квартира: 10 (что?) справа от лифта, вправо`

Вообще вывод сильно лучше сдедать как представлено в задаче

2023-11-24 14:28 UTC, PavloKutsyn commented
вот код который работает:

package com.walking.intensive.chapter1.task2;

/**
 * Условие: <a href="https://geometry-math.ru/homework/Java-house.html">ссылка</a>
 */
public class Task2 {
    public static void main(String[] args) {
        int floorAmount = 10;
        int entranceAmount = 3;
        int flatNumber = 88;

        System.out.println(getFlatLocation(floorAmount, entranceAmount, flatNumber));
    }

    static String getFlatLocation( int floorAmount, int entranceAmount, int flatNumber) {
        int flatsPerFloor = 4;
        int totalFlatsPerEntrance = flatsPerFloor * floorAmount;
        int totalFlats = totalFlatsPerEntrance * entranceAmount;

        if (flatNumber < 1 || flatNumber > totalFlats) {
            return "Такой квартиры не существует";
        }

        int entrance = (flatNumber - 1) / totalFlatsPerEntrance + 1;
        int floorWithinEntrance = (flatNumber - 1) % totalFlatsPerEntrance;
        int floor = floorWithinEntrance / flatsPerFloor + 1;
        int flatPositionWithinFloor = floorWithinEntrance % flatsPerFloor;

        String position = switch (flatPositionWithinFloor) {
            case 0 -> "слева от лифта, влево";
            case 1 -> "слева от лифта, вправо";
            case 2 -> "справа от лифта, влево";
            case 3 -> "справа от лифта, вправо";
            default -> throw new IllegalStateException("Unexpected value: " + flatPositionWithinFloor);
        };

        return flatNumber + " кв - " + entrance + " подъезд, " + floor + " этаж, " + position;
    }
}

2023-11-24 18:53 UTC, ekolokolov approved these changes
Зачтено

2023-11-24 18:53 UTC, closed without merging