Решение задачи Дом
KFalcon2022/intensive-tasks pull request #215
Opened 2023-11-22 12:10 UTC by ichigovizor

2023-11-23 07:37 UTC, ekolokolov requested changes
Исправить форматирование

2023-11-23 07:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String positionStr = "empty";
Обычно делают просто "".

2023-11-23 07:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        switch (position) {
Попробуй switch из новых версий Java. Он более компактный.

2023-11-23 07:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        else {
else не должен быть на новой строке.

2023-11-23 07:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            return flatNumber + " кв - " + ((flatNumber-1)/(floorAmount*4)+1) + " подъезд, " + ((((flatNumber-(((flatNumber-1)/(floorAmount*4)))*(floorAmount*4))-1)/4)+1) + " этаж, " + positionStr;
Ну а вот это какая то шаманская магия. Советую вынести часть результатов расчетов в отдельные переменны. 
+ Надо поправить форматирование - пробелы меду операндами и переменными.

Заставь тебя через пару недель разобраться что тут просиходит - ты с ума сойдешь.

2023-11-27 03:56 UTC, ichigovizor commented
Здравствуйте, я внес правки и устранил конфликты, не пойму, что теперь сделать.

2023-11-27 06:32 UTC, ekolokolov approved these changes
Зачтено

2023-11-27 06:32 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int entranceNumber = (flatNumber - 1)/(floorAmount * 4) + 1;
Пробелы между вычислениями `(flatNumber - 1) / (floorAmount * 4)`

2023-11-27 06:32 UTC, closed without merging