Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #223
Opened 2023-11-22 14:20 UTC by SenyaDiamond

2023-11-22 19:53 UTC, EvgeneZhurov requested changes

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
>          double b = 0;
лучше объявить переменные в момент считывания с клавиатуры

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        while (true) {
не используйте while в этой задаче

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +
Вы написали метод solveQuadraticEquation, но не вызвали его из main

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if (b == 0 && c == 0) {
После return не пишут else

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                return "Количество решений: 2. Корни: -" + sqrt(-c / a) + ";" + sqrt(-c / a);
чтобы извлечь корень нужно использовать класс Math.sqrt - Вы прислали программу на проверку которую не можете запустить?

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            if (c / a > 0) {
Перепишите программу без вложенных ветвлений, не используйте вложенные if без крайней необходимости.

2023-11-22 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        }
Поправьте замечания и будем разбираться с задачей дальше.

2023-11-23 04:51 UTC, SenyaDiamond commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                return "Количество решений: 2. Корни: -" + sqrt(-c / a) + ";" + sqrt(-c / a);
Я им и пользуюсь, просто импортировал его в начале: "import static java.lang.Math.sqrt;", для быстрого обращения к методу, так делать не корректно?

2023-11-23 05:18 UTC, SenyaDiamond commented
Исправил замечания, но не позволяет прикрепить их сюда из-за конфликта в файлах, создан новый [PR](https://github.com/KFalcon2022/intensive-tasks/pull/244).

2023-11-23 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                return "Количество решений: 2. Корни: -" + sqrt(-c / a) + ";" + sqrt(-c / a);
В коде лучше писать Math.sqrt лучше импортировать класс вне метода. Повышает читаемость.

2023-11-23 15:44 UTC, EvgeneZhurov reviewed
Не исправлены ранее присланные замечания: После return не пишут else

2023-11-23 15:45 UTC, EvgeneZhurov requested changes
Читайте замечания к коду

2023-11-23 16:04 UTC, SenyaDiamond commented
> Читайте замечания к коду

1. Вложенные ветвления убрал
2. Использовал более полное имя метода кв корня. 
3. Вместо return в if-else использовал строку которую возвращаю вне оператора ветвления. 
4. Содержимое Main привел в порядок (убрал свои внесенные изменения). 

Подскажите, пожалуйста, почему использование return не рекомендуется после - else if -?

2023-11-23 16:06 UTC, SenyaDiamond commented
Исправления вносил в другой [PR ](https://github.com/KFalcon2022/intensive-tasks/pull/244)

2023-11-23 20:42 UTC, EvgeneZhurov commented
Подскажите, пожалуйста, почему использование return не рекомендуется после - else if -?

потому что return возвращает значение из метода. Либо условие выполнится и return либо код и так пойдет исполняться без else.  Это делает код куда более читаемым.

2023-11-23 20:42 UTC, EvgeneZhurov commented
Раз исправления в другом PR закрываем этот

2023-11-23 20:42 UTC, closed without merging