Task1
KFalcon2022/intensive-tasks pull request #224
Opened 2023-11-22 14:50 UTC by LadyShikari

2023-11-22 16:40 UTC, EvgeneZhurov requested changes

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
отступ после }

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int a = i % 10;
отступ

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int a = i % 10;
нужно стараться давать более информативные имена

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if (a == 2 || a == 3 || a == 4) {
После return не ставят else, поправьте везде

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if (a == 2 || a == 3 || a == 4) {
a == 2 || a == 3 || a == 4 - через неравенства условие будет короче

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
пробел не нужен

2023-11-22 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return ("Вам" + age + "лет");
Результат: Вам0лет - нужно поставить пробелы при печати

2023-11-23 11:19 UTC, LadyShikari commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if (a == 2 || a == 3 || a == 4) {
Поубирала везде, но в конце, я же могу оставить else? Так как там условие для все остальных случаев, не входящих в предыдущие If

2023-11-23 13:41 UTC, EvgeneZhurov requested changes

2023-11-23 13:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else {
После return не ставят else

2023-11-23 13:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } if (a >= 2 && a <= 4) {
правильно писать так:
}

if ...

2023-11-23 13:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int i = age % 100;
Давайте информативные имена переменным. Не используйте i для переменной, обычно так называют итератор в цикле.

2023-11-23 13:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int i = age % 100;
Пробел после введения переменной

2023-11-23 14:54 UTC, LadyShikari commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
17-я строка пустая - отступ, если я правильно понимаю, о чем вы

2023-11-25 19:25 UTC, EvgeneZhurov requested changes

2023-11-25 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int a = century % 10;
пустая строка перед int. Давайте переменным информативные имена

2023-11-25 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (century >= 11 && century <= 14) {
пустая строка после int

2023-11-25 19:25 UTC, EvgeneZhurov commented
Задача решена верно. Засчитано.

2023-11-25 19:25 UTC, closed without merging