Chapter1task2
KFalcon2022/intensive-tasks pull request #228
Opened 2023-11-22 18:25 UTC by ChiffaRi

2023-11-23 18:50 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (isCheckFlat(flatNumber, floorAmount, entranceAmount) == false) {
`== false` - избыточно
Более лаконичная и принятая форма записи - `!isCheckFlat(flatNumber, floorAmount, entranceAmount)`

Также есть вопрос по названию метода isCheckFlat. Из контекста непонятно, что это за проверка. я бы предложил название isFlatExists или иное, явно указывающее либо на факт валидации значения, либо на суть этой валидации

2023-11-23 18:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int entrance = findNumberEntry(flatNumber, floorAmount);
findEntryNumber звучит естественнее. number of entry, но entry's number. Ниже аналогично

2023-11-23 18:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > 0 && flatNumber <= (4 * floorAmount * entranceAmount)) {
Чем это отличается от `return flatNumber > 0 && flatNumber <= (4 * floorAmount * entranceAmount)`?

2023-11-23 18:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber % (4 * floorAmount) != 0) {
Использование тернарного оператора сделало бы код лаконичнее и читабельнее

В целом, объявление переменной без инициализации - звонок о том, что мб код стоит несколько изменить. Иногда такая форма (объявление без инициализации) записи действительно нужна. Но не скажу, что части

2023-11-23 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        switch (floorFlat) {
можно return установить перед switch, это сделает конструкцию лаконичнее

2023-11-23 18:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> {
Рекомендую это поведение вынести под case 0, а на default завязать какую-то ошибку. Мб ззатвра кто-то криво доправит твой код и тут может оказаться 5, 6 или 10. И все это будет писаться в "справа от лифта, вправо"

2023-11-23 18:55 UTC, KFalcon2022 requested changes
Хорошая декомпозиция, в остальном стоит немного доработать. При внесении правок оповести в ЛС

2023-11-23 18:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floor;
аналогично

2023-11-24 03:09 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber % (4 * floorAmount) != 0) {
Пробовала тернарный, не получилось. Позже вернусь к нему и подробнее разберу.
А так была мысль использовать.

2023-11-24 03:12 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > 0 && flatNumber <= (4 * floorAmount * entranceAmount)) {
Скорее всего этот метод можно убрать в текущей реализации, избыточная декомпозиция получилась.
И с названиями беда, согласна.

2023-11-24 03:22 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> {
Решила пока не озадачиваться "защитой от дурака", чтобы код не распухал. А еще верю в себя и людей. Иногда.

2023-11-24 14:37 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (isCheckFlat(flatNumber, floorAmount, entranceAmount) == false) {
Эту форму записи встречала. Предпочитаю не использовать "!" рядом с "i", слишком похожи и текст сливается.

2023-11-28 15:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return (flatNumber % (4 * floorAmount) != 0) ? (1 + flatNumber / (4 * floorAmount)) : (flatNumber / (4 * floorAmount));
избыточные внешние скобки

2023-11-28 15:28 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            floor = 1 + (flatNumber - 4 * floorAmount * (entrance - 1)) / 4;
выше с тернаркой получилось. ЗДесь аналогично

2023-11-28 15:28 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floorFlat = flatNumber % 4;
избыточная переменная, лучше выражение впихнуть в условие switch

2023-11-28 15:29 UTC, KFalcon2022 requested changes

2023-11-28 15:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        };
на мой взгляд, стало намного лучше, осталось немного

2023-11-29 17:28 UTC, KFalcon2022 approved these changes

2023-11-29 17:28 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>  }
Засчитываю задачу

2023-11-29 17:28 UTC, closed without merging