Chapter 1 Task 5
KFalcon2022/intensive-tasks pull request #240
Opened 2023-11-23 01:59 UTC by Lunularis

2023-11-24 19:05 UTC, ekolokolov requested changes
1. Прочитать правила оформления (приложены к каждой задаче)
2. Поправить формулу расчета углов.

2023-11-24 19:05 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        p = (a + b + c) / 2; //полупериметр
имя переменной предназначено как раз для того чтобы не гадать что это за значение. 
назови переменную адекватно и не придется везде комменты савать.
Однобуквенные переменных кроме abc - убрать

2023-11-24 19:05 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double[] getAngles(double a, double b, double c) {
Не правильно считает углы

2023-11-25 10:18 UTC, Lunularis commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double[] getAngles(double a, double b, double c) {
Да. Сначала переписала формулу, а потом увидела, что результат нужен в градусах, а не радианах))

2023-11-25 10:19 UTC, Lunularis commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        p = (a + b + c) / 2; //полупериметр
s (площадь) тоже нельзя использовать? это же тоже общепринятое сокращения, наряду с abc
p - тоже общепринятая штука, но редкоупотребимая.

2023-11-25 11:24 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        p = (a + b + c) / 2; //полупериметр
м, можно, но лучше area.

2023-11-25 11:25 UTC, ekolokolov approved these changes
Зачтено

2023-11-25 11:25 UTC, closed without merging