Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #241
Opened 2023-11-23 02:02 UTC by Lunularis

2023-11-24 17:09 UTC, PomidorkaYulia requested changes

2023-11-24 17:09 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Некорректный ответ выдает Ваша программа только при всех нулевых коэффициентах - должно быть бесконечное множество решений. 
Здесь можно избавиться от всех else - просто if -> return затем следующий if.
Попробуете переделать?

2023-11-25 05:27 UTC, Lunularis commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
да, добавила ветку

2023-11-28 15:33 UTC, PomidorkaYulia requested changes

2023-11-28 15:33 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else {
этот else мне видится не нужным - у Вас под ним все условиями обложено

2023-11-29 01:16 UTC, Lunularis commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else {
Не понимаю. 
Если это линейное уравнение, то мне нет смысла считать дискриминант и как-то его анализировать. Поэтому расчет дискриминанта в ветке else.
Ruturn здесь я не поставлю, т.к. в конце функции к строке answer приписываются еще общие для всех веток фрагменты.

2023-12-02 04:49 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (a == 0 & b == 0 & c == 0) {
Есть два типа логических операндов, например & и  && (или  | и ||). "Двойные" вычисляют вторую сторону условия только при необходимости, одинарные всегда. То есть в этом случае - если у Вас a !=0, то все равно будет происходить сравнение с нулем и  b и с. Если бы вы использовали && то получилось, что при невыполнении первого условия все последующие не проверяются. В подавляющем большинстве случаев используют "двойные". 
Вот здесь это описано - https://docs.oracle.com/javase/tutorial/java/nutsandbolts/op2.html (The Conditional Operators). Не думаю что есть смысл это править, но для информации.

2023-12-02 04:54 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else {
Действительно, тут Вы правы - в Вашем решении от этого else не удастся безболезненно избавиться. Но, Вы при условии a == 0 && b == 0 && c == 0 (кстати при таких коэффициентах существует бесконечное множество решений, а не отсутствие решений) - сделали сразу return  - далее можно было бы пользоваться таким же приемом и избежать вложенных if/else. 
В любом случае у Вас есть ненужный else на 52 строке - если Вы оставите там просто if - ничего не изменится. Вообще тройная вложенность это моветон, здесь можно было без этого обойтись. 
Зачитываю задачу в таком виде.

2023-12-02 04:55 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            double d;
и вот тут необязательно было оъявлять на одной строке,  а присваивать на другой. Можно было ( и нужно) сделать в одной.

2023-12-02 04:55 UTC, closed without merging