На проверку
KFalcon2022/intensive-tasks pull request #260
Opened 2023-11-23 13:32 UTC by Captain-Greg

2023-11-24 11:32 UTC, ekolokolov requested changes
Идея интересная, но крайне специфичная. 
Переделай пожалуйста на "более общее" решение. 
Чтобы, например, увеличение возраста,  не требовало переписывания половины кода.

2023-11-24 11:32 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    static boolean ifContain(int x, int[] m) {
Очень медленное решение циклического поиска. 
Ну и в этой задаче оно не нужно.

2023-11-24 11:32 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int[] array1 = {1, 21, 31, 41, 51, 61, 71, 81, 91, 101, 121};
Боюсь представить что ты будешь делать если придется считать возраст например черепах =)

2023-11-24 18:34 UTC, ekolokolov reviewed
Поправить форматирование. Избавиться от пустых ковычек

2023-11-24 18:34 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age >= 0) {/*Едем дальше*/} else {
Убрать пустые скобки.

2023-11-24 18:34 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else return null;
после else фигурная скобка.

2023-11-24 20:39 UTC, Captain-Greg commented
Проверка связи)

2023-11-25 10:55 UTC, ekolokolov approved these changes
Зачтено

2023-11-25 10:55 UTC, closed without merging