Chapter 1 Task2
KFalcon2022/intensive-tasks pull request #267
Opened 2023-11-23 16:30 UTC by sauza7

2023-11-23 19:56 UTC, KFalcon2022 requested changes

2023-11-23 19:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        for (int i = 1 ; i <= entranceAmount ; i++) {
Цикл в данной задаче избыточен, ее можно (и стоит) решить лишь оперируя условными конструкциями и операторами для арифметических действий

2023-11-23 19:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumberInEntrance % 4 == 0 || flatNumberInEntrance % 4 == 3) {
интересное решение, но сама подобная конструкция (if-else и инициализация двух полей в каждом блоке) не слишком удобна в поддержке. Не критичное замечание, но если есть идеи - попробуй исправить

2023-11-23 19:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                flatNumber, entranceNumber, floorNumber , flatPosition, flatDirection);
При внесении исправлений - напиши в ЛС с ссылкой на ПР. https://t.me/ironicMotherfucker

От цикла избавиться обязательно, с if-else - опционально. В остальном качество кода достаточно хорошее

2023-11-24 10:22 UTC, sauza7 commented
Second Solution commit - Удалил цикл for, убрал else инициализировав Strings и меняя при if.  Не очень понял что имеется ввиду "инициализация двух полей в каждом блоке) не слишком удобна в поддержке." - решений вижу несколько для получения того же результата. но все они кажутся мне более громоздкими. Возможно я ошибаюсь.

2023-11-28 15:56 UTC, closed without merging