chapter 1, task 2
KFalcon2022/intensive-tasks pull request #27
Opened 2023-11-19 12:14 UTC by Greem4

2023-11-20 09:37 UTC, EvgeneZhurov requested changes

2023-11-21 16:14 UTC, EvgeneZhurov requested changes

2023-11-21 16:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String location = getFlatLocation(10, 3, 88);
Неверно: 10 этажей, 3 подъезда 80 кв - 1 подъезд, 20 этаж, справа от лифта, вправо

2023-11-21 17:39 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        String location1 = getFlatLocation(10, 3, 88);
не нужно создавать переменную String : System.out.println(getFlatLocation(10, 3, 88));

2023-11-21 17:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
не ставьте пробелы перед закрывающей } Никогда не ставьте 2 пустые строки в коде. Засчитано.

2023-11-21 17:42 UTC, closed without merging

2023-11-21 17:42 UTC, Greem4 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +
Понял , приянл, main делал на скорую руку, чисто копипастом. Спасибо