Chapter 1 Task5
KFalcon2022/intensive-tasks pull request #275
Opened 2023-11-23 20:25 UTC by KungFU13

2023-11-25 15:51 UTC, Zawadskiy requested changes

2023-11-25 15:51 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double[] getAngles(double a, double b, double c) {
Метод не проходит тест.

2023-11-25 20:51 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double[] getAngles(double a, double b, double c) {
были косинусы стали аркосинусы

2023-11-28 16:02 UTC, Zawadskiy requested changes

2023-11-28 16:02 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        double p = (a + b + c) / 2;
Нету проверок на существование треугольника и єто во всех методах.

2023-11-28 16:02 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        if (minValue > valueC){
minValue = Math.min(minValue, valueС); Ну ладно, работает, вроди.

2023-11-28 16:13 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        double p = (a + b + c) / 2;
у меня сразу в самом начале проверка, если не существует, то вроде не должны строки запуститься
if (a + b >= c && a + c >= b && b + c >= a && a * b * c != 0){
        System.out.println("Площадь треугольника: " + getAreaByHeron(a, b, c));
        System.out.println("Высоты треугольника: " + Arrays.toString(getHeights(a, b, c)));
        System.out.println("Медианы треугольника: " + Arrays.toString(getMedians(a, b, c)));
        System.out.println("Биссектрисы треугольника: " + Arrays.toString(getBisectors(a, b, c)));
        System.out.println("Углы треугольника: " + Arrays.toString(getAngles(a, b, c)));
        System.out.println("Длина радиуса вписанной в треугольник окружности: " + getInscribedCircleRadius(a, b, c));
        System.out.println("Длина радиуса описанной в треугольник окружности: " + getCircumradius(a, b, c));
        System.out.println("Площадь треугольника через синус: " + getAreaAdvanced(a, b, c));
        } else {
            System.out.println("Такого треугольника нет");
        }

2023-11-29 17:32 UTC, Zawadskiy requested changes

2023-11-29 17:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
>      static double getAreaByHeron(double a, double b, double c) {
Пустая строка

2023-11-29 17:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        if (a + b > c && a + c > b && b + c > a && a * b * c != 0) {
Делаем реверс. Если не существует return. Условие юзаем несколько раз - можно віінести в метод.

2023-11-29 17:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        System.out.println("Треугольник не существует");
Убрать

2023-11-29 17:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
Аналогично в других методах.

2023-11-29 18:31 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        System.out.println("Треугольник не существует");
исправил

2023-11-29 18:31 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
исправил

2023-11-29 18:40 UTC, Zawadskiy requested changes

2023-11-29 18:40 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
-_-

2023-11-29 18:40 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
-_-

2023-11-29 18:40 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
-_-

2023-11-29 18:40 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
-_-

2023-11-29 18:40 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +        if (isTriangleExist(a, b, c)) {
где реверс?)
if (!isTriangleExist(a, b, c)) { //если не существует
return;
}

обіічная логика...

2023-11-30 08:35 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Main.java
> +
А вот здесь лишняя. Как и в остальнііх местах (if/методах) где только return строка.

2023-11-30 08:36 UTC, closed without merging