Chapter1 task1
KFalcon2022/intensive-tasks pull request #276
Opened 2023-11-23 20:43 UTC by AkBoAl

2023-11-23 21:24 UTC, EvgeneZhurov requested changes

2023-11-23 21:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
пустая строка после }

2023-11-23 21:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1) {
Метод может содержать несколько return. Так код будет легче читать.

2023-11-23 21:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1) {
Попробуйте обойтись без двойных ветвлений

2023-11-23 21:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age%100 == 11 || age%100 == 12 || age%100 == 13 || age%100 == 14) {
Код нужно выравнивать. Читайте правила оформления кода.

2023-11-23 21:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                if (age % 10 == 2 || age % 10 == 3 || age % 10 == 4) {
Если использовать операторы сравнения логическое условие можно сделать меньше. Так будет более читаемо.

2023-11-24 08:38 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age%100 == 11 || age%100 == 12 || age%100 == 13 || age%100 == 14) {
Я же выровнял код комбинацией "вин+альт+L". Что я упустил?

2023-11-24 08:45 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
Укажите, пожалуйста, к какой строке претензия. Потому-как если фигурные скобки закрывать в одной строке " }}} ", то комбинацией "контрол+альт+L" они все переносятся на новые строки.

2023-11-24 08:47 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1) {
А это хорошая практика? Если в методе несколько return'ов, то сложнее код. Но я переделаю

2023-11-24 08:50 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age%100 == 11 || age%100 == 12 || age%100 == 13 || age%100 == 14) {
Код выровнял комбинацией "контрол+альт+L". К какой строчке относится комментарий?

2023-11-24 09:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1) {
нет, смотрится легче.

2023-11-24 09:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age%100 == 11 || age%100 == 12 || age%100 == 13 || age%100 == 14) {
Например к 14. Код не выравнивался

2023-11-24 19:16 UTC, closed without merging

2023-11-24 19:17 UTC, EvgeneZhurov commented
Засчитано