Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #285
Opened 2023-11-24 08:46 UTC by madishkin2

Chapter 1 Task 4

2023-11-25 16:02 UTC, Zawadskiy requested changes

2023-11-25 16:02 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        String message = "Решений бесконечно";
Хз зачем здесь переменная.

2023-11-25 16:02 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                    message = String.format("Количество решений: 2. Корни: %.0f;%.0f" , x2 , x1);
else не нужен если return будет в 59-й строке, ну и без присвоения просто return строку

2023-12-21 13:07 UTC, EvgeneZhurov commented
для дальнейшей проверки просьба открыть новый PR

2023-12-21 13:07 UTC, closed without merging