Chapter#1, task#4
KFalcon2022/intensive-tasks pull request #29
Opened 2023-11-19 12:37 UTC by tasiq

2023-11-19 14:40 UTC, PomidorkaYulia requested changes

2023-11-19 14:40 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (a==0 && b==0){
если с = 0, Ваш алгоритм выдаст - "Нет решений". А их получается бесконечное множество при a, b и с равных нулю

2023-11-19 20:13 UTC, tasiq commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (a==0 && b==0){
Исправил

2023-11-20 03:23 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (a==0 && b==0){
Решение принято, на будущее - можно писать var вместо типа переменной если ты сразу присваиваешь ей(переменной) значение. В программе два выхода на "Нет решений" - но разные тексты. И два выхода на один корень. Это работает корректно, но можно было сделать с меньшим количеством return.

2023-11-20 03:24 UTC, PomidorkaYulia approved these changes

2023-11-20 04:29 UTC, closed without merging