Chapter 1.task 1
KFalcon2022/intensive-tasks pull request #302
Opened 2023-11-24 19:49 UTC by MariaMasha91

Добавила корректировки по комментариям ревьюера:
1) Все расчеты вынесены в метод
2)Для остатков от деления в нем выделены отдельные переменные
3)Использовала Switch, а не if-else, для уменьшения громоздкости

2023-11-25 21:31 UTC, EvgeneZhurov requested changes

2023-11-25 21:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
Валидацию лучше перенести в метод

2023-11-25 21:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        switch (remOfDivBy100) {
Если бы в switch case были реализованы все сценарии по порядку, то это бы объясняло его использование. Напишите код через if

2023-11-25 21:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int remOfDivBy100 = a % 100;
лучше избегать предлогов в названиях и не делайте сокращений.

2023-11-25 21:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                System.out.println("Вам " + a + " лет");
используйте return, в методе их может быть несколько.

2023-11-26 12:43 UTC, MariaMasha91 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        switch (remOfDivBy100) {
Прошлый ревьюер мне сказал наоборот, что if слишком громоздко и давай через switch пожалуйста)))Я отправляла ранее эту задачу, но потом у меня все сломалось и пришлось ветки удалять и заново создавать. Хорошо, сделаю через if

2023-12-08 19:20 UTC, closed without merging

2023-12-08 19:20 UTC, EvgeneZhurov commented
Просьба создать новый PR по этой задаче в случае продолжения ревью.