walking.intensive.chapter1.task1
KFalcon2022/intensive-tasks pull request #32
Opened 2023-11-19 13:25 UTC by AleksandrAkimovChg

КУРСОВАЯ ЗАДАЧА - ВОЗРАСТ
https://geometry-math.ru/homework/Java-age.html

2023-11-19 16:24 UTC, ekolokolov requested changes
Не корректное исполнение для значений:
0, 111, 112, 113, 114

2023-11-19 16:24 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return "Поздравляю! Ты родился.";
По условиям задачи необходимо вывести "Вам 0 лет"

2023-11-19 18:24 UTC, AleksandrAkimovChg commented
> Не корректное исполнение для значений: 0, 111, 112, 113, 114

исправил
@ekolokolov Please review

2023-11-19 18:24 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return "Поздравляю! Ты родился.";
исправил
@ekolokolov Please review

2023-11-20 06:44 UTC, ekolokolov approved these changes
Зачтено (с мелкими замечаниями)

2023-11-20 06:44 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if(age <= 20 || (age > 104 && age < 121)) {
Не забывай про форматирование - пробел между "if"  и "(".

2023-11-20 06:44 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if (age % 10 >= 5 || age % 10 == 0) {
Вообще можно несколько условий, которые возвращают одинаковый результат, объединить. Можешь попробовать если есть желание.

2023-11-20 06:44 UTC, closed without merging