Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #321
Opened 2023-11-25 23:40 UTC by dm-evstafiev

2023-11-27 19:12 UTC, EvgeneZhurov requested changes

2023-11-27 19:12 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                return "Решений бесконечно";
double a = 0;
        double b = 0;
        double c = 1;
неверный результат

2023-11-27 19:12 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0) {
Лучше писать более сложные логические условия используя && или ||, чем писать вложенные if без крайней необходимости.

2023-11-27 19:12 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else {
после return не пишут else, поправьте везде в коде

2023-11-27 19:12 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 2. Корни: " + (int) x1 + ";" + (int) x2;
не уходите от вещественных чисел. чтобы пройти тесты. Программа создается не для тестов

2023-11-28 07:22 UTC, EvgeneZhurov requested changes

2023-11-28 07:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b != 0 && c != 0) {
c != 0    - это условие лишнее. Даже если с=0, все равно 1 корень

2023-11-28 07:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if ((a != 0 || b != 0) && c == 0) {
это условие делает решение задачи неверным
        double a = 1;
        double b = -2;
        double c = 0;
Дает 2 решения

2023-11-28 07:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 && (-c / a) >= 0) {
(a != 0 && (-c / a) >= 0) - мне не очень понятна цепочка логических условий и причем здесь -c / a?  Если уравнение квадратное, количество решений зависит только от дискриминанта.

2023-11-28 08:21 UTC, dm-evstafiev commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 && (-c / a) >= 0) {
Спасибо! Я попробую еще.
К сожалению, с логикой у меня совсем что-то плохо, запутался напрочь

2023-11-29 18:44 UTC, EvgeneZhurov requested changes

2023-11-29 18:44 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 && b != 0 && c == 0) {
Придется переделывать, этот случай должен быть реализован в случае, если дискриминант положительный, и не нужно отталкиваться от частного случая, что с = 0, если a != 0 && b != 0, то если дискриминант положительный, то решений 2.

2023-11-29 18:44 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (c == 0) {
этого условия про c == 0 вообще не должно быть в задаче отдельно.
Должно быть всего 5 логических условий:
1) a == 0, b == 0, с == 0
2) a == 0, b == 0
и 3 условия на дискриминант.

2023-12-03 21:57 UTC, closed without merging