Chapter 1. Task 1. Решение.
KFalcon2022/intensive-tasks pull request #33
Opened 2023-11-19 13:34 UTC by tvadim1

2023-11-19 16:17 UTC, ekolokolov requested changes
Решение работает но требуется изменение замечаний.

2023-11-19 16:17 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    public static int[] forbiddenArray = {11, 12, 13, 14};
Если объявлять константный блок то он должен быть private static final. В таком случае название переменной надо писать через snake_case. например FORBIDDEN_ARRAY = {11, 12, 13, 14}

2023-11-19 16:17 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int i = 0; i < forbiddenArray.length; i++) {
Можно сделать сильно проще. Или привести ageString изначально к числу или в forbiddenArray хранить строки (чтобы не конвертировать их каждый раз)

Но вообще это выглядит как дикое переусложнение.

2023-11-19 16:17 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    public static boolean isFoundInForbiddenArrayCheckedByLinearSearch(String ageString) {
Название метода надо упростить. Слишком большое и говорит не только что делает но и как.

2023-11-19 18:04 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    public static int[] forbiddenArray = {11, 12, 13, 14};
Оу, понел! не подумал, даже думал enum какой-то нужен и как-то с ним работать, но т.к. по основному курсу, еще не дошел до него, подумал будет неправильно изображать то, что еще не изучил

2023-11-19 18:05 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int i = 0; i < forbiddenArray.length; i++) {
благодарю за ремарки, согласен, тут слишком много переводов из одного типа в другой, в силу небогатого опыта кроме как того, что в чем бы я не сомневался, пришло в голову только String.indexOf(), (заоодно посмотрел чем отличается от lastIndexOf()). Наверное можно было как-то через charAt, но не знаю. В самом начале хотелось регулярное выражение, по обучающим урокам на ютубе делал было простенький вход в Десктоп приложение с проверкой в БД а-ля

_String reg = "^[A-Za-z0-9+_.-]+@(.+)$"; 
Pattern pattern = Pattern.compile(reg);
Matcher matcher = pattern.matcher(loginText);_

но т.к. нужно прям проникнуться идеей за несколько дней, и понять что к чему в регулярных, да и я опять же по курсу не дошел, оставил эту идею в стороне. Да и вроде на хабре потом видел, что делают через emailvalidator класс,т.е. даже там регулярные не нужны. 
в итоге сейчас исправил как смог,а позже посмотрю на лучшее решение, когда ответы вы выложите :)

2023-11-19 18:15 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +    public static boolean isFoundInForbiddenArrayCheckedByLinearSearch(String ageString) {
исправил на глагол findForbiddenArray  :)

2023-11-20 06:50 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int i = 0; i < forbiddenArray.length; i++) {
Почему вообще строка? Храни "забытые" дни в виде чисел, тогда не придется ничего конвертировать. 

```Java
 private static final int[] FORBIDDEN_ARRAY = {11, 12, 13, 14};

 public static boolean findInForbiddenArray(int age) {
        for (int forbidden : FORBIDDEN_ARRAY) {
            if (age == forbidden) {
                return true;
            }
        }
        return false;
    }
```

2023-11-20 06:51 UTC, ekolokolov approved these changes
Принято. С замечаниями.

2023-11-20 06:51 UTC, closed without merging