Chapter 2 task 6
KFalcon2022/intensive-tasks pull request #339
Opened 2023-11-26 16:36 UTC by MagPier

2023-11-28 17:29 UTC, KFalcon2022 requested changes

2023-11-28 17:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
Крайне переусложненное решение. Задача не требует коллекций и даже массивов в любом более-менее оптимальном алгоритме. По сути, ты создаешь здесь проблему и мужественно с ней борешься) попробуй упростить, здесь достаточно циклов, условий и примитивов. Если не будет идей как - напиши в ЛС, будем вместе рассуждать

При внесении правок - тоже пиши. В обоих случаях с ссылкой на ПР. https://t.me/ironicMotherfucker

2023-12-01 19:29 UTC, KFalcon2022 requested changes

2023-12-01 19:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (number1 < number2) {
если ты предполагаешь, что могут быть переданы отрицательные числа (судя по условию ниже) логично это учитывать. Например, отбрасывать "-"

2023-12-01 19:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return number1;
почему именно number1? Не очень понимаю логику. -2 и -5. Их НОД == 1. В твоем случае будет -2

2023-12-21 13:10 UTC, EvgeneZhurov requested changes

2023-12-21 13:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>      public static void main(String[] args) {
1 pr 1 задача

2023-12-21 13:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGreatestCommonDivisor(number2, number1 % number2);
После return не ставят else

2023-12-28 19:11 UTC, KFalcon2022 approved these changes

2023-12-28 19:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (number2 > 0) {
не хватает пустой строки перед if для разделения блоков кода с разной логикой

2023-12-28 19:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGreatestCommonDivisor(number2, number1 % number2);
замечание не исправлено

2023-12-28 19:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
Оставшиеся замечания считаю мелкими. Задача зачтена

2023-12-28 19:11 UTC, closed without merging