Chapter 2 Task 8
KFalcon2022/intensive-tasks pull request #354
Opened 2023-11-26 20:23 UTC by tasiq

2023-11-28 20:57 UTC, EvgeneZhurov requested changes

2023-11-28 20:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 0; i<=999999; i++){
Код нужно выравнивать: читайте правила оформления перед сдачей.

2023-11-28 20:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 0; i < 3; i++) {
Использовать 2 цикла для подсчета одного и того же? Выглядит громоздко, Лучше 1 цикл от 0 до 6 с встроенным if

2023-11-28 22:30 UTC, tasiq commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 0; i<=999999; i++){
Исправил, уже не в первый раз, жуть как стыдно

2023-11-28 22:30 UTC, tasiq commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 0; i < 3; i++) {
Сделал 1 цикл.
В каком направлении почитать, чтобы в будущем я самостоятельно мог оценить, что в подобных ситуациях один цикл со встроенным if лучше двух более коротких циклов?

2023-11-29 17:19 UTC, closed without merging

2023-11-29 17:19 UTC, EvgeneZhurov commented
засчитано