chapter 2 task 10
KFalcon2022/intensive-tasks pull request #355
Opened 2023-11-26 20:46 UTC by lambo64

Добрый вечер) На английском работает, при вводе текста на русском все слетает. При чем вне зависимости от использования стрингбилдера или циклов. что я делаю не так(

2023-11-28 20:59 UTC, EvgeneZhurov requested changes
в PR не вложен код с решением.

2023-11-30 12:09 UTC, lambo64 commented
куда-то все пропало. Написала заново, проблема с русским не ушла

2023-12-02 10:05 UTC, EvgeneZhurov requested changes

2023-12-02 10:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +        System.out.println(isPalindrome("rerer"));
1 pr - 1 задача. Сейчас 2 задачи в 1 pr.

2023-12-02 10:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +        String str = example.replaceAll(" ", "").replaceAll("\\p{Punct}", "");
Объявлять символы в задаче можно, но просьба решить задачу без введения строк и использования тем, которые не были затронуты в курсе.

2023-12-02 19:14 UTC, lambo64 commented
нечаянно назвала 9 заданием вместо 10. И лишнюю задачу не смогла найти( Но саму задачу переделала

2023-12-03 19:53 UTC, EvgeneZhurov requested changes

2023-12-03 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +            char[] array = string.toCharArray();
решите задачу без массивов.

2023-12-03 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +            if (isLetter(c)) {
не увидел метода isLetter.

2023-12-03 19:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +        String stringWithoutPunctuation = "";
решите задачу без введения новых String во всем коде, используя только примитивы.

2023-12-05 20:26 UTC, lambo64 commented
переделала, вроде все учла)

2023-12-05 21:06 UTC, EvgeneZhurov requested changes

2023-12-05 21:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Main.java
> +        System.out.println(isPalindrome("aa.aba fAa"));
При вводе строки " ,!Aa" ожидалось - true
выдается false.

2023-12-16 20:19 UTC, EvgeneZhurov commented
для продолжения просьба создать новый PR, этот висит без изменений больше недели

2023-12-16 20:19 UTC, closed without merging