КУРСОВАЯ ЗАДАЧА - ВОЗРАСТ
KFalcon2022/intensive-tasks pull request #36
Opened 2023-11-19 14:31 UTC by koi1966

2023-11-19 16:22 UTC, ekolokolov requested changes
Не проходят следующие сценарии:
111, 112, 113, 114

2023-11-19 16:22 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +                return s + Integer.toString(age) + " лет";
Integer.toString(age) можно заменить на просто age. Java сама вызовет toString для формирования строки

2023-11-20 19:30 UTC, koi1966 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +                return s + Integer.toString(age) + " лет";
Благодарю, исправил.

2023-11-22 08:06 UTC, ekolokolov requested changes
Нужно поработать над реализацией и форматированием.

2023-11-22 08:06 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int id : ageArray) {
Если вводишь константые значения, то можно их вынести как private static final.
Однако поиск по массиву не очень быстрый. Лучше обойтись без него.

2023-11-22 08:06 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        String s = "Вам ";
s - плохое название для переменной. 
Название переменной должно быть осмесленным

2023-11-22 08:06 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int id : ageArray) {
Что значит id?

2023-11-22 08:06 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 2:
вместо 
```Java
            case 2:
            case 3:
            case 4:
```
можно написать 
```Java
case 2, 3, 4:
```

2023-11-24 11:22 UTC, koi1966 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            case 2:
Сорри, я не смотрел сюда, буду думать над замечаниями.

2023-11-24 12:30 UTC, koi1966 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int id : ageArray) {
У меня два варианта было или массив или ArrayList.
Я посчитал что массив () предпочтительней, тем более еще и final. 
Или есть еще что-то предпочтительнее ?

2023-11-24 18:35 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        for (int id : ageArray) {
Можно было вообще без циклов обойтись

2023-11-24 18:36 UTC, ekolokolov approved these changes
Зачтено

2023-11-24 18:36 UTC, closed without merging