Solution Chapter 2  Task 6
KFalcon2022/intensive-tasks pull request #370
Opened 2023-11-27 09:41 UTC by k2336351

Решение Глава 1 Задача 6

2023-11-28 21:19 UTC, EvgeneZhurov requested changes

2023-11-28 21:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i <= m && i <= n; i++) {
i <= m && i <= n более легко написать через Math.max, лучше написать до минимального числа из пары. Зачем идти дальше?

2023-11-28 22:55 UTC, k2336351 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i <= m && i <= n; i++) {
Точно, и мне бросалось в глаза, что это коряво, но не смогла придумать лучше, а оказывается, что ларчик просто открывался :)

2023-11-29 18:38 UTC, EvgeneZhurov commented
засчитано

2023-11-29 18:38 UTC, closed without merging