Chapter 2. Task 6.
KFalcon2022/intensive-tasks pull request #372
Opened 2023-11-27 10:06 UTC by tvadim1

2023-11-28 21:35 UTC, EvgeneZhurov requested changes

2023-11-28 21:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int ostatok = ceiling % floor;
не используйте транслит в названиях

2023-11-28 21:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getNodByEuclideanAlgorithm(floor, ceiling); //рекурсия
избегайте предлогов в названиях.

2023-11-28 21:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        LinkedList<Integer> mKratinie = new LinkedList<>();
решите задачу без коллекций.

2023-11-29 11:02 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int ostatok = ceiling % floor;
изменил на remainder

2023-11-29 11:02 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        LinkedList<Integer> mKratinie = new LinkedList<>();
исправил, теперь без коллекций

2023-11-29 18:36 UTC, EvgeneZhurov requested changes

2023-11-29 18:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            currentM = i * n;
двойной цикл в задаче не нужен, попробуйте решить без него.

2023-11-29 19:19 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            currentM = i * n;
Действительно, как-то не сразу додумался, что если общее кратное, значит остаток от деления для обоих должен быть равен нулю, и от второго прохода цикла можно отказаться, т.е. логика проверки не **m->неизвестное кратное<-n**, а **m->неизвестное кратное->n**

2023-11-29 19:22 UTC, EvgeneZhurov requested changes

2023-11-29 19:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            ceiling = remainder;
эта ветвь лишняя, можно ниже в рекурсию в качестве агрумента вводить remainder

2023-11-29 19:23 UTC, EvgeneZhurov commented
Засчитано

2023-11-29 19:23 UTC, closed without merging