Chapter_2_Task_6
KFalcon2022/intensive-tasks pull request #375
Opened 2023-11-27 11:44 UTC by Skof1eld

2023-11-29 17:00 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        Scanner in = new Scanner(System.in);
In не лучшее название для переменной, давай для названия переменных будем использовать осмысленные существительные.

2023-11-29 17:02 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        in.close();
закрытие сканера стоит отделить пустой строкой от кода получения значения переменной. это улучшит читаемость.

2023-11-29 17:02 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
избыточную пустую строку убрать, достаточно одной.

2023-11-29 17:04 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
всегда отделяем методы друг от друга пустыми строками.

2023-11-29 17:04 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getNod(int m, int n) {
пустая строка между методами.

2023-11-29 17:08 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getNodByEuclideanAlgorithm(int m, int n){
пропустил пробел между скобками, так же прожимай ctrl+alt+L для форматирования.

2023-11-29 17:10 UTC, knownAsPuffy requested changes
Поправить комменты. Вопросы только по формату. В остальном +.

2023-11-29 18:13 UTC, Skof1eld commented
> Поправить комменты. Вопросы только по формату. В остальном +.

Простите, что - то много с оформлением накосячил, некоторые моменты не знал, спасибо!

2023-11-30 16:10 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
а вот тут пустая трока не очень нужна. выполняем две логически похожие операции.

2023-11-30 16:11 UTC, closed without merging