Chapter 2 Task 7
KFalcon2022/intensive-tasks pull request #376
Opened 2023-11-27 12:12 UTC by SahaPWNZ

2023-11-29 17:32 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getFriendlyPair(int N) {
1. Имя переменной исправить на строчную.
2. Метод работает неправильно, ориентируемся на пример из условия задачи.

2023-11-29 17:34 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sum1number = 0;
не используем "магические" цифры в имени переменной. и всегда camelCase. стараемся использовать осмысленные существительные.

2023-11-29 17:35 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sum2number = 0;
поправить имя переменной

2023-11-29 17:36 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
>          return 0;
отделяем return от логических блоков кода пустой строкой. исключение: return единственная строка в блоке кода (метод, тело if и т.д.).

2023-11-29 17:36 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +
избыточная пустая строка. ниже нечего отделять.

2023-11-30 07:40 UTC, SahaPWNZ commented
Замечания поправил: оформление и согласно условию задачи добавил чтобы метод выводил большее число в паре

2023-11-30 16:30 UTC, knownAsPuffy requested changes
Решение не правильное, перечитай и разберись в условии задачи. При int = 200, решение будет 0. у тебя 28) разбираемся и правим.

2023-11-30 16:31 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
>          return 0;
забыл отделить return

2023-12-01 08:20 UTC, SahaPWNZ commented
Согласен, пересмотрел код, добавил условие, согласно заданию, что числа должны отличаться, сейчас вроде со всем работает корректно

2023-12-05 07:15 UTC, SahaPWNZ commented
Эх, понял - буду разбираться(

2023-12-05 11:00 UTC, SahaPWNZ commented
Ну я проверил ещё раз, со всеми значениями работает корректно, может просто коммит какой-то не дошёл с последних, запушил ещё раз

2023-12-05 15:12 UTC, knownAsPuffy approved these changes

2023-12-05 15:12 UTC, knownAsPuffy commented
вопросов нет

2023-12-05 15:12 UTC, closed without merging