Chapter 2 Task 8
KFalcon2022/intensive-tasks pull request #377
Opened 2023-11-27 13:24 UTC by SahaPWNZ

2023-11-29 17:51 UTC, EvgeneZhurov requested changes

2023-11-29 17:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) count / ticketNumber * 100;
неверный результат. Вероятность не может быть болье 1 и не исчисляется в %

2023-12-01 08:45 UTC, SahaPWNZ commented
Поправил замечание, + изменил имена переменных на более понятные и добавил учет счастливого номера 000_000, до этого его не учитывал

2023-12-02 09:34 UTC, EvgeneZhurov requested changes

2023-12-02 09:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) countHappyTicket / ticketNumber;
Все еще неверно выводит результат. Общее количество билетов не 999999

2023-12-05 14:43 UTC, EvgeneZhurov requested changes

2023-12-05 14:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) countHappyTicket / (ticketNumber +1);
код нужно выравнивать. Читайте правила оформления задачи перед отправкой.

2023-12-05 14:43 UTC, closed without merging

2023-12-05 14:43 UTC, EvgeneZhurov commented
засчитано