Chapter 2 Task 7
KFalcon2022/intensive-tasks pull request #378
Opened 2023-11-27 13:26 UTC by tvadim1

2023-11-29 17:59 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getFriendlyPair(int m) {
метод работает некорректно, ошибка в вычислениях. переписать. ориентируемся на пример из задачи для самостоятельной проверки.

2023-11-29 18:00 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m - 1; i > 0; i--) {     //натуральные числа начинается от единицы, т.е i>0
комментарии оставляем над строками, так удобней читать по вертикали.

2023-11-29 18:01 UTC, knownAsPuffy requested changes
Ошибка в вычислениях.

2023-11-29 19:26 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        System.out.printf("Для N = %d искомое число = %d", n, getFriendlyPair(n));
исправил, не заметил было

2023-11-29 19:41 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getFriendlyPair(int m) {
исправил ошибки оформления, но не совсем понял, что неправильно конкретно в методе. проверял до n=15000 - пары находятся корректно, метод возвращает самое большое значение из пары (согласно условию), сама пара выводится в консоль  (4 минуты вычислений)
![image](https://github.com/KFalcon2022/intensive-tasks/assets/9698419/16d31e1c-85f4-4a50-a7b0-9382bdc15bdc)

2023-11-30 16:18 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            }
разделить ифы пустой строкой

2023-11-30 16:18 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +
убрать пустую строку, над комментарием она ни к чему)

2023-11-30 16:21 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m - 1; i > 0; i--) {
давай попробуем уйти от вложенных циклов, это скажется на производительности в лучшую сторону)

2023-11-30 16:22 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                    return Math.max(i, j);
return всегда отделяем пустой строкой, исключение если это единственная строка в логическом блоке кода.

2023-11-30 16:23 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getFriendlyPair(int m) {
да расчеты верны , согласен

2023-11-30 16:23 UTC, knownAsPuffy requested changes
поправить комментарии

2023-11-30 16:57 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                    return Math.max(i, j);
понел, принел)

2023-11-30 16:59 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            }
исправлено, буду знать

2023-11-30 18:01 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m - 1; i > 0; i--) {
разрешите вопрос, которые меня давно мучает, как называть правильно интерфейс? с припиской (например) IFunction, IClonable, существительным-сущностью или страдательным причастием или это местное соглашение внутри компании разработчиков, как вы ориентируетесь?
какие еще правила к контексте оформления применяемые в русскоязычной практике, которые необходимо прям в голове держать, как, например, те что перечислены в правилах оформления интенсива + избавление от магических чисел, название контант по типу CAMEL_CASE и этом духе, т.е. то, что вы прям в голове держите.

2023-12-02 06:50 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m - 1; i > 0; i--) {
Погугли "конвенция наименований java". В целом, пока, этого будет достаточно.

2023-12-02 06:50 UTC, knownAsPuffy approved these changes
в целом хорошо

2023-12-02 06:51 UTC, closed without merging

2023-12-02 12:01 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m - 1; i > 0; i--) {
Действительно, не знал, что есть такая "спецификация", прочитал, благодарю.