Capter1 task4
KFalcon2022/intensive-tasks pull request #394
Opened 2023-11-27 18:14 UTC by ETSphere

прошу прощение за опоздание, постараюсь наверстать.

2023-11-28 11:20 UTC, ekolokolov requested changes
Разберись с кодировкой на своей машине, иначе все следующие задачи будут для тебя и нас огромной проблемой. 
Поправь ошибки в названиях переменных.

2023-11-28 11:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        /*���� D < 0 � �� ���������� ��������� �� ����� �������;
Золотое правило: 
Если ты оставляешь комментарии в коде, чтобы объяснить что в этом коде происходит - значит твой код плохой. 
Комментарии убрать.

2023-11-28 11:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +          ���� D = 0 � �� ��������� ����� ����� ������ ���� ������;
Классно что ты починил кодировку на своем компьютере.
Плохо что это теперь не работает ни у кого другого.

2023-11-28 11:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                int rounedSecondMS = (int) Math.floor(secondMS);
не знаю слова `rouned` (3 раза встречается по коду)

2023-11-28 17:50 UTC, ETSphere commented
Учел визуальные ошибки, поменял кодировку. Надеюсь не отвлеку сильно.

2023-11-30 06:44 UTC, ekolokolov approved these changes
Зачтено

2023-11-30 06:44 UTC, closed without merging