Chapter 2, task 7
KFalcon2022/intensive-tasks pull request #401
Opened 2023-11-27 23:01 UTC by EkkoXIII

На значении до 15000 еще худо-бедно работает, но на больших задумывается на очень долго. Как оптимизировать перебор не придумал =(
Подскажите, плиз, в каком направлении думать.

2023-11-29 18:59 UTC, KFalcon2022 requested changes

2023-11-29 18:59 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +    public static int getDivisorsSum(int integer) {
парметр логичнее назвать number или иным подобным образом

2023-11-29 18:59 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +                result += i + integer / i;
пожалуй, наиболее эффективный способ получения суммы делителей из тех, что я видел

2023-11-29 18:59 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        int sum = 0;
стоит обозначить, что речь идет о максимальной сумме

2023-11-29 18:59 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +            for (int j = i + 1; j <= maxInteger; j++) {
Задачу можно решить без вложенного цикла, это повысит производительность кода

2023-11-29 18:59 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        return result;
При внесении исправлений напиши в ЛС с ссылкой на ПР. https://t.me/ironicMotherfucker

2023-11-30 05:15 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +                result += i + integer / i;
Спасибо! Гугл помог) Другие комментарии учел.

2023-12-06 13:15 UTC, KFalcon2022 requested changes

2023-12-06 13:32 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        return (number != getDivisorsSum(number)) && (number == getDivisorsSum(getDivisorsSum(number))) && (getDivisorsSum(number) < maxInteger);
> > number != getDivisorsSum(number)
> > с таким условием мы точно дружественное число?

Если number = getDivisorsSum(number), то number будет уже совершенным числом. 
В условиях задачи про это не сказано, но интуиция подсказывает, что совершенные числа все же в ряд дружественных не входят, поэтому и исключаю их таким образом. 

А вот с остальным условием чего-то и правда накосячил: сравнил число с суммой его делителей (кандидат гна "дружественность"). 
Нужно еще добавить проверку суммы делителей кандидата на "дружественность" на равенство с входящим числом.

2023-12-06 17:35 UTC, EkkoXIII commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        for (int i = 2; i < Math.sqrt(number); i++) {
Допилил

2023-12-06 19:39 UTC, KFalcon2022 approved these changes

2023-12-06 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +                } else {
рекомендую через тернарку сделать

2023-12-06 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        int friendlyNumberCandidate = getDivisorsSum(number);
тут  (и в какой-то переменной выше) можно проще отнестись к названию. devisorsSum было бы достаточным определением. Иногда длинное, хоть и исчерпывающее, название идет не на пользу

2023-12-06 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
>  }
Замечания мелкие, задача засчитана

2023-12-06 19:40 UTC, closed without merging