Chapter 2 Task 7
KFalcon2022/intensive-tasks pull request #405
Opened 2023-11-28 06:43 UTC by SenyaDiamond

2023-11-29 19:10 UTC, EvgeneZhurov requested changes

2023-11-29 19:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < m; i++)
System.out.println(getFriendlyPair(100));
ответ: 28
ожидалось: 0
придется переделать.

2023-11-30 05:25 UTC, SenyaDiamond commented
Да, не приметил в условии, что i != j. Спасибо, поправил.

2023-12-02 11:12 UTC, EvgeneZhurov requested changes

2023-12-03 19:32 UTC, EvgeneZhurov requested changes

2023-12-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int maxFriendlyNumber = 0;
лучше объявлять переменные максимально близко к месту их использования.

2023-12-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = m; i > 1 ; i--)
отделяйте блоки кода пустыми строками, это улучшает читаемость.

2023-12-03 19:32 UTC, EvgeneZhurov commented
засчитано.

2023-12-03 19:32 UTC, closed without merging