Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #425
Opened 2023-11-28 14:10 UTC by DearCuba

2023-11-28 14:38 UTC, Zawadskiy requested changes

2023-11-28 14:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +      answer = "Количество решений: 1. Корень: " + String.format("%.0f", (-c / b));
Почему біі не вернуть ответ сразу? Тогда переменная не пригодится.

2023-11-28 14:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    } else if (a == 0 && b == 0 && c == 5) {
Хорошая попіітка подогнать под тестіі, но нет)

2023-11-28 14:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    } else {
Вложености єто плохо, избавляемся от них.

2023-11-28 14:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +          answer = "Количество решений: 2. Корни: " + String.format("%.0f", firstRoot) + ";"
Почему біі не вернуть ответ сразу?

2023-11-28 14:38 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +          answer = "Количество решений: 2. Корни: " + String.format("%.0f", secondRoot) + ";"
Аналогично.

2023-11-29 17:37 UTC, Zawadskiy requested changes

2023-11-29 17:37 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    } else if (a == 0 && b == 0 && c == 0) {
После return else не пишем. Хватит и просто if. Между if пустііе строки.

2023-11-29 17:37 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    } else {
Зачем else?

2023-11-29 18:49 UTC, DearCuba commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    } else {
Думал, что if else (пример ниже) устойчивая конструкция и менять ее не рекомендуется. Теперь понимаю, что, если не сработало все что было выше, выбор не велик.

if (boolean condition) { 
do something
}
else { 
do something
}

2023-12-06 10:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    }
Пустая строка

2023-12-06 10:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +      return firstRoot < secondRoot ? "Количество решений: 2. Корни: " + (int) firstRoot + ";"
Пустая строка

2023-12-06 10:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    return ("Количество решений: 0.");
Пустая строка

2023-12-06 10:59 UTC, closed without merging