Chapter1 task2
KFalcon2022/intensive-tasks pull request #426
Opened 2023-11-28 14:33 UTC by Akarumai

Сделал задание 2. Посмотрите, пожалуйста.

2023-11-29 19:49 UTC, EvgeneZhurov requested changes

2023-11-30 12:05 UTC, Akarumai commented
Внес изменения в последнем коммите. Теперь ввод отрицательных этажей и подъездов выдает ошибку ввода.

2023-12-02 10:09 UTC, EvgeneZhurov requested changes

2023-12-02 10:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            return "Ошибка ввода. Число не может быть отрицательным или равным нулю.";
Читайте правила оформления кода перед сдачей: https://github.com/KFalcon2022/intensive-tasks/tree/master#правила-оформления-кода

2023-12-02 10:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String flatLocation = "";
объявляйте переменные максимально близко к месту использования.

2023-12-02 10:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > 4 * floorAmount * entranceAmount)
отделяйте блоки кода пустыми строками, код будет читаться легче

2023-12-02 10:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int entranceNumber = (flatNumber - 1) / (floorAmount * 4) + 1; //Подъезд квартиры
Почитайте про "магическое число java" - здесь это число 4. Представьте, что завтра Вам поступил новая задача, сделать такую же задачу с 6 квартирами на этаже. Сделайте "число квартир на этаже " отдельной неизменяемой переменной используя модификатор доступа final

2023-12-04 08:47 UTC, Akarumai commented
Добрый день. Внес правки по комментариям, посмотрите, пожалуйста.
Также хотел спросить. Я правильно понимаю, что при получении комментариев достаточно все поправить, закоммитить, запушить и отписаться в ветке обсуждения (то есть здесь)? Снова жать на пулреквест не нужно?

2023-12-04 19:41 UTC, EvgeneZhurov commented
новый PR делать не нужно

2023-12-04 19:44 UTC, EvgeneZhurov commented
засчитано

2023-12-04 19:44 UTC, closed without merging