Chapter 2 Task 9
KFalcon2022/intensive-tasks pull request #429
Opened 2023-11-28 17:08 UTC by tvadim1

2023-11-28 18:13 UTC, EvgeneZhurov requested changes

2023-11-28 18:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +import java.util.ListIterator;
написал в личку пример, треугольник распадается при 20 рядах

2023-11-28 21:26 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +import java.util.ListIterator;
действительно, обнаружил ошибку - факториал (начиная с 13!) принимает такие большие значения, что выходит за пределы 4-х байт, исправлено заменой 
```
private static int getFactorial(int currentNumber)
-> 
private static long getFactorial(int currentNumber) {
```
![image](https://github.com/KFalcon2022/intensive-tasks/assets/9698419/afc0f08c-8109-46af-be47-a9d9c38baac6)

2023-11-29 17:12 UTC, EvgeneZhurov commented
Принято.

2023-11-29 17:12 UTC, closed without merging