Chapter 2 Task 10
KFalcon2022/intensive-tasks pull request #438
Opened 2023-11-28 19:58 UTC by ArtemiyDS

Chapter 2 Task 10

2023-11-28 20:36 UTC, EvgeneZhurov requested changes

2023-11-28 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String resultString = inputString.toLowerCase().replaceAll(" ", "").replaceAll("\\pP", "");
Не используйте новую строку, попробуйте решить пользуясь inputString

2023-11-29 15:09 UTC, ArtemiyDS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String resultString = inputString.toLowerCase().replaceAll(" ", "").replaceAll("\\pP", "");
Если не использовать новую строку, то по коду необходимо исправить в цикле в if
if(resultString.charAt(i) != inputString.toLowerCase().replaceAll(" ", "").replaceAll("\\pP", "").charAt(length - i - 1))
Если это так, то не совсем понятно, почему это будет лучше, чем введение переменнной? Да, память для хранения освободится, однако на каждом шаге мы будем вызывать 4 метода по форматированию строки, чтоо увеличит скорость работы программы, что не есть хорошо

Или хотите видеть принципиально другое решение при работе только с inputString?

2023-11-29 18:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String resultString = inputString.toLowerCase().replaceAll(" ", "").replaceAll("\\pP", "");
Я не говорил, что это лучше или хуже, яя лишь сказал, что прошу использовать только прошедшие темы.

2023-12-11 07:44 UTC, EvgeneZhurov commented
ветка висит больше недели без изменений. Если требуется проверка, просьба открыть новый PR.

2023-12-11 07:44 UTC, closed without merging