Chapter2 Task7
KFalcon2022/intensive-tasks pull request #440
Opened 2023-11-28 20:19 UTC by PavloKutsyn

2023-11-29 12:36 UTC, PavloKutsyn commented
Второй пуш, добавил вывод второго (меньшего) числа из пары.

2023-11-29 20:50 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (sumOfDivisorsI < m && sumOfDivisorsI != i) {
вот вариация использывания логических операторов.

https://github.com/KFalcon2022/intensive-tasks/pull/440/commits/302fe8d384afee8a5b9003faa89a31c208029be3

2023-11-29 20:54 UTC, EvgeneZhurov requested changes

2023-11-29 20:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static String getFriendlyPair(int m) {
По условию задачи метод должен вернуть int - число

2023-11-29 20:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (pairSum > maxPairSum) {
Это условие можно вставить в более сложное логическое условие верхнего if

2023-11-29 20:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int friendOfMaxNumber = 0;
избегайте предлогов в названиях переменных, методов и классов.

2023-11-29 21:07 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static String getFriendlyPair(int m) {
в этом комите так и было
https://github.com/KFalcon2022/intensive-tasks/pull/440/commits/74dc887b48f19386a1849c7a98b8fa2b57a75d27

просто пробовал выводить 2 значения
всю дружественную пару, а не максимальное число.
И ide предложило как вариант использовать строку.

2023-11-29 21:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static String getFriendlyPair(int m) {
ide не читала условие задачи просто. Прошу сделать в соответствии с условием задачи

2023-11-30 11:04 UTC, PavloKutsyn commented
надеюсь финальное исправление
https://github.com/KFalcon2022/intensive-tasks/pull/440/commits/5d39f89dcf102f1b66efb3a3c6961071ae0516c6

Убрал предлоги из названий,
Вернул численное значение int для getFriendlyPair.
по условию задачи я должен возвращеть максимальное число из пары, maxNumber.

но для проверки я вывожу пару максимального числа в консоль.

2023-11-30 11:09 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static String getFriendlyPair(int m) {
вернул численное значение

2023-11-30 11:09 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (pairSum > maxPairSum) {
вставил

2023-11-30 11:10 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int friendOfMaxNumber = 0;
исправил

2023-12-02 08:45 UTC, closed without merging

2023-12-02 08:45 UTC, EvgeneZhurov commented
Засчитано