Chapter 2 Task 6
KFalcon2022/intensive-tasks pull request #446
Opened 2023-11-28 23:13 UTC by AkBoAl

Нашел формулы в гугле да вписал их. Правда над рекурсией поломать пришлось немного голову, не сразу вышло.

Если надо, то можно переписать через циклы просто перебором.

2023-11-30 16:39 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        System.out.println(getNoc(10, 25));
Добавить в вывод сообщение, что-бы понимать что за числа появляются в консоли)

2023-11-30 16:40 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        }
всегда отделяем return пустой строкой, за исключением когда return единственная строка в логическом блоке кода.

2023-11-30 16:40 UTC, knownAsPuffy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return m > n ? getNodByEuclideanAlgorithm(m % n, n) : getNodByEuclideanAlgorithm(m, n % m);
переусложнил, можно написать проще.

2023-11-30 16:42 UTC, knownAsPuffy requested changes
поправить комменты

2023-12-06 13:40 UTC, AkBoAl commented
Не знаю как именно просматриваете код, поэтому старый вызов закомментировал. Скорее всего не нужно было, но я решил оставить. Это к тому, что я не забыл удалить - оставил специально.

2023-12-07 16:17 UTC, knownAsPuffy approved these changes

2023-12-07 16:17 UTC, closed without merging