Chapter2 Task9
KFalcon2022/intensive-tasks pull request #455
Opened 2023-11-29 09:27 UTC by PavloKutsyn

calculateMaxRowWidth - этот метод рассчитывает максимальную ширину строки в треугольнике Паскаля. Он делает это, идя через все числа на последнем уровне (последняя строка) и добавляя к ширине количество знаков каждого числа плюс пробел.

calculateRowWidth - этот метод рассчитывает ширину текущей строки. Он работает аналогично calculateMaxRowWidth, но для определенного уровня row.

В getPascalTriangle - для каждого уровня (i) сначала рассчитывается количество начальных пробелов для центровки строки в треугольнике. Затем генерируются числа треугольника Паскаля затем по формуле (number * (i - j) / (j + 1)) ид'т расчет, и после каждого числа добавляется пробел, кроме последнего числа в строке.

Используя этот код, каждый уровень треугольника центрируется относительно максимальной ширины строки, что обеспечивает симметричный вид треугольника, как на вашем изображении.

2023-11-29 23:36 UTC, PavloKutsyn commented
https://github.com/KFalcon2022/intensive-tasks/pull/455/commits/7a4ac7c0c01f95a3b86a60e15f49a61952f68a27

решение приснилось, без всяких десятичных логарифмов.

![Screenshot from 2023-11-30 00-33-28](https://github.com/KFalcon2022/intensive-tasks/assets/60603000/3c22b15c-adf3-4a95-bb5f-d328c862fab3)

пирамида получилась

2023-11-30 06:20 UTC, ekolokolov requested changes
Отлично решение. 
Молодец!

Только за красотой решения нельзя забывать об оформлении. 
Причесать.

2023-11-30 06:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            width += (int) (Math.log10(number) + 2); // Добавление длины числа и пробела после него
Вот это не "без всяких десятичных логарифмов" =)

2023-11-30 06:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    // Метод для центрирования строки внутри строки определенной длины
Если хочется оставлять комментарии к методам - то посмотри в сторону JavaDoc.

2023-11-30 06:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        int paddingSize = (maxRowLength - row.length()) / 2; // Вычисление количества пробелов для вставки слева
А вот комментарии внутри кода - признак плохого кода. 
Если тебе приходится вставлять комменты, чтобы можно было понять что твой код делает - то это плохой код (хотя твой вроде бы хороший)

2023-11-30 06:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    static String getPascalTriangle(int n) {
Если метод главный - подними его в верх

2023-11-30 06:20 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            int number = 1; // Первое число в каждом уровне всегда 1
что означает `number` в данном контексте?

2023-11-30 10:07 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            int number = 1; // Первое число в каждом уровне всегда 1
Формулу number = number * ((i - j) / (j + 1)) мне помогли вывести на работе.

Есть формула биномиального коэффициента C(n,k)=n!​/(k!(n−k)!)
где n – номмер строки, а k – позиция числа в строке, начиная с 0.

Я искал в интернете + мне подсказали на работе, что считать факториалы для каждого числа по формуле в лоб будет очень долго, особенно если буду увеличивать количество строк.

Поэтому мне предложили уйти от фактариалов и использовать свойства треугольника Паскаля и вывели следующую формулу.

C(n, k) = C(n,k – 1) * ((n – k + 1)/k)

в коде это выглядит так

i= n
j= k – 1
number = С (i, j)
C (i, j + 1) = C(i, j) * ((i – j)/(j +1))

чтобы в строке найти следующие число нужно -> number * ((i - j) / (j + 1))
получаем C (i, j + 1) или новый number.
  
По сути number это ячейка в строке, может лучше назвать pascalNumber?

2023-12-01 10:52 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            int number = 1; // Первое число в каждом уровне всегда 1
Я вообще не силен, но переменная, в которой содержится число и которая называется "число", как будто бы не информативна =)

2023-12-01 10:53 UTC, ekolokolov approved these changes
Зачтено.

2023-12-01 10:53 UTC, closed without merging