Сhapter2.Task10.
KFalcon2022/intensive-tasks pull request #458
Opened 2023-11-29 11:31 UTC by dimapros

Сhapter2.Task10.

2023-11-30 20:09 UTC, KFalcon2022 requested changes

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +    static boolean isPalindrome(String receivedSuggestion){
Данное решение считает односимвольную строку палиндромом, что некорректно

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +    static boolean isPalindrome(String receivedSuggestion){
К слову, не стоит менять названия параметров. В данном случае, большей информативности это не дало

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        suggestion = getFormatString(suggestion);
зачем иницилизировать строку параметром, если следующей же строкой ты даешь ей другое значение?

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        suggestion = (suggestion.toLowerCase()).replaceAll("\\p{IsPunctuation}", "");
лишние скобки. При цепочке вызовов рекомендую пользоваться правилом строчка-точка, это упрощает читабельность, особенно, если цепочка длинная:
```java
suggestion.toLowerCase()
     .replaceAll("\\p{IsPunctuation}", "");
```

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        suggestion = suggestion.replaceAll(" ", "");
а если был применен `\t`? логичнее ожидать `"\\s"`, а не `" "`

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for(int i = 0; i < suggestion.length(); i++){
Если все равно начал использовать методы строковых типов - StringBuilder содержит метод reverse()

2023-11-30 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return suggestion;
Рекомендую исправить замечания и прислать на проверку. И, имхо: не стоит использовать функциональность, не разобравшись в ней. Могу ошибаться. но выглядит, будто ты просто нагуглил регулярку для пунктуации. Непонятно, почему она не была расширена пробельными символами. Как и то, почему пробельные символы включили в себя только пробелы

После внесения правок напиши в ЛС с ссылкой на ПР. https://t.me/ironicMotherfucker

2023-12-01 18:37 UTC, KFalcon2022 requested changes

2023-12-27 18:32 UTC, EvgeneZhurov commented
RP висит более недели без изменений. Если требуется дальнейшая проверка откройте новый RP.

2023-12-27 18:32 UTC, closed without merging