Chapter 2 Task 7
KFalcon2022/intensive-tasks pull request #459
Opened 2023-11-29 11:34 UTC by AkBoAl

Вроде верно находит. Возможно стоит попробовать сумму находить через рекурсию отдельным методом. Может быть займусь.

2023-11-30 18:54 UTC, KFalcon2022 requested changes

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                 */
Избыточные комментарии. Не стоит ими злоупотреблять. Как правило, допустимо оставить комментарий в виде Java-doc над методом:
```java
/**
* Твой комментарий
*/
```

А также уточнять не очевидные места в логике однострочными комментариями (через `//`). Как правило, в данном случае речь идет о высоких уровнях абстракции, соотнесении действий с предметной областью или иными пояснениями, без которых смысл кода не ясен. 

В данном случае я бы рекомендовал вообще отказаться от комментариев

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int maxNumber = 0, maxSum = 0, sum1 = 1, sum2 = 1;
не объявляй несколько переменных в одной строке. Это усложняет чтение кода

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                    sum1 += j;
Т.е. один и тот же делитель может быть добавлен дважды? При i == j

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            for (int j = 2; j <= Math.sqrt(i); j++) {   //находим сумму множителей первого числа и записываем в sum1
Предлагаю попытаться оптимизировать читабельность кода, выделив вложенный цикл в отдельный метод. В текущем виде код переусложнен

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                        sum2 += j;
Как видишь, тебе приходится дублировать один и тот же код дважды. Вынося в отдельный метод, ты избавляешь себя от дублирования, которое еще и придется актуализировать сразу в двух местах при наличии ошибки в этом блоке кода

2023-11-30 18:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
>  }
После внесения правок напиши в ЛС с ссылкой на ПР. https://t.me/ironicMotherfucker

2023-11-30 19:27 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                    sum1 += j;
Похоже понял. Когда у числа есть квадратный корень, который равен целому числу, я в сумму 2 раза его добавляю, хотя надо 1 раз.

2023-12-01 19:17 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                    sum1 += j;
именно

2023-12-01 19:20 UTC, KFalcon2022 requested changes

2023-12-01 19:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int sum2 = 0;
непонятно, почему sum1 и sum2 объявлены вне цикла. sum1 точно живет в рамках одной итерации. sum2 - вроде бы нет, но подзреваю, что это некорректно

2023-12-01 19:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (j != n / j) {
n / j логично вынести в переменную, чтобы не считать дважды

2023-12-01 19:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    static String getPascalTriangle(int n) {
не проверяется в рамках этого ПР

2023-12-06 13:57 UTC, AkBoAl commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    static String getPascalTriangle(int n) {
Да, не знаю как файл попал в данный коммит, а удалить не сумел.

2023-12-28 19:15 UTC, KFalcon2022 approved these changes

2023-12-28 19:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (sum1 != i && sum2 == i && maxSum < sum1 + i && sum1 < m && sum2 < m) {
переусложненное условие. В целом, тяжелые условия с несколькими &&/|| стоит выносить в отдельные булеан-методы. Это делает код читабельнее и позволяет дать доп. информацию о сути проверок посредством названия такого булеан-метода

2023-12-28 19:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
>  }
Оставшиеся замечания считаю мелкими, задача зачтена

2023-12-28 19:15 UTC, closed without merging