Chapter 2 Task 9
KFalcon2022/intensive-tasks pull request #464
Opened 2023-11-29 13:39 UTC by SenyaDiamond

2023-11-29 21:10 UTC, EvgeneZhurov requested changes

2023-11-29 21:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            baseOfTriangle += (getFactorial(n)) / (getFactorial(j) * getFactorial(n - j)) + " ";
идея жалуется на +=

2023-11-29 21:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    }
Приятно, отличный результат

2023-11-29 21:11 UTC, closed without merging

2023-11-30 05:33 UTC, SenyaDiamond commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            baseOfTriangle += (getFactorial(n)) / (getFactorial(j) * getFactorial(n - j)) + " ";
Она предлагала делать через метод append StringBilder'a, но КМК это сложнее читается чем +=, в следующий раз учту.