Chapter 2 Task 6
KFalcon2022/intensive-tasks pull request #466
Opened 2023-11-29 14:24 UTC by smmotor

2023-12-01 11:32 UTC, ekolokolov requested changes

2023-12-01 11:32 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int nod = 1;
Переменную объявить нужно после if

2023-12-01 11:32 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int maxNum = Math.max(Math.abs(m), Math.abs(n));
ты несколько раз делаешь Math.abs(m) - вынеси в переменную. (хотя зачем тебе вообще тут значение по модулю, я хз. Вроде не нужно.)

2023-12-05 11:47 UTC, smmotor commented
Здравствуйте, вроде бы нажал "re request"

2023-12-06 06:45 UTC, ekolokolov approved these changes
Зачтено

2023-12-06 06:45 UTC, closed without merging