chapter2.task10
KFalcon2022/intensive-tasks pull request #479
Opened 2023-11-29 18:58 UTC by AleksandrAkimovChg

<a href="https://geometry-math.ru/homework/Java-palindrome.html">ссылка</a>

2023-11-29 19:02 UTC, EvgeneZhurov requested changes

2023-11-29 19:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String str = inputString.toLowerCase().replaceAll("[^а-я0-9]", "");
сделайте без использования String и не используйте темы, которые не были затронуты в курсе.

2023-11-30 18:31 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String str = inputString.toLowerCase().replaceAll("[^а-я0-9]", "");
Благодарю Евгений. Пока работаю над таской

2023-11-30 21:33 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String str = inputString.toLowerCase().replaceAll("[^а-я0-9]", "");
Done. Please review.

2023-12-02 09:40 UTC, EvgeneZhurov requested changes

2023-12-02 09:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (isRussianLetter(firstChar)) {
Russian? программа не должна зависеть от языка. Сейчас она работает и с английскими символами.

2023-12-02 09:41 UTC, closed without merging

2023-12-02 10:20 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (isRussianLetter(firstChar)) {
Да, согласен, сейчас перечитал таску свежим взглядом. Вспомогательные методы можно докурутить.