Chapter 2 Task 10
KFalcon2022/intensive-tasks pull request #492
Opened 2023-11-30 08:37 UTC by KrisLu23

2023-12-02 14:15 UTC, EvgeneZhurov requested changes

2023-12-02 14:15 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        inputString = inputString.replaceAll("[ ,.!?]", "").toLowerCase(Locale.ROOT);
не используйте regex и другие темы, которые не были затронуты в курсе.

2023-12-02 14:15 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        char[] arr = new char[inputString.length()];
не используйте массивы, только примитивы.

2023-12-03 10:10 UTC, KrisLu23 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        inputString = inputString.replaceAll("[ ,.!?]", "").toLowerCase(Locale.ROOT);
Проблемы с кодировкой не решила. Выкручивалась как могла.

Буду думать, как еще сделать.

2023-12-03 19:27 UTC, EvgeneZhurov requested changes

2023-12-04 20:00 UTC, EvgeneZhurov requested changes

2023-12-04 20:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>          System.out.println(isPalindrome("Никогда не говори никогда."));
"Никогда не говори никогда." выдает true, ожидалось false

2023-12-05 08:13 UTC, KrisLu23 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>          System.out.println(isPalindrome("Никогда не говори никогда."));
У меня выдает false на "Никогда не говори никогда."

2023-12-05 08:29 UTC, closed without merging