commit1
KFalcon2022/intensive-tasks pull request #5
Opened 2023-11-18 22:14 UTC by N1ruin

2023-11-19 08:50 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return "Вам " + age + " лет.";
Какой результат будет для 32?

2023-11-19 09:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Так же не советую использовать else if, если все блоки завершаются return. Это затрудняет чтение кода, но не имеет практического смысла

2023-11-19 09:19 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
>  }
Также не вижу валидации отрицательных значений. Возраст не может быть ниже 0 лет

2023-11-19 12:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Не вижу исправления

2023-11-19 12:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        result = "Неверный возраст.";
почему 0 быть не может? 
И нет вырпвнивания кода. ctrl+alt+L

2023-11-19 12:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        result = "Неверный возраст.";
Подольешь изменения - пни в лс. https://t.me/ironicMotherfucker

2023-11-19 12:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Вводить переменную вместо нескольких return - не лучшая идея. Тем самым ты заставляешь скакать по коду, смотря, где используется переменная

2023-11-19 12:36 UTC, N1ruin commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Теряюсь в догадках как лучше сделать) А если в методе main вызвать метод getAgeString (предварительно сделав его void) и вместо return в методе просто выводить на экран результат?

2023-11-19 15:50 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
Это нарушение условий задачи

```
 if (age < 0) {
            return "Неверный возраст.";
 } 
if (age % 10 == 1 && age != 11) {
            return"Вам " + age + " год.";
}
...
```

И последний кейс тогда без else

2023-11-20 17:37 UTC, KFalcon2022 requested changes

2023-11-20 19:50 UTC, EvgeneZhurov requested changes

2023-11-20 19:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
При введении числа 111 выведет неверный результат.

2023-11-22 15:14 UTC, EvgeneZhurov requested changes

2023-11-22 15:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age % 10 == 1 && age != 11 && age != 111) {
age != 11 && age != 111   используйте остаток от деления на 100, код станет короче

2023-11-22 15:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age % 10 >= 2 && age % 10 <= 4 && age != 12 && age != 13 && age != 14 && age != 112 && age != 113 && age != 114) {
age != 12 && age != 13 && age != 14 && age != 112 && age != 113 && age != 114    используйте сравнение, как Вы делали в других условиях и используйте остатки от деления на 100. Код сильно сократится

2023-11-22 15:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (age % 10 == 1 && age != 11 && age != 111) {
пробел перед if

2023-11-22 20:06 UTC, KFalcon2022 requested changes

2023-11-22 20:06 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            entrance -= 1;                                             // Буду рад если выложите разбор этой задачи в будущем
Не проверялось. Одна задача - один ПР

2023-11-22 20:06 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "Вам " + age + " лет.";
Задача выполнена формально верно. Но требуется упростить условия - в таком виде код крайне загроможден

2023-12-04 20:40 UTC, KFalcon2022 commented
PR закрыт, т.к. не обновлялся больше недели. При возобновлении работы стоит создать новый

2023-12-04 20:40 UTC, closed without merging