Chapter 2 Task6
KFalcon2022/intensive-tasks pull request #506
Opened 2023-11-30 18:15 UTC by KungFU13

2023-12-05 16:59 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +    public static int getMinNumber(int number1, int number2) {
исправил

2023-12-05 16:59 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +        if (isSimple(maxNumber) && isSimple(minNumber)) {
убрал

2023-12-05 20:48 UTC, EvgeneZhurov requested changes

2023-12-06 18:12 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +    public static boolean isNotCorrectInput(int number1, int number2) {
я думал, если я в условиях делаю от false, то должен спросить "некорректные значение?" и если идет тру, то программа завершается

2023-12-06 18:12 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +        if (minNumber == maxNumber || maxNumber % minNumber == 0) {
тупанул

2023-12-06 18:13 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +    public static String getNOKAndNOD(int number1, int number2) {
исправил

2023-12-06 18:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Main.java
> +        if (minNumber == maxNumber || maxNumber % minNumber == 0) {
да ничего, Вы учитесь

2023-12-06 19:37 UTC, closed without merging