Chapter2 task10
KFalcon2022/intensive-tasks pull request #510
Opened 2023-11-30 20:01 UTC by NJmist

2023-12-03 20:36 UTC, EvgeneZhurov requested changes

2023-12-03 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                letterString = letterString + inputString.charAt(i);
Строка в Java - это неизменяемый объект, лучше использовать stringbuilder. Просьба написать программу без использования без создания строк, используя только примитивы.

2023-12-04 19:56 UTC, NJmist commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                letterString = letterString + inputString.charAt(i);
Сделал без строк.

2023-12-04 20:06 UTC, EvgeneZhurov commented
Засчитано

2023-12-04 20:06 UTC, closed without merging