Chapter1 Task2
KFalcon2022/intensive-tasks pull request #511
Opened 2023-11-30 21:13 UTC by fb1rd

2023-12-03 20:44 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static final double FLATS_ON_FLOOR = 4.0;
Чем эта переменная заслужила быть полем класса? Почему она double? Квартир на этаже целое число.

2023-12-03 22:36 UTC, fb1rd commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static final double FLATS_ON_FLOOR = 4.0;
чтобы можно было ее использовать ее в разных методах класса.
например, вы сами предложили использовать ее в другом методе в последнем комменте этого пр

2023-12-04 07:38 UTC, EvgeneZhurov requested changes

2023-12-04 07:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +    static final int FLATS_ON_FLOOR = 4;
лучше стараться избегать предлогов в названиях переменных и методов, если без них можно обойтись.

2023-12-04 07:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        double mainFraction = (double) flatNumber / FLATS_ON_FLOOR;
лучше стараться делать названия имен максимально информативно и без лишней воды. Слова фракция и координата не очень подходят по смыслу. Слова main и full не нужны.

2023-12-04 07:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +                & floorAmount > 0
Лучше использовать && вместо &, почитайте почему.

2023-12-04 07:39 UTC, EvgeneZhurov commented
засчитано.

2023-12-04 07:39 UTC, closed without merging