Chapter2 Task10
KFalcon2022/intensive-tasks pull request #513
Opened 2023-12-01 10:42 UTC by PavloKutsyn

2023-12-03 20:51 UTC, EvgeneZhurov requested changes

2023-12-03 20:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String cleanedString = inputString.replaceAll("[^a-zA-Zа-яА-Я0-9]", "").toLowerCase();
попробуйте решить задачу без использования новых строк, только примитивы

2023-12-04 10:52 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String cleanedString = inputString.replaceAll("[^a-zA-Zа-яА-Я0-9]", "").toLowerCase();
Попробовал уйти от рекомендации не объявлять новых строк.
Ппросто когдато решал задачку про оборотней :)
но там не предложения были, а слова.

public class DetectWerewolf {
  public static boolean isWerewolf(String target) {
    StringBuilder builder = new StringBuilder(target);
    builder.reverse();
    String reversedTarget = builder.toString();

    return target.equals(reversedTarget);
    
  }
}

И решая вашу задачу, отталкивался от знакомой мне логики.
Я случайно запушил каакойто из старых вариантов 10 задачи (с логическими операторами) в 7 задачу этой ветки Chapter2_Task10, она не проходила тесты то, от невнимательности,

решение 10 задачи есть.
https://github.com/KFalcon2022/intensive-tasks/pull/513/commits/ed23b24ed46952f6c0e50b61f0bc0f63cf9ae2c6

2023-12-04 19:00 UTC, EvgeneZhurov requested changes
здесь 6 разных задач. Пришлите одну нужную

2023-12-04 19:43 UTC, PavloKutsyn commented
public class Task10 {
    public static void main(String[] args) {
        String testString = "Муза! Ранясь шилом опыта, ты помолишься на разум.";
        System.out.println("Is palindrome: " + isPalindrome(testString));
    }

    public static boolean isPalindrome(String inputString) {
        String cleanedInput = inputString.toLowerCase().replaceAll("[^a-zA-Z0-9а-яА-Я]", "");
        if (cleanedInput.length() <= 1) {
            return false;
        }
        int left = 0, right = cleanedInput.length() - 1;
        while (left < right) {
            if (cleanedInput.charAt(left) != cleanedInput.charAt(right)) {
                return false;
            }
            left++;
            right--;
        }
        return true;
    }
}

2023-12-04 19:48 UTC, EvgeneZhurov commented
Пожалуйста без regex и создания новых строк. Только примитивы.

2023-12-05 12:17 UTC, PavloKutsyn commented
Доброго времени суток.
Думаю получилось

[57ee4d9](https://github.com/KFalcon2022/intensive-tasks/pull/513/commits/57ee4d9f35e7095174eb924a8b9a49c6affbfe5f)

2023-12-05 14:17 UTC, EvgeneZhurov commented
нужно научиться корректно работать с GitHub. Задача засчитана.

2023-12-05 14:17 UTC, closed without merging