capter2_task7
KFalcon2022/intensive-tasks pull request #514
Opened 2023-12-01 11:23 UTC by ETSphere

добавил метод расчета суммы делителей числа и мессадж для удобства. Надеюсь моя самодеятельность не помешает проверке.

2023-12-03 20:56 UTC, EvgeneZhurov requested changes

2023-12-04 19:19 UTC, EvgeneZhurov requested changes

2023-12-04 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int quantityOfDivisors = sumOfDivisor(i);
Читайте правила оформления кода: https://github.com/KFalcon2022/intensive-tasks/tree/master#правила-оформления-кода
старайтесь избегать предлогов в названиях методов и переменных. Разверните слова местами и предлог можно выкинуть divisorSum исправьте везде

2023-12-04 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static void msg(int start, int end) {
старайтесь давать максимально релевантные имена print...

2023-12-04 19:20 UTC, closed without merging

2023-12-06 08:22 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static void msg(int start, int end) {
Принял