Chapter2 Task7
KFalcon2022/intensive-tasks pull request #532
Opened 2023-12-02 10:22 UTC by KungFU13

2023-12-03 21:54 UTC, EvgeneZhurov requested changes

2023-12-03 21:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        int numberN = 999999;
N = 497 
результат: 220
ожидалось: 284

2023-12-05 17:04 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +        int numberN = 999999;
исправил, думал надо вывести число у которого сумма чисел больше

2023-12-05 20:27 UTC, EvgeneZhurov requested changes

2023-12-05 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Main.java
> +            return 0;
Лучше не делать отдельный метод на каждую отдельную строку кода. Бывают короткие емкие методы, но этот метод можно смело объединять с другими.

2023-12-05 20:28 UTC, EvgeneZhurov commented
Засчитано.

2023-12-05 20:28 UTC, closed without merging