chapter1task5
KFalcon2022/intensive-tasks pull request #538
Opened 2023-12-02 20:19 UTC by DeaDMop03

2023-12-04 07:30 UTC, ekolokolov requested changes
поправить проверку

2023-12-04 07:30 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static boolean checkTriangleExistance (double a, double b, double c) {
Тут явно какая то проблема. 
Для треугольника 12, 13, 5 - проверка не проходит.

2023-12-07 11:26 UTC, ekolokolov requested changes
Не корректное поведение на данных:
12, 13, 5

Expected :2.0
Actual   :0.5

2023-12-07 11:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double[] getAngles(double a, double b, double c) {
Не корректно считает.

2023-12-07 11:26 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double getInscribedCircleRadius(double a, double b, double c) {
Не корректно считает

2023-12-11 06:30 UTC, ekolokolov requested changes

2023-12-11 06:30 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double[] getAngles(double a, double b, double c) {
углы все еще не корректно считает

Для треугольника 12, 13, 5  примерно 22.619864, 67.3801350 и 90

2023-12-27 18:35 UTC, EvgeneZhurov commented
Висит более недели. Если требуется проверка - просьба открыть новый PR.

2023-12-27 18:35 UTC, closed without merging