Task1
KFalcon2022/intensive-tasks pull request #54
Opened 2023-11-19 17:33 UTC by sto-so

2023-11-19 19:55 UTC, sto-so commented
Пока размышлял над второй задачей, понял что не корректно выведет "год" при значение от 111 до 114. Как поступить? Создать новый Pull requests? А что со старым?

2023-11-20 09:41 UTC, EvgeneZhurov requested changes

2023-11-20 14:04 UTC, sto-so commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            } else if (age % 10 > 1 && age % 10 < 5) {
Исправил эту ошибку и убрал пробел.

2023-11-20 18:59 UTC, EvgeneZhurov requested changes

2023-11-20 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
>                  return "Вам " + age + " года.";
сразу после return не должно должно быть else, метод либо вернет результат через return либо и без else пойдет исполняться дальше

2023-11-22 12:09 UTC, EvgeneZhurov requested changes

2023-11-22 14:55 UTC, closed without merging