Chapter 2 Task 7
KFalcon2022/intensive-tasks pull request #542
Opened 2023-12-03 06:43 UTC by DearCuba

2023-12-04 13:05 UTC, EvgeneZhurov requested changes

2023-12-05 06:00 UTC, DearCuba commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (m != getSumOfDivisors(getSumOfDivisors(m)) || getSumOfDivisors(m) >= m) {
Спасибо вам, впредь постараюсь серьезнее относиться к циклу while.

2023-12-05 14:52 UTC, EvgeneZhurov requested changes

2023-12-13 14:46 UTC, EvgeneZhurov approved these changes

2023-12-13 14:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    while (m > 0 && !(m == getSumOfDivisors(getSumOfDivisors(m))) | getSumOfDivisors(m) >= m) {
лучше использовать || . Советую узнать почему

2023-12-13 14:47 UTC, closed without merging