Chapter 2  Task8
KFalcon2022/intensive-tasks pull request #543
Opened 2023-12-03 09:43 UTC by KungFU13

2023-12-04 13:09 UTC, EvgeneZhurov requested changes

2023-12-05 20:14 UTC, EvgeneZhurov requested changes

2023-12-05 20:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        return  (double) getCountHappyTicket(tickets) / 1_000_000;
Все, что делает это метод, это делит на миллион результат следующего метода. Почем бы не объединить его с методом getCountHappyTicket

2023-12-05 20:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        if (number < 1_000_000){
эти 3 if бесполезны. введите 2 переменных, посчитайте в 1 переменной сумму первых трех цифр, во второй сумму вторых 3 цифр и верните результат сравнения

2023-12-06 18:32 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        if (number < 1_000_000){
исправил

2023-12-06 18:32 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        return  (double) getCountHappyTicket(tickets) / 1_000_000;
исправил

2023-12-06 18:55 UTC, EvgeneZhurov requested changes

2023-12-06 18:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 1000; i < 1_000_000; i++){
неверный ответ. Если итератор начент с 0 ответ будет верным

2023-12-06 18:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
обычно не пропускают сроку сразу после } и перед {

2023-12-06 18:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +
пустая строка не нужна

2023-12-07 03:43 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task8/Main.java
> +        for (int i = 1000; i < 1_000_000; i++){
потому что в нашей вселенной учитывается 000_000 билет?

2023-12-08 17:36 UTC, closed without merging