chapter2_task8
KFalcon2022/intensive-tasks pull request #563
Opened 2023-12-04 11:17 UTC by ETSphere

Как то оно все сложно математически, механизм подсчета суммы цифр стащил в интернете, адаптировал под себя.

2023-12-05 18:40 UTC, KFalcon2022 requested changes

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +    static final int halfDigits = totalDigits / 2;
Константы уровня класса принято писать в UPPER_CASE

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +
одна пустая строка - хорошо, две - избыточно

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int halfValueTiketNumber = (int) Math.pow(10, halfDigits);
опечатка в названии переменной

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +    private static int sumOfDigitCalc(int tiketIteration) {
названия методов должны начинаться с глагола. Скажем, calсDigitsSum. Сокращениями тоже не стоит сильно увлекаться

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            int sumFirstHalf = sumOfDigitCalc(i);
не очевидное поведение. Ты передаешь в метод все число, а считает оно сумму только последних трех цифр

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < halfDigits; i++) {
учитывая название метода, логичнее бы вписался while и расчет суммы всех цифр, без искусственного ограничения

2023-12-05 18:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +
В целом хорошее решение, но довольно много мелких замечаний. При внесении исправлений напиши в ЛС со ссылкой на ПР. https://t.me/ironicMotherfucker

2023-12-06 07:20 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +    static final int halfDigits = totalDigits / 2;
Действительно, забыл про это правило когда переносил переменные из метода в тело класса для дальнейшего удобства смены значений если в них возникнет необходимость.

2023-12-06 07:20 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +
увлекся, исправил.

2023-12-06 07:20 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int halfValueTiketNumber = (int) Math.pow(10, halfDigits);
к сожалению такое случается со мной часто.

2023-12-06 07:22 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +    private static int sumOfDigitCalc(int tiketIteration) {
можно пример хорошего названия, чтоб понять примерный эталон ( еще не дошел до чтения книги "Чистого кода" оттого собираю мудрость от менторов.

2023-12-06 07:24 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            int sumFirstHalf = sumOfDigitCalc(i);
Долго пытался понять замечание пока не переделал метод калькулятора на цикл.. понял что правильнее получать остаток, а не значение цикла.

2023-12-06 07:25 UTC, ETSphere commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < halfDigits; i++) {
Переделал в while убрав ограничение, но оставил в коде цикл for закоментированным (исключительно для себя)

2023-12-07 19:19 UTC, KFalcon2022 approved these changes

2023-12-07 19:19 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +//            ticketIteration /= 10;
не стоит оставлять закомменченный код. Чаще всего он больше никогда не пригодится

2023-12-07 19:19 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +}
Задача засчитана

2023-12-07 19:19 UTC, closed without merging