chapter1.task4
KFalcon2022/intensive-tasks pull request #59
Opened 2023-11-19 19:02 UTC by AleksandrAkimovChg

КУРСОВАЯ ЗАДАЧА - КВАДРАТНОЕ УРАВНЕНИЕ
<a href="https://geometry-math.ru/homework/Java-parameter.html">ссылка</a>

2023-11-20 20:46 UTC, EvgeneZhurov requested changes

2023-11-20 20:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if(a == 0 && b == 0 && c == 5) {
Неверно, условие с !=0

2023-11-20 20:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            x2 = (-1 * b + Math.sqrt(discriminant) / 2 * a);
зачем переводить в int? решение может быть вещественным числом.

2023-11-20 20:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            result = ";" + (int)x2;
При a = 1, b = 0, c = 1 код отработает криво.

2023-11-21 19:13 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if(a == 0 && b == 0 && c == 5) {
fixed

2023-11-21 19:14 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            x2 = (-1 * b + Math.sqrt(discriminant) / 2 * a);
fixed

2023-11-21 19:14 UTC, AleksandrAkimovChg commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            result = ";" + (int)x2;
fixed

2023-11-21 20:00 UTC, closed without merging