Chapter 2 Task10
KFalcon2022/intensive-tasks pull request #591
Opened 2023-12-05 17:27 UTC by KungFU13

2023-12-09 20:44 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String text = getReplaceAllText(inputString);
исправил

2023-12-09 20:44 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +
исправил

2023-12-09 20:45 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return text.replaceAll("\\p{Punct}|\\p{Space}", "").toLowerCase();
убрал

2023-12-10 12:29 UTC, EvgeneZhurov requested changes

2023-12-10 12:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        StringBuilder originalText = new StringBuilder(inputString.toLowerCase());
просьба решить задачу без использования StringBuilder. Не заводите объектов строк, используйте только примитивы.

2023-12-10 12:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        reversText = getReplaceText(reversText).reverse();
пройдите по существующему тексту 1 циклом с двумя итераторами, один ++, другой --.

2023-12-10 15:27 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        reversText = getReplaceText(reversText).reverse();
так?

2023-12-10 15:31 UTC, EvgeneZhurov requested changes

2023-12-10 15:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        System.out.println(isPalindrome("как"));
не проходит валидацию:"!!! ." 
ожидалось false
этот пункт был ранее в комметариях

2023-12-10 15:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String originalText = "";
не используйте строки в методе. Лучше почитать чем string отличается от stringbuilder и stringbuffer, но не используйте это в решении.

2023-12-10 18:08 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String originalText = "";
а вот так?(

2023-12-10 18:25 UTC, EvgeneZhurov requested changes

2023-12-10 18:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = 0, j = inputString.length() - 1; i < inputString.length() && j >= 0; i++, j--) {
скорость возрастет вдвое, если идти до равенства итераторов

2023-12-11 21:19 UTC, EvgeneZhurov approved these changes

2023-12-11 21:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (i == j){
2 момента: 1) счетчики могут легко проскочить равенство, лучше использовать <=
2) лучше вставить это логическое условие в логическое выражение цикла for( ; логическое выражение цикла; )

2023-12-11 21:21 UTC, closed without merging