Chapter2Task10
KFalcon2022/intensive-tasks pull request #608
Opened 2023-12-06 14:38 UTC by N1ruin

2023-12-08 19:17 UTC, EvgeneZhurov requested changes

2023-12-10 13:59 UTC, EvgeneZhurov requested changes

2023-12-10 13:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
не проходит тест: "!!! ."
Ожидается false.

2023-12-10 15:08 UTC, EvgeneZhurov requested changes

2023-12-10 15:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        int validSymbols = 0;
эта переменная не нужна. Обращайте внимание на варнинги idea

2023-12-10 15:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = 0, j = inputString.length() - 1; i < inputString.length() && j >= 0; i++, j--) {
метод будет работать вдвое быстрее, если учесть условие, что i<=j.

2023-12-10 15:22 UTC, N1ruin commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        int validSymbols = 0;
Сначала пришла идея реализации с переменной, но когда начал писать код получилось без нее и забылось убрать) Варнинги это желтые треугольники которые?

2023-12-10 15:24 UTC, EvgeneZhurov approved these changes

2023-12-10 15:24 UTC, closed without merging