Chapter2Task9
KFalcon2022/intensive-tasks pull request #609
Opened 2023-12-06 14:47 UTC by N1ruin

2023-12-08 19:27 UTC, EvgeneZhurov requested changes

2023-12-08 19:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        System.out.println(getPascalTriangle(10));
при n = 20 скашивает нижние 3 ряда

2023-12-08 19:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        for (int i = 0; i < n; i++) {
блоки кода лучше отделять пустыми строками

2023-12-13 17:22 UTC, N1ruin commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        System.out.println(getPascalTriangle(10));
Всю голову сломал, не могу понять в чем проблема( По логике должно считать разницу между текущей строкой и последней и добавлять столько пробелов в текущую строку.

2023-12-14 06:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        System.out.println(getPascalTriangle(10));
не торопитесь. Чаек и время расставят все по своим местам. Сначала в голове, потом в коде.

2023-12-21 13:17 UTC, EvgeneZhurov commented
Pr висит без изменения более недели, если требуется проверка откройте новый PR

2023-12-21 13:17 UTC, closed without merging