Chapter 1 Task 4
KFalcon2022/intensive-tasks pull request #619
Opened 2023-12-07 13:59 UTC by smmotor

Исправил замечания по предыдущему PR

2023-12-08 21:25 UTC, EvgeneZhurov requested changes
жду правок.

2023-12-08 21:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double d = Math.pow(b, 2) - 4 * a * c;
лучше объявлять переменные максимально близко к месту их использования. Логика простая: если return будет из следующего if, получается, что эти переменные будут объявлены без использования.

2023-12-08 21:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0) {
как вариант, можно объединить это логическое условие с дискриминантом меньше 0. Более логично возвращать один и тот же результат в одном ветвлении. Читаемость повысится.

2023-12-09 13:40 UTC, smmotor commented
Переменные перенес, обьединить с d < 0 не получилось

2023-12-10 12:25 UTC, EvgeneZhurov requested changes

2023-12-10 12:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double x2 = 0;
переменная x2 объявлена не максимально близко к месту использования.

2023-12-10 12:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +
Посчитайте дискриминант перед блоком выше с логическим условием "a == 0 && b == 0" и объедините через && d < 0, тогда блок в самом конце пропадет, один из if внизу можно будет убрать, читаемость и логика работы повысится.

2023-12-10 12:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (-b - Math.sqrt(d)) / 2 * a;
не имеет смысла считать корень квадратный из 0

2023-12-10 12:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return String.format("Количество решений: 2. Корни: %d;%d", (int) x1, (int) x2);
решение не обязательно целое число. Будет ошибкой, если ответ будет дробью или иррациональным числом. Не смотрите на тесты.

2023-12-12 20:52 UTC, smmotor commented
Здравствуйте, если я вас правильно понял, вы имеете ввиду, что решение может быть и вещественным числом

2023-12-13 08:05 UTC, EvgeneZhurov requested changes

2023-12-13 08:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>          if (d == 0) {
Если уже выше были условия с d < 0 и с d > 0, значит уже не останется выбора и дискриминант и так равен 0, то есть достаточно убрать if и оставить код, который сейчас внутри {}

2023-12-13 12:40 UTC, smmotor commented
Исправил

2023-12-13 14:58 UTC, EvgeneZhurov approved these changes

2023-12-13 14:58 UTC, closed without merging