Chapter2 task6
KFalcon2022/intensive-tasks pull request #621
Opened 2023-12-07 14:10 UTC by ChiffaRi

2023-12-08 21:41 UTC, EvgeneZhurov approved these changes

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n == m) {
лишний блок кода

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (Integer.max(m, n) % Integer.min(m, n) == 0) {
алгоритм не такой. не нужно считать минимальные и максимальные значения. важен только остаток от деления m на n. Если он  == 0, то return, если нет, то рекурсивно передаем в качестве аргументов n  и m%n (именно в такой очередности аргументов.)

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n == m) {
этот блок кода не нужен, ос содержится в следующем if

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (Integer.max(m, n) % Integer.min(m, n) == 0) {
блоки кода обычно отделяют пустыми строками с обеих сторон.

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n == m) {
лишний блок кода

2023-12-08 21:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            max = Integer.max(min, rec - min);
введите 2 числа: 1000000 и 3 и проверьте как работает. понадобится примерно 333 333 итерации цикла, через остаток от деления понадобится 2 итерации. Перепишите.

2023-12-08 21:43 UTC, EvgeneZhurov requested changes
просьба исправить замечания

2023-12-09 12:29 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n == m) {
Согласна.

2023-12-09 12:31 UTC, ChiffaRi commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n == m) {
Не согласна, т.к. строки 61-63 возвращают именно 1. Если его убрать, то вернет 0, а это неверно.

2023-12-26 17:16 UTC, closed without merging