Chapter2_Task11 "прямой подход"
KFalcon2022/intensive-tasks pull request #622
Opened 2023-12-07 14:29 UTC by PavloKutsyn

2023-12-07 14:36 UTC, PavloKutsyn commented
Прямой подход делал сам.
Комбинаторику не сам. Буду еще в этом разбираться.

2023-12-08 21:47 UTC, EvgeneZhurov requested changes
"Код рассчитывает это, используя свойства комбинаторики" - это все равно что сказать: написал код, он считает верно. Либо придется объяснить почему именно эти коэффициенты считают верно и дают алгоритмическую сложность O(n) или придется переписать все сначала через вложенные циклы. В таком виде без детальный пояснений задача принята не будет

2023-12-09 09:57 UTC, PavloKutsyn commented
**Алгоритмическая сложность**
**Прямой подход**
Алгоритмическая сложность этого подхода является O(n^3), поскольку мы имеем три вложенных цикла: один для итерации по элементам, второй для генерации подмассивов разной длины и третий для суммирования элементов каждого подмассива.

**Комбинаторный подход:**
Этот подход имеет алгоритмическую сложность O(n), так как он включает в себя только один цикл, который проходит по каждому элементу массива один раз. Все вычисления в цикле являются константными операциями, не зависящими от размера массива.

Обїяснение как я понял.
**Прямой подход**
Прямой подход предполагает явное создание всех подмассивов нечетной длины и вычисление их сумм. Расчет идет следующим образом:

Вычисление суммы подмассивов для каждого элемента:
Для каждого элемента array[i]:
Генерируем подмассивы, которые начинаются с array[i] и имеют нечетную длину.
Вычисляем сумму каждого подмассива.

пример:
Массив: {1, 2, 3, 4, 5}

Элемент 1:
Подмассивы: [1], [1, 2, 3], [1, 2, 3, 4, 5]
Суммы: 1, 1+2+3=6, 1+2+3+4+5=15

Элемент 2:
Подмассивы: [2], [2, 3, 4]
Суммы: 2, 2+3+4=9

Элемент 3:
Подмассивы: [3], [3, 4, 5]
Суммы: 3, 3+4+5=12

Элемент 4:
Подмассивы: [4]
Суммы: 4

Элемент 5:
Подмассивы: [5]
Суммы: 5
Общая сумма: 1+6+15+2+9+3+12+4+5=57

**Комбинаторный подход**
Распределение элементов в подмассивах:
Каждый элемент массива входит в определенное количество подмассивов. Это количество зависит от позиции элемента в массиве. Элементы, расположенные ближе к середине массива, входят в большее количество подмассивов нечетной длины, чем те, которые расположены ближе к краям.

Вычисление количества подмассивов:
Для каждого элемента вычисляется количество подмассивов, в которые он входит. Это делается путём умножения количества элементов до (включительно) и после (включительно) этого элемента. Это дает общее количество подмассивов, в которых фигурирует этот элемент.

Учет только подмассивов нечетной длины:
Из общего количества подмассивов выбираются только те, которые имеют нечетную длину. Это делается путем определения половины от общего количества (с учетом того, что количество подмассивов четной и нечетной длины примерно одинаково).

Вычисление:
Для каждого элемента array[i]:
end = i + 1 – количество элементов от текущего до конца массива.
start = n – i — количество элементов от текущего до начала массива.
totalSubarrays = start * end – общее количество подмассивов, включающих array[i].
oddSubarrays = (totalSubarrays + 1)/2 — количество подмассивов нечетной длины, включающих array[i].
Сумма array[i] в общую сумму: contribution = array[i] * oddSubarrays.

Объяснение Переменных
array[i]: Элемент массива на позиции i.
n: Общее количество элементов массива.
end: Количество частей от i до конца массива.
start: Количество частей от i до начала массива.
totalSubarrays: Общее количество подмассивов, включающих array[i].
oddSubarrays: Количество подмассивов нечетной длины, включающих array[i].

2023-12-10 12:40 UTC, EvgeneZhurov approved these changes

2023-12-10 12:40 UTC, EvgeneZhurov commented
засчитано

2023-12-10 12:40 UTC, closed without merging