Task1
KFalcon2022/intensive-tasks pull request #63
Opened 2023-11-19 20:47 UTC by cranium1983

2023-11-20 03:33 UTC, PomidorkaYulia requested changes

2023-11-20 03:33 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "Вам "+ age + " " + yearStr;
При 111,112,113,114 годах - некорректное формирование выходящей строки

2023-11-20 07:09 UTC, cranium1983 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "Вам "+ age + " " + yearStr;
Спасибо. Внес правку. Мне нужно нажать на Resolve conversation?

2023-11-20 07:14 UTC, cranium1983 commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "Вам "+ age + " " + yearStr;
> Спасибо. Внес правку. Мне нужно нажать на Resolve conversation?

Наверное, нет.  Но кликнул на re request review.

2023-11-21 11:03 UTC, PomidorkaYulia approved these changes

2023-11-21 11:03 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        return "Вам "+ age + " " + yearStr;
Работает корректно. Операции сравнения значений поддаются общим правилам о привдении к левой стороне операнда, но есть разного рода оптимизации. 

Одна из них — приведение к int в безусловном виде на популярных архитектурах типов short, char и byte. Как именно они приводятся — спецификация не общей jls, а конкретной ревизии jvm. 
Это я все пишу к тому что short - излишне - потому что все равно при сравнении к инту приведется.

2023-11-21 11:04 UTC, closed without merging

2023-11-21 11:09 UTC, cranium1983 commented
Спасибо за уточнения по приведению типов.