Ch.3 Task13
KFalcon2022/intensive-tasks pull request #636
Opened 2023-12-08 19:56 UTC by ganka-xn

2023-12-10 13:29 UTC, EvgeneZhurov requested changes

2023-12-10 13:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int[] plants = new int[] {7,7,7,7,7,7,7};
не проходит тесты.
plants = {7,7,7,7,7,7,7}
лейка = 8
Результат: 49

2023-12-11 11:17 UTC, ganka-xn commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int[] plants = new int[] {7,7,7,7,7,7,7};
возможно я что-то упустил, но получается 61 шаг
<img width="1176" alt="image" src="https://github.com/KFalcon2022/intensive-tasks/assets/82700413/92afcc68-6771-4895-8aae-c6b223783775">

2023-12-11 12:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int[] plants = new int[] {7,7,7,7,7,7,7};
описал в личку. Алгоритм реализован неверно.

2023-12-12 11:50 UTC, EvgeneZhurov requested changes

2023-12-12 11:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        for (int plant: plants) {
код нужно выравнивать, читайте требования к оформлению кода перед отправкой на проверку.

2023-12-12 11:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int neededWateringVolume = 0;
блоки кода обычно отделяют пустыми строками с обеих сторон, если они не стоят  сразу после { и перед }

2023-12-12 11:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int stepsCount = 0;
небольшой лайфхак, лучше называть возвращаемую переменную так же, как называется метод, только без глагола, это повышает читаемость кода. Если метод getCountSteps, то переменная countSteps

2023-12-12 11:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int neededWateringVolume = 0;
необходимый - прилагательное. Правила оформления кода, пункт 7: посмотрите.

2023-12-12 19:05 UTC, EvgeneZhurov approved these changes

2023-12-12 19:05 UTC, closed without merging