Task4
KFalcon2022/intensive-tasks pull request #65
Opened 2023-11-19 21:32 UTC by ganka-xn

2023-11-20 20:53 UTC, EvgeneZhurov requested changes

2023-11-20 20:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            return "Некорректные данные";
неверно, данные корректны, нужно решать линейное уравнение

2023-11-20 20:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            result = "0";
Желательно ставить {} даже если ветвление 1 строка

2023-11-20 20:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        {
{ ставится на той же строке, что и if

2023-11-20 20:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        else
} else {

2023-11-20 20:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        else
в 1 ветке 1 задача. Иначе сложно отслеживать решение задач. После решения 1 задачи хочется закрыть задачу, чтобы было удобно отслеживать.

2023-11-21 06:24 UTC, ganka-xn commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            return "Некорректные данные";
не очень понял )

2023-11-21 06:27 UTC, ganka-xn commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        {
так хуже считывается )

2023-11-21 06:31 UTC, ganka-xn commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        else
По хорошему нужна подробная инструкция по гиту с картинками, применительно к курсу. У новичков в гите (и у Вас тоже))) было бы сильно меньше головной боли ))

2023-11-21 08:15 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            return "Некорректные данные";
логика решения неверная, данные корректные. Нужно разобраться какие решения будут, если уравнение станет линейным, сколько решений и есть ли вообще.

2023-11-21 08:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        {
нет цели обмануть и повести по ложному следу :)

2023-11-21 08:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        else
это вопрос к автору канала. Есть инструкция.

2023-11-22 12:39 UTC, EvgeneZhurov commented
a = 0, b = 0, c = 0 ожидается "Решений бесконечно." Выводится некорректный ответ
a = 0, b = 0, c = 6 ожидается "Решений нет." Выводится некорректный ответ

2023-11-22 12:40 UTC, EvgeneZhurov commented
Создавайте ветку только 1 задачей, Задача засчитана.

2023-11-22 12:40 UTC, closed without merging