Chapter 4 Task 18
KFalcon2022/intensive-tasks pull request #660
Opened 2023-12-09 19:53 UTC by tasiq

2023-12-10 16:31 UTC, EvgeneZhurov requested changes

2023-12-10 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +        int length = array.length;
эта переменная не нужна.

2023-12-10 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            for (int k = length - 1 - i; k > 0; k--) {
неверное условие про k > 0 с каждым прохождения минимального элемента влево цикл должен становиться короче.

2023-12-10 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            for (int k = length - 1 - i; k > 0; k--) {
итератор 2 уровня вложенности в цикле называют j

2023-12-10 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +        for (int i = 0; i < length; i++) {
i < length вторую половину лины цикл не выполнит никогда.

2023-12-10 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            for (int j = i; j < length - 1; j++) {
length - 1   точно так? с каждым прохождением максимального элемента вправо цикл должен становиться короче.

2023-12-12 17:57 UTC, EvgeneZhurov requested changes

2023-12-12 17:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (i != 0 && countMovesLeft == 0 && countMovesRight == 0) {
countMovesLeft == 0  - это условие никогда не выполнится. Либо цикл проедет мимо на 1 итерации цикла и выйдет из него в нижнем if, либо countMovesLeft != 0. По этому идея подсвечивает, что условие бесполезно. Обращайте внимание на варнинги.

2023-12-12 17:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +
сразу после { можно не пропускать строку.

2023-12-12 17:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            for (int j = i; j < array.length - 1 - i; j++) {
когда максимальный элемент представился на самый правый индекс, перед тем как сравнивать минимальные элементы нужно отступить влево.

2023-12-13 19:17 UTC, tasiq commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (i != 0 && countMovesLeft == 0 && countMovesRight == 0) {
Ох, это было очень глупо. Да, я обращаю, но в этот раз почему-то решил, что глупая IDEA меня не поняла. И даже ковырялся дебагом, но сейчас понимаю, что проверял сценарии, в которых как раз ожидался countMovesLeft  == 0, а надо было проверить и countMovesLeft  != 0 тоже.
Очень наглядно было, больше так не ошибусь, спасибо.

2023-12-14 08:57 UTC, EvgeneZhurov requested changes

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
сразу после { и перед } обычно не ставят пустые строки, а 2 пустые стоки считается моветоном.

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            int countSwap = 0;
это на самом деле завуалированная логическая переменная, которая отвечает на вопрос, отсортирован ли массив. Лучше и делать ее логической без скрытого смысла.

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (countSwap == 0) {
это условие можно попробовать вставить в логическое условие выхода в самом for ( ; ... && countSwap == 0 ; )

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
здесь не нужна пустая строка

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
>      public static int[] doCocktailSort(int[] array) {
избегайте слова do, и так понятно, что метод нужен для действия. Когда речь заходит о каких то известных названиях, можно обойтись и без глагола.

2023-12-14 08:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
>      public static int[] doCocktailSort(int[] array) {
Сортировка вводимого массива будет произведена и без возврата самого массива, можно заменить на void.

2023-12-14 19:12 UTC, tasiq commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (countSwap == 0) {
Магия. Но понял идею, кажется.

Зато забыл, почему решил, что надо продолжать сортировку, если после самого первого прохода не было ни одной перестановки(

2023-12-16 10:03 UTC, EvgeneZhurov requested changes

2023-12-16 10:03 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            int countMoves = 0;
эта переменная лишняя, лучше ее выбросить из кода и поставить isSorted = true;  а внутри if присваивать логической переменной false. Суть проста, если код внутри if не исполняется, значит массив отсортирован. Сейчас переменная countMoves выглядит ненужным костылем

2023-12-18 20:31 UTC, EvgeneZhurov approved these changes

2023-12-18 20:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (isSorted) {
лучше отделять блоки кода пустыми строками с обеих сторон

2023-12-18 20:31 UTC, closed without merging