Completing the first task of the first chapter.
KFalcon2022/intensive-tasks pull request #686
Opened 2023-12-11 11:45 UTC by Bercut-Alex

The first task of the first chapter.

2023-12-11 12:31 UTC, EvgeneZhurov requested changes

2023-12-11 12:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age == 0 || (age >= 5 && age <= 20) || (age >= 105 && age <= 120)) {
Часть замечаний написал в личку. Смотрите: Если есть if( логическое условие){
большой блок кода 
} else {
1 строка кода
}

лучше заменить логическое условие на противоположное, поменять блоки кода в {} местами, сделать return из 1 блока кода, тогда можно отказаться от else - это сделает код более читаемым и легким для понимания

2023-12-11 14:02 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age == 0 || (age >= 5 && age <= 20) || (age >= 105 && age <= 120)) {
Внес следующие изменения:
1. Добавил отдельный метод printAge, который выводит результат.
2. Добавил в методе getAgeString еще один return, чтобы убрать вложенные условия IF.
3. Добавив в условие сравнение по остатку от деления на 100. 
4. Скорректировал имена переменных.

2023-12-11 20:37 UTC, EvgeneZhurov requested changes

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String declension = "Вам " + age;
переменная лишняя. Делайте return в каждом if

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " лет";
лучше сделать return

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " годa";
лучше сделать return

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " год";
лучше сделать return

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (moduloDivision10 >= 2 && moduloDivision10 <= 4) {
это условие не нужно и выполнится автоматически

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0 || age > 150) {
в задаче другие условия валидации

2023-12-11 20:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int moduloDivision10 = age % 10;
некорректное название, это остаток от деления"

2023-12-12 08:49 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String declension = "Вам " + age;
Удалил переменную. Добавил return для if.

2023-12-12 08:50 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " лет";
Добавил return для if.

2023-12-12 08:50 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " годa";
Добавил return для if.

2023-12-12 08:50 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            resultString = declension + " год";
Добавил return для if.

2023-12-12 08:52 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0 || age > 150) {
Скорректировал условия для возраста (age < 0 || age > 127) в соответствии с условиями в задаче.

2023-12-12 08:53 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int moduloDivision10 = age % 10;
Поменял название переменных на moduloRemainder10 и moduloRemainder100.

2023-12-12 08:55 UTC, Bercut-Alex commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (moduloDivision10 >= 2 && moduloDivision10 <= 4) {
Имеется ввиду, что сравнениях "(moduloDivision100 >= 5 && moduloDivision100 <= 20)" и  "moduloDivision10 >= 5 && moduloDivision10 <= 10)" есть пересекающиеся значения? Или одно из сравнений избыточно и его можно исключить из условия?

2023-12-12 09:04 UTC, EvgeneZhurov requested changes

2023-12-12 09:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          return null; // Заглушка. При реализации - удалить
этот return нужно убрать.

2023-12-12 09:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (moduloRemainder10 == 1) {
Когда отработаны все остальные условия, последнее выполнится без всяких условий автоматически, потому что другого выбора нет. Этот if не нужен. Я бы сделал по другому. Это условие короткое и внятное, я бы вынес его обрабатываться выше, и избавился от if в блоке выше: if (moduloRemainder10 >= 2 && moduloRemainder10 <= 4)

2023-12-12 09:51 UTC, EvgeneZhurov approved these changes

2023-12-12 09:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        {
лучше ставить { в той же строке, что и if и использовать единый стиль кода ко всем блокам.

2023-12-12 09:51 UTC, closed without merging