Chapter 4 Task 18
KFalcon2022/intensive-tasks pull request #687
Opened 2023-12-11 11:51 UTC by lambo64

2023-12-11 21:49 UTC, EvgeneZhurov requested changes

2023-12-11 21:49 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +        int count = 0;
если счетчик создан, чтобы исключать случаи пустых прохождений по циклам, то он работает некорректно. Пройдите дебагом по методу с данным массивом:{1, 2, 3, 4, 6, 5, 7, 8, 9, 10}

2023-12-11 21:49 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            if (count == 0 || left >= right) {
лучше вставить это логическое условие в логические выражение метода 
for ( ; логическое выражение ; )

2023-12-13 20:30 UTC, lambo64 commented
ошибку поняла, исправила)

2023-12-14 16:34 UTC, EvgeneZhurov approved these changes

2023-12-14 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +
Лучше не ставить 2 пустых строки в коде никогда. Здесь они вообще н нужны

2023-12-14 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +            int count = 0;
как я понимаю эта переменная нужна для выполнения некоторого условия - то есть это завуалированная логическая переменная. Лучше пытаться писать максимально понятный код используя релевантные переменные.

2023-12-14 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Main.java
> +
код должен был остановиться тут, если бы был отсортированный массив

2023-12-14 16:34 UTC, closed without merging