chapter 2 task 8
KFalcon2022/intensive-tasks pull request #689
Opened 2023-12-11 12:25 UTC by mirchello

chapter 2 task 8
init solution

2023-12-11 19:02 UTC, KFalcon2022 requested changes

2023-12-11 19:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        double[] probabilities = new double[28];
Откуда берутся 28 и ниже - 13? Если это чем-то обусловлено - стоит вынести эти значения в константы с понятными именами

2023-12-11 19:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        double[] probabilities = new double[28];
При необходимости можно внести объяснения к константам в виде комментариев. Но оставлять магические значения в коде - очень пагубная практика

2023-12-11 19:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
>      }
После исправления замечаний напиши в ЛС с ссылкой на ПР. https://t.me/ironicMotherfucker

2023-12-28 19:07 UTC, KFalcon2022 requested changes

2023-12-28 19:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        double[] probabilities;
объявляем переменные как можно ближе к их использованию

2023-12-28 19:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        } else {
зачем тут else? Если программа зайдет в if - она выйдет из метода (из-за return)

2023-12-28 19:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return result + n;
к моменту выполнения этой строчки n - гарантированно будет 0. Исходя из условия цикла

2023-12-28 19:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
>      }
Переусложнил решение. Предлагаю исправить замечания и посмотреть, как можно после этого оптимизировать программу. Если будет затык - пиши в ЛС

2024-01-08 10:41 UTC, EvgeneZhurov commented
pr висит без изменений больше недели. Если требуется ревью - откройте новый PR.

2024-01-08 10:41 UTC, closed without merging