Task2
KFalcon2022/intensive-tasks pull request #69
Opened 2023-11-20 08:31 UTC by Lunularis

2023-11-20 19:18 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:
10, 3, 40. 
Expected :40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо
Actual   :2 подъезд, 1 этаж, справа от лифта, вправо

2023-11-21 04:44 UTC, Lunularis commented
Исправила, но запуталась с ветками в Гите...

2023-11-21 07:36 UTC, ekolokolov approved these changes
Зачтено. 
С замечаниями

2023-11-21 07:36 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +            answer = "" + (entrance + 1) + " подъезд, ";
Можно не передавать пустую строку. 
Оставить только `(entrance + 1) + " подъезд, "`

2023-11-21 07:36 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task2/Main.java
> +        }else {
Форматирование хромает. Не хватает пробелов после фигурных скобок или знаков умножения/деления.
Советую отформатировать с помощью IDE

2023-11-21 08:30 UTC, closed without merging

2023-11-22 01:10 UTC, Lunularis commented
Спасибо за обратную связь!
Можно еще раз выложить, чтобы зачесть без замечаний?) И как это сделать?