Chapter 4, Task 16
KFalcon2022/intensive-tasks pull request #691
Opened 2023-12-11 13:52 UTC by Kegeke

2023-12-11 21:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Main.java
> +        int min = Integer.MAX_VALUE;
объясните причину, зачем Вы взяли и именно максимальное значение, какой в этом смысл?

2023-12-11 21:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Main.java
> +        int minIndex = 0;
почему индекс 0, а не аргумент в методе?

2023-12-11 21:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Main.java
> +        sortSelection(initsArray);
если вы вызываете метод и не ждете от него возвращаемого значения, лучше сделать метод void

2023-12-12 09:10 UTC, EvgeneZhurov requested changes

2023-12-12 09:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Main.java
> +        int[] initsArray = {-4, 2, -1, 3, 1, 7, 24, 9};
{10, 2, 11, 3, 1, 7, 24, 9}
не сортируется.

2023-12-12 10:08 UTC, EvgeneZhurov approved these changes
Логичнее было бы присваивать минимальному значению самый левый индекс сортируемого массива.

2023-12-12 10:08 UTC, closed without merging

2023-12-12 10:09 UTC, Kegeke commented
Что-то не додумался до такого:)