Chapter 3 Task11
KFalcon2022/intensive-tasks pull request #697
Opened 2023-12-11 18:18 UTC by KungFU13

2023-12-11 19:26 UTC, KFalcon2022 requested changes

2023-12-11 19:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            for (int i = 0; i < array.length - div + 1; i++) {
вместо +1 логичнее использовать <=. Ниже то же самое

2023-12-11 19:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                sumArrayDiv += total;
почему бы сразу во втором цикле не прибавлять array[j] к sumArrayDiv?

2023-12-11 19:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            for (int i = 0; i < array.length - div + 1; i++) {
лишний отступ перед for

2023-12-11 19:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        if (array.length % 2 != 0){
Логичнее этот блок выполнить перед циклом - иначе теряется контекст

2023-12-12 16:23 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        if (array.length % 2 != 0){
исправил

2023-12-12 16:23 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            for (int i = 3; i < array.length; i = i + 2) {
исправил

2023-12-12 16:24 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            sum = sum * 2;
убрал

2023-12-12 16:24 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            for (int i = 0; i < array.length - div + 1; i++) {
исправил

2023-12-12 16:24 UTC, KungFU13 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                sumArrayDiv += total;
исправил

2023-12-12 20:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +}
Задача зачтена

2023-12-12 20:04 UTC, closed without merging