Chapter3 task11
KFalcon2022/intensive-tasks pull request #710
Opened 2023-12-12 09:19 UTC by SenyaDiamond

2023-12-13 15:56 UTC, EvgeneZhurov requested changes

2023-12-13 15:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +
1 PR - 1 задача

2023-12-13 15:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +
int[] array = {10, 11, 12};
ожидалось 66
Результат: 10111210111266
Придется переделать.

2023-12-14 09:24 UTC, SenyaDiamond commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +
Действительно, затерялся лишний out.print спасибо.

2023-12-14 09:26 UTC, SenyaDiamond commented
Исправил, на заголовок прошу внимания не обращать по факту это 3 глава 11 задание

2023-12-15 15:43 UTC, EvgeneZhurov requested changes

2023-12-15 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +
Просьба поправить, 1 pr - 1 файл (сейчас их 15)

2023-12-26 17:19 UTC, EvgeneZhurov commented
Висит без изменения более недели. В случае необходимости создайте новый PR.

2023-12-26 17:19 UTC, closed without merging