Chapter 4 Task 17
KFalcon2022/intensive-tasks pull request #727
Opened 2023-12-13 08:19 UTC by KrisLu23

2023-12-16 12:26 UTC, EvgeneZhurov requested changes

2023-12-16 12:26 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +        int count;
Примитив int здесь имеет скрытый смысл boolean, он проверяет логическое условие, не отсортирован ли уже массив. Старайтесь максимально по назначению использовать переменные и не прятать в них искаженный смысл, будет сложнее разобраться в больших программах с таким подходом.

2023-12-16 12:26 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +        do {
do редко когда нужен, как раз скрытая boolean переменная помешала создать код без do. Создайте логическую переменную выше цикла и присвойте ей true, уберите do, в цикле 1 делом присвойте логической переменной false, и только в случае перестановки элементов присваивайте ей true. Код будет читаться легче.

2023-12-18 09:30 UTC, KrisLu23 commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +        do {
Благодарю за подсказки с подробным объяснением.

2023-12-18 19:31 UTC, EvgeneZhurov approved these changes

2023-12-18 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +        boolean count = true;
лучше стараться давать максимально релевантные и внятные имена - это не счетчик. переменные boolean лучше называть со слова is. Например isTrue, так повышается читаемость и видно, что это логическая переменная

2023-12-18 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +        int tempArrayLength = array.length;
слово temp не несет никакой смысловой нагрузки и оно лишнее.

2023-12-18 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +                int temp = array[i];
нужно стараться объявлять переменные с минимальной областью видимости и максимально близко к 1 месту использования, здесь это внутри блока if ниже

2023-12-18 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Main.java
> +            }
блоки кода, например while лучше отделять пустыми строкам с обеих сторон, так читается лучше.

2023-12-18 19:36 UTC, closed without merging