task 1
KFalcon2022/intensive-tasks pull request #76
Opened 2023-11-20 10:00 UTC by lambo64

2023-11-20 11:16 UTC, ekolokolov requested changes
Не корректно выполняется на значениях:
1, 10, 21, *1, 101, 102, 103, 104, 122 - 127.

2023-11-20 13:35 UTC, lambo64 commented
Не поняла куда нужно нажать, но правки внесла

2023-11-21 08:37 UTC, ekolokolov requested changes

2023-11-21 08:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return (age % 100 % 10);
Для того чтобы получить остаток от деления не надо делать ни каких преобразований. 

15 % 10 = 5
115 % 10 = 5
3215 % 10 = 5

2023-11-21 08:37 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if (age == 1) return ("Вам " + age + " год");
по правилам форматирования else if должны быть на той же строке что и }

вот так `} else if (`

так же, если после условия else сразу идет return - все равно надо ставить фигурную скобку 
```Java
   if ((age >= 10 && age <= 20) || (age >= 110 && age <= 120)) {
            return ("Вам " + age + " лет");
        } else if (age == 1) {
            return ("Вам " + age + " год");
        } else {
```

2023-11-21 13:12 UTC, lambo64 commented
исправила

2023-11-22 08:14 UTC, ekolokolov approved these changes
Зачтено с замечаниями.

2023-11-22 08:15 UTC, closed without merging