Решение задачи Дом
KFalcon2022/intensive-tasks pull request #761
Opened 2023-12-14 14:30 UTC by llwoodruff

2023-12-14 15:42 UTC, EvgeneZhurov requested changes
Продолжим после исправления

2023-12-14 15:42 UTC, EvgeneZhurov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
1 PR - 1 файл

2023-12-14 15:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        System.out.println(getFlatLocation(2, 5, 1));
System.out.println(getFlatLocation(-2, -5, 1));
1 кв - 0 подъезд, -1 этаж, слева от лифта, влево

2023-12-14 15:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (floorFlatAmountMod == 1) {
лучше реализовать через switch case.

2023-12-14 15:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String direction;
Переменные заводят максимально близко к месту их 1 использования. Незаданная переменная - редкость.

2023-12-14 15:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floorFlatAmount = 4;
лучше использовать модификатор доступа final, чтобы это было константой и это значение нельзя было поменять

2023-12-14 17:18 UTC, llwoodruff commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floorFlatAmount = 4;
Внесла все изменения

2023-12-16 10:13 UTC, EvgeneZhurov approved these changes

2023-12-16 10:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floorFlatAmountMod = flatNumber % floorFlatAmount;
пара моментов: 1) лучше заводить переменную максимально близко к месту ее использования. 
2) Можно не заводить переменную, которая используется в коде 1 раз.

2023-12-16 10:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        switch (floorFlatAmountMod) {
String direction = switch (floorFlatAmountMod) {
            case 1 -> "слева от лифта, влево";
            case 2 -> "слева от лифта, вправо";
            case 3 -> "справа от лифта, влево";
            default -> "справа от лифта, вправо";
        };

2023-12-16 10:14 UTC, closed without merging