Решение задачи Високосный год
KFalcon2022/intensive-tasks pull request #762
Opened 2023-12-14 15:04 UTC by llwoodruff

2023-12-16 11:59 UTC, EvgeneZhurov requested changes

2023-12-16 11:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if(year % 400 == 0 || (year % 4 == 0 && year % 100 != 0)){
здесь не нужен if, можно сразу писать return и логическое условие.

2023-12-28 15:23 UTC, llwoodruff commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if(year % 400 == 0 || (year % 4 == 0 && year % 100 != 0)){
убрала

2023-12-28 17:46 UTC, EvgeneZhurov approved these changes

2023-12-28 17:47 UTC, closed without merging