Resolve Chapter1 Task1
KFalcon2022/intensive-tasks pull request #764
Opened 2023-12-14 18:45 UTC by Nicholas71931

2023-12-16 12:05 UTC, EvgeneZhurov requested changes

2023-12-16 12:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            old = " год";
лучше делать return в каждом if

2023-12-16 12:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (ageLastNumber == 1)
просьба придерживаться правил комьюнити и ставить { } даже при 1 строке кода

2023-12-16 12:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String old = "";
здесь не нужна строка

2023-12-16 12:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        boolean exclusion = (age % 100 >= 11) && (age % 100 <= 14);
иногда вводят переменные для однократного использования ,например, для печати, но в методе не стоит создавать переменную для однократного использования.

2023-12-24 19:59 UTC, Nicholas71931 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            old = " год";
Сделал return

2023-12-24 20:00 UTC, Nicholas71931 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (ageLastNumber == 1)
Поставил скобки

2023-12-24 20:00 UTC, Nicholas71931 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String old = "";
Убрал строку

2023-12-24 20:01 UTC, Nicholas71931 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        boolean exclusion = (age % 100 >= 11) && (age % 100 <= 14);
убрал переменную

2023-12-25 11:41 UTC, EvgeneZhurov requested changes

2023-12-25 11:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Вам " + age + " лет";
у Вас 3 слова и 4 return. Попробуйте составить логические условия таким образом, чтобы количество return совпадало с количеством возвращаемых слов.

2023-12-25 11:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 100 >= 11) && (age % 100 <= 14)) {
лучше отделять логические блоки пустыми строками с обеих сторон, если они не стоят сразу после { и перед }. Это повышает читаемость

2023-12-25 11:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 100 >= 11) && (age % 100 <= 14)) {
вы завели отдельную перемену для деления на 10, потому что она используется несколько раз. Тогда лучше быть последовательным и завести переменную для деления на 100

2023-12-25 11:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int ageLastNumber = age % 10;
сделайте блок валидации, который будет возвращать строку с информацией, если данные введены неверно.

2024-01-08 15:15 UTC, closed without merging

2024-01-08 15:15 UTC, EvgeneZhurov commented
pr висит более недели без изменений. Если требуется проверка - откройте новый pr.