Chapter3_Task13 "Полив"
KFalcon2022/intensive-tasks pull request #765
Opened 2023-12-14 21:05 UTC by PavloKutsyn

2023-12-16 21:35 UTC, EvgeneZhurov requested changes

2023-12-16 21:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int[] plants = {2, 2, 3, 3};
int[] plants = {1, 1, 1, 4, 2, 3};
        int wateringCanVolume = 4;
ожидаемый ответ: 30

2023-12-16 21:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int waterInCan = 0; // Текущее количество воды в лейке
лучше стараться избегать предлогов в названиях переменных.

2023-12-17 14:22 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int waterInCan = 0; // Текущее количество воды в лейке
изменил название переменной

2023-12-17 14:23 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        int[] plants = {2, 2, 3, 3};
нашёл способ расчёта шагов

2023-12-17 15:48 UTC, EvgeneZhurov approved these changes

2023-12-17 15:48 UTC, closed without merging