Chapter 4, Task 18
KFalcon2022/intensive-tasks pull request #769
Opened 2023-12-15 11:26 UTC by Kegeke

2023-12-17 17:22 UTC, EvgeneZhurov requested changes

2023-12-17 17:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        int count = 0;
здесь count - это завуалированная логическая переменная, пока кусок кода маленький, это еще можно понять, но в реальном коде логика будет трудно читаема. Лучше стараться максимально релевантно подбирать переменные. Просьба поправить

2023-12-19 08:53 UTC, EvgeneZhurov requested changes

2023-12-19 08:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        int elementRearrangement = 0;
я думаю Вы меня не поняли. Эта переменная на самом деле boolean. Вы целочисленной переменной пытаетесь заменить логическую переменную, которая отвечает на вопрос, отсортирован ли массив? Совет так не делать. Создайте логическую переменную и пользуйтесь ей.

2023-12-19 08:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +
если попался отсортированный массив и цикл прошел вправо без изменений, пора выходить из метода.

2023-12-21 12:47 UTC, EvgeneZhurov requested changes

2023-12-21 12:47 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +            for (int j = right; j > left; j--) {
если массив пройдя вправо стал отсортированным, цикл прошел влево без изменений, пора выходить из метода.

2023-12-28 09:42 UTC, Kegeke commented
Мда, забыл как делать, не знаю что доделать)

2024-01-02 17:53 UTC, EvgeneZhurov requested changes

2024-01-02 17:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
>              boolean isElementRearrangement = false;
Чувствуется, что новый год скорее всего в салат. Не нужно заводить лишнюю переменную, достаточно 1 логической переменной.

2024-01-02 17:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
>                  int temp = array[j - 1];
лучше переменную temp завести внутри if, лучше стремиться задавать минимальную область видимости переменной.

2024-01-02 17:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> -            if (!isElementRearrangement) {
Уже писал выше: если попался отсортированный массив и цикл прошел вправо без изменений, пора выходить из метода! Здесь нужен if с return внутри

2024-01-11 07:01 UTC, EvgeneZhurov requested changes

2024-01-11 07:01 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +
не исправлено замечание: Если проходя влево массив оказался отсортированным пора выходить из метода.

2024-01-11 07:09 UTC, EvgeneZhurov approved these changes
да, так.

2024-01-11 07:09 UTC, closed without merging