Chapter 4. task 16
KFalcon2022/intensive-tasks pull request #772
Opened 2023-12-15 14:00 UTC by sauza7

2023-12-17 17:31 UTC, EvgeneZhurov requested changes

2023-12-17 17:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        for (int i = 0; i < array.length - 1; i++) {
алгоритм работает неверно, на втором шаге цикла число 10 встает на индекс 1, пройдите дебагом и проверьте.

2023-12-18 11:25 UTC, sauza7 commented
Изменил для поиска минимума, но не понял чем первое решение было не верным.

2023-12-18 19:53 UTC, EvgeneZhurov approved these changes

2023-12-18 19:54 UTC, closed without merging