Chapter4 task19
KFalcon2022/intensive-tasks pull request #776
Opened 2023-12-15 14:07 UTC by PavloKutsyn

2023-12-17 18:09 UTC, EvgeneZhurov requested changes

2023-12-17 18:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        for (int value : array) {
System.out.println(Arrays.toString(array));

2023-12-17 18:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int pivot = array[end];
Выбор опорного элемента не соответствует требованию задачи, просьба переделать

2023-12-19 08:48 UTC, EvgeneZhurov requested changes

2023-12-19 08:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int[] array = {10, 7, 8, 9, 1, 5, -100, 1000};
int[] array = {10, 7, 8000, 9000, 1, 5, 11, 10};
не сортирует.

2023-12-19 14:47 UTC, PavloKutsyn commented
Старый код:
В старом коде рекурсивный вызов sortByQuicksort включает в себя сегменты массива до и после partitionIndex - 1 и partitionIndex + 1 соответственно.
Разделение (partition) производится с выбором опорного элемента как среднее между максимальным и минимальным значением подмассива.
Новый код:
В новом коде изменение заключается в изменении границ для рекурсивных вызовов quicksort.
Теперь включается partitionIndex в правую часть сортировки: quicksort(array, pivotIndex, right). 
Идея в том, что элементы, равные опорному элементу, могут быть более эффективно распределены между двумя подмассивами.
Добавлена специальная обработка для массивов длиной 2, которая учитывает случай, когда нужно всего лишь поменять два элемента местами.
Логика выбора опорного элемента остается прежней, но изменение в логике рекурсивного вызова quicksort помогает справляться с распределением элементов вокруг опорного елеммента

2023-12-19 14:48 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int[] array = {10, 7, 8, 9, 1, 5, -100, 1000};
изменил код, добавил условие когда в подмасиве 2 елемента

2023-12-19 14:50 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int pivot = array[end];
прошу прощения, я стлько времение сижу над этим кодом, что уже условия задачи немного в голове затёрлись, как следствие и в коде тоже.
Обновил условие выбора опорного елемента.

2023-12-19 14:50 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        for (int value : array) {
спасибо за подсказку, так намного проще и без for each

2023-12-19 15:06 UTC, EvgeneZhurov requested changes

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        if (begin < end) {
условие для рекурсии пишется отдельно с return, без else.
Это облегчит понимание кода. То есть блоки состоят из последовательностей: выход из рекурсии, поиск опорного элемента, разбитие массива на 2 части в соответствии с опорным элементом и вызов рекурсии с обоими подмассивами без всяких условий.

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int i = begin, j = end;
лучше не использовать названия итераторов i, j, k... Они используются для циклов. Можно использовать например "лево", "право"

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int pivot = (max + min) / 2;
пустая строка выше pivot

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +    private static int partition(int[] array, int begin, int end) {
лучше называть метод начиная с глагола и максимально релевантно: getPartitionIndex. Если Вы пишете конкретный метод для задачи, то метод должен делать ровно то, что от него хотят и ничего более. Здесь производится поиск и представление элементов

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        return i;
небольшой полезный лайфхак: если давать название возвращаемой переменной в методе так же как и сам метод без глагола, это повысит читаемость кода. Будет наглядно.

2023-12-19 15:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +            if (i <= j) {
лучше отделять блоки кода пустыми строками

2023-12-19 15:31 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        return i;
исправил

2023-12-19 15:32 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +    private static int partition(int[] array, int begin, int end) {
Метод partition переименован в getPartitionIndex

2023-12-19 15:32 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int pivot = (max + min) / 2;
исправил

2023-12-19 15:33 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int i = begin, j = end;
left, right испраил

2023-12-19 15:34 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        if (begin < end) {
думаю я верно понял

        if (begin >= end) {
            return;
        }

        if (end - begin == 1) {
            if (array[begin] > array[end]) {
                swap(array, begin, end);
            }
            return;
        }

2023-12-19 15:37 UTC, PavloKutsyn commented
1. Условие для выхода из рекурсии в sortByQuicksort теперь написано отдельно с return.
2. Изменены названия итераторов в partition на left и right.
3. Добавлены пустые строки
4. Метод partition переименован в getPartitionIndex для лучшего отражения его функциональности.
5. Возвращаемая переменная в getPartitionIndex теперь называется left для соответствия с названием метода.

2023-12-19 16:31 UTC, EvgeneZhurov approved these changes
Верно

2023-12-19 16:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        for (int k = begin + 1; k <= end; k++) {
итератор 1 уровня вложенности обычно называют i

2023-12-19 16:32 UTC, closed without merging

2023-12-19 16:34 UTC, PavloKutsyn commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        for (int k = begin + 1; k <= end; k++) {
Аж самому смешно 
Немного все замылилось, слишком долго делал и переделывал