Chapter4 Task18
KFalcon2022/intensive-tasks pull request #779
Opened 2023-12-15 20:46 UTC by k2336351

2023-12-17 18:16 UTC, EvgeneZhurov requested changes

2023-12-17 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +
если на вход подан отсортированный массив, здесь должен быть выход

2023-12-21 12:54 UTC, EvgeneZhurov requested changes

2023-12-21 12:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        boolean isSortedMin = true;
достаточно 1 логической переменной isSorted.

2023-12-21 12:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +                isSortedMax = false;
неверная логика, пройдя по циклу 1 раз переменная станет false, а вдруг на втором проходе цикла массив станет отсортированным, нужно выходить и метода. По этому каждый раз начиная новую итерацию цикла нужно снова присваивать true.

2023-12-23 16:56 UTC, k2336351 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +                isSortedMax = false;
Спасибо, я поняла, наконец!

2023-12-23 19:50 UTC, EvgeneZhurov approved these changes
Засчитано. Могу ошибаться, но мне кажется это единственная реализация этой задачи через рекурсию, которую я видел :)

2023-12-23 19:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        return getShakerSortedArray(array, arrayLength - 1, lastMinValueCheckIndex + 1);
Используя рекурсию лучше писать условие выхода из рекурсии вначале метода.

2023-12-23 19:50 UTC, closed without merging