task 3
KFalcon2022/intensive-tasks pull request #79
Opened 2023-11-20 10:03 UTC by lambo64

2023-11-20 17:54 UTC, ekolokolov requested changes
Не верное исполнение для значений:
2020, 2021, 2022, 2023, 2024

2023-11-20 18:53 UTC, lambo64 commented
перепутала true с false(

2023-11-21 08:40 UTC, ekolokolov approved these changes
Зачтено.
С замечаниями

2023-11-21 08:40 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task3/Main.java
> +            } else return true;
после else ВСЕГДА идет фигурная скобка 
` } else {`

При сильном желании уменьшить количество строк кода - можно попробовать объединить условия.

2023-11-21 08:40 UTC, closed without merging