chapter 5, task21
KFalcon2022/intensive-tasks pull request #790
Opened 2023-12-17 13:02 UTC by Greem4

2023-12-17 18:58 UTC, EvgeneZhurov requested changes

2023-12-17 18:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    public static boolean checkIntersection(Sphere sphere, Parallelepiped parallelepiped) {
метод в ряде случаев выдает неверный результат

2023-12-17 20:42 UTC, EvgeneZhurov requested changes

2023-12-17 20:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    private static void checkIntersectionForPairs(List<Sphere> spheres, List<Parallelepiped> parallelepipeds) {
не очень понял ход мысли. Не требовалось создавать новый метод. Метод checkIntersection работает неверно

2023-12-17 20:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    private static void checkIntersectionForPairs(List<Sphere> spheres, List<Parallelepiped> parallelepipeds) {
лучше избегать предлогов в названиях методов

2023-12-17 20:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    public static boolean checkIntersection(Sphere sphere, Parallelepiped parallelepiped) {
часто методы boolean начинаются со слова is

2023-12-17 20:49 UTC, Greem4 commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    private static void checkIntersectionForPairs(List<Sphere> spheres, List<Parallelepiped> parallelepipeds) {
Увлекся малость , хотел сделать красиво , но перемудрил , убрал метод

2023-12-17 20:51 UTC, Greem4 commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +    public static boolean checkIntersection(Sphere sphere, Parallelepiped parallelepiped) {
Надо подтянуть английский , и внимательно почитать про методику названия методов . Спасибо !

2023-12-17 20:55 UTC, EvgeneZhurov requested changes
Сергей, советую налить чайку, подумать и переписать метод. Он концептуально считает длины, которые не смогут ответить на поставленный вопрос корректно.

2023-12-17 20:58 UTC, EvgeneZhurov commented
Просьба ответить на вопрос. Как Вы понимаете условие задачи: AB главная диагональ прямоугольного параллелепипеда, а ребра параллельны базису?

2023-12-17 21:10 UTC, Greem4 commented
> Просьба ответить на вопрос. Как Вы понимаете условие задачи: AB главная диагональ прямоугольного параллелепипеда, а ребра параллельны базису?
Диагональ от одного угла тянется к противоположному углу ,  а ребра получаются параллельны осям координат.  Писать код в впопыхах плохая идея, спасибо вам , я на недели лучше посижу и подумаю.

2023-12-17 21:12 UTC, EvgeneZhurov commented
Понимание в расположении фигуры в пространстве верное

2023-12-19 09:24 UTC, Greem4 commented
Спокойно подумав, понял в чем ошибка, заходя на грань параллелепипеда  он выдовал false,

2023-12-19 09:38 UTC, EvgeneZhurov requested changes

2023-12-19 09:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Sphere sphere1 = new Sphere(0, 0, 0, 1);
Sphere sphere1 = new Sphere(0, 0, 2, 1);
Parallelepiped parallelepiped1 = new Parallelepiped(0, 0, 0, 1, 1, 1);
ответ: нет
Правильный ответ: да
точка касания (0,0,1)

2023-12-19 09:43 UTC, Greem4 commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Sphere sphere1 = new Sphere(0, 0, 0, 1);
На это все ) спасибо вам за труды. Но для мне такая математика /  перебор ) Наверное лучше займусь сортировкой , а на матрицу даже смотреть не буду .

2023-12-19 09:47 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Sphere sphere1 = new Sphere(0, 0, 0, 1);
Обычная школьная математика. Цель курса - развитие. Было сказано сразу. Определитель матрицы несложный. Создаем новую матрицу отрезая 1 строку и 1 столбец, вызываем рекурсию. Это 10 строк кода.

2023-12-19 09:50 UTC, Greem4 commented
Забыл что там больше либо равно должно было стоять

2023-12-19 09:54 UTC, Greem4 commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Sphere sphere1 = new Sphere(0, 0, 0, 1);
Не в укор вам, весь курс и материал мне очень понравились , хоть с 95% что вы рассказывали я был знаком, а вот решать такие задачи да еще и ваши проверки , тут все всяких похвал , этого очень не хватало. По этому очень благодарен вам за проделанную работу

2023-12-19 10:05 UTC, EvgeneZhurov requested changes

2023-12-19 10:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +
лучше не ставить 2 пустые строки подряд.

2023-12-19 10:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Sphere sphere1 = new Sphere(0, 0, 2, 1);
Sphere sphere3 = new Sphere(-13, -13, -13, 15);
        Parallelepiped parallelepiped3 = new Parallelepiped(0, 0, 0, -10, -10, -10);
неверно

2023-12-19 19:23 UTC, Greem4 commented
Добавил в конструктор возможно находить верхний левый и правый нижний угол, вроде пмогло

2023-12-19 20:57 UTC, EvgeneZhurov approved these changes
Напишите в личку, нужно договориться как передать вино

2023-12-19 21:03 UTC, closed without merging