Resolve Chapter1.Task2
KFalcon2022/intensive-tasks pull request #792
Opened 2023-12-17 13:16 UTC by DevTorch

2023-12-17 13:51 UTC, EvgeneZhurov requested changes
Исправьте, и будем думать над задачей дальше.

2023-12-17 13:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +    static String leftOrRight = "";
просьба обойтись без полей класса, нужно пытаться использовать переменные с минимальной областью видимости, а не поднимать их над методами, они этого не заслужили

2023-12-17 13:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        System.out.println(getFlatLocation(10, 3, 40));
не проходит валидацию:        System.out.println(getFlatLocation(-10, -3, 40));

2023-12-17 13:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            case 1, 2 -> leftOrRight = ", слева от лифта, влево";
это не так, там 4 расположения квартир. Например 2 квартира влево от лифта направо

2023-12-17 13:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String totalString = flatNumber + " кв - " + getEntrance(floorAmount, flatNumber) + " подъезд, "
можно вернуть строку, можно и не создавать. Idea подсказывает, что лучше не создавать строку, чтобы использовать ее тут же 1 раз

2023-12-17 16:13 UTC, DevTorch commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            case 1, 2 -> leftOrRight = ", слева от лифта, влево";
При этом % без коррекции на единицу дает порядок квартир на этаже: 1, 2 , 3, 0

2023-12-17 16:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            case 1, 2 -> leftOrRight = ", слева от лифта, влево";
жду исправленное решение и будем думать дальше. Еще заведите константу для числа 4 используя модификатор доступа final, и почитайте про магическое число Java.

2023-12-17 16:58 UTC, DevTorch commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            case 1, 2 -> leftOrRight = ", слева от лифта, влево";
Принял, спасибо. За предыдущий комментарий прощу прощения. Был невнимателен и пропустил тот факт, что они и между собой «вправо/влево» разделяются.

2023-12-17 18:05 UTC, EvgeneZhurov requested changes

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>          while (maxFlat - 3 > flatNumber) {
блоки кода лучше отделять пустыми строками, так читается легче

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (floorAmount <= 0 || entranceAmount <= 0 || flatNumber <= 0) return "Такой квартиры не существует";
есть правила согласованные комьюнити, просьба их соблюдать, даже 1 строка выделяется {}

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>              return "Такой квартиры не существует";
это условие валидации, как и другие выше, зачем делать 2 разных return с одним и тем же выходом? Чем меньше кода, тем легче читать.

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        System.out.println(getFlatLocation(-10, -3, 40));
System.out.println(getFlatLocation(10, 3, 40));
40 кв - 1 подъезд, 10 этаж, справа от лифта, влево
с хрущевках по часовой стрелке
ожидалось: 40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>          int maxFlat = getEntrance(floorAmount, flatNumber) * floorAmount * 4;
писал про заведение константы в PR, читайте.

2023-12-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>          while ((setEntrance * floorAmount * 4) < flatNumber) {
это даст алгоритмическую сложность O(n), когда можно легко посчитать через % и Math.ceil pf O(1). Просьба переделать.

2023-12-18 20:13 UTC, EvgeneZhurov approved these changes

2023-12-18 20:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>          String leftOrRight = "";
еще можно так:
        String leftOrRight = switch (flatNumber % FLATS_ON_THE_FLOOR) {
            case 1 -> ", слева от лифта, влево";
            case 2 -> ", слева от лифта, вправо";
            case 3 -> ", справа от лифта, влево";
            default -> ", справа от лифта, вправо";
        };

2023-12-18 20:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            maxFlatInCurrentEntrance = maxFlatInCurrentEntrance - FLATS_ON_THE_FLOOR;
лучше избегать предлогов во всех переменных.

2023-12-18 20:13 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        while (maxFlatInCurrentEntrance - 3 > flatNumber) {
можно придумать, как посчитать номер этажа без цикла. нужно пытаться использовать лучшую алгоритмическую сложность в коде.

2023-12-18 20:13 UTC, closed without merging