Resolve Chapter1.Task4
KFalcon2022/intensive-tasks pull request #794
Opened 2023-12-17 13:18 UTC by DevTorch

2023-12-17 17:11 UTC, EvgeneZhurov requested changes

2023-12-17 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0 && c == 0) return "Решений бесконечно";
обращайте внимание на варнинги, идея советует дельные вещи 
c == 0 - это условие избыточно и не нужно. Потому что условие выше и так исключает все остальные условия кроме 0

2023-12-17 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0 && c != 0) return "Количество решений: 0.";
есть правила, которые согласованы местным комьюнити. Просьба ставить {} b c 1 строкой кода. Просьба исправить везде в коде.

2023-12-17 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        int setRoots;
старайтесь объявлять переменную максимально близко к моменту использования. Переменная без присвоенного значения редкость и указывает, что скорее всего Вы объявили ее рано, может быть return до ее применения и она не нужна

2023-12-17 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (int) ((c / b) * -1);
решение любое вещественное число, не обязательно целое.

2023-12-17 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            outputTail = " Корень: " + x1;
сделайте return и переменная string не понадобится

2023-12-19 09:35 UTC, DevTorch commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (int) ((c / b) * -1);
Натолкните, пожалуйста, на мысль, как тогда на тестах быть со значением 2.0, когда ожидается 2. Ничего, кроме каста, не пришло в голову((

2023-12-19 09:44 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (int) ((c / b) * -1);
забить. Там в тестах бывают проколы. Делали быстро и на коленке. Смотрим часть тестов глазками. Старайтесь решать задачу и пытайтесь разобраться в сути, не обращайте внимание на тесты.

2023-12-19 11:16 UTC, EvgeneZhurov approved these changes

2023-12-19 11:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else {
небольшой, но крайне полезный лайфхак, который поможет облегчить код: Если у Вас есть If и 2 блока кода, первый из которых содержит много строк (больше 1 строки), а второй блок после else содержит всего 1 строку облегчить код можно поменяв логическое условие на противоположное, поменять блоки местами и отказаться от else вернув корни из метода  внутри блока if.

2023-12-19 11:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = ((-1 * b) / (2 * a));
((-1 * b) / (2 * a))
 x1 = -b / (2 * a);
читается лкгче

2023-12-19 11:17 UTC, closed without merging