Resolve Chapter1.Task5
KFalcon2022/intensive-tasks pull request #795
Opened 2023-12-17 13:18 UTC by DevTorch

2023-12-17 17:18 UTC, EvgeneZhurov requested changes

2023-12-17 17:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double p = (a + b + c) / 2;
метод валится         System.out.println(getAreaByHeron(1,2,4));
Подумайте над валидацией
Треугольник не должен быть вырожденным и должен существовать. Читайте условие задачи

2023-12-17 17:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    public static double[] returnedArray = new double[3];
без полей класса пожалуйста.

2023-12-17 17:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double triangleS = 2 * Math.sqrt(p * (p - a) * (p - b) * (p - c));
Вы создали метод по Герону, не стоит брать тело метода и дублировать его. Для этого методы и создаются, чтобы написать их раз и радоваться.

2023-12-19 11:52 UTC, DevTorch reviewed
В эту ветку Task6 попал ошибочно, он без изменений пока.

2023-12-19 13:34 UTC, EvgeneZhurov approved these changes

2023-12-19 13:35 UTC, closed without merging