Resolve Chapter2.Task10
KFalcon2022/intensive-tasks pull request #799
Opened 2023-12-17 13:31 UTC by DevTorch

2023-12-17 19:27 UTC, EvgeneZhurov requested changes

2023-12-17 19:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String temp = inputString.replaceAll("[\\p{Punct}+\\s+]", "").toLowerCase();
без регекса и создания новый строк стрингбилдета и стрингбуфера. У обертки char есть методы, отвечающий на вопрос: является ли символ буквой.

2023-12-17 19:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (temp.length() < 2) return false;
устал писать про скобки

2023-12-19 13:43 UTC, EvgeneZhurov requested changes

2023-12-19 13:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String temporaryString = "";
Просьба без создания строк в методе, создание строки и присваивание через цикл новых значений будет кушать память. В Java строка (String) является неизменяемым (immutable) объектом, то есть после создания строки её нельзя изменить. Когда мы изменяем строку, мы фактически создаем новую строку, которая содержит изменения. Поскольку курс про эффективность и грамотное использование ресурсов просьба решить задачу более эффективно. Достаточно двумя итераторами в одном цикле пробежать на встречу друг другу и перепрыгивая ненужные символы, проверяя сходную стоку через char например.

2023-12-21 07:26 UTC, DevTorch commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String temporaryString = "";
Спасибо за ваши подсказки! Узнал про CharacterIterator, но не уверен, что именно его вы имели ввиду. Я могу воспользоваться его методами или построение перебора классическими циклами – и есть цель?

2023-12-21 12:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String temporaryString = "";
Как удобно, я бы используя Character.isLetter() сравнивал бы палиндром с 2 сторон итераторами перепрыгивая итераторами символы, не являющиеся буквами

2023-12-22 12:05 UTC, DevTorch commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String temporaryString = "";
При таких условиях задача задача заиграла совсем другими красками) Прям здорово. Даже как-то стыдно стало за свои регэкспы и перевертыши...

Отправил на проверку новое решение.

2023-12-22 12:52 UTC, EvgeneZhurov requested changes

2023-12-22 12:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            while (!Character.isLetter(c1)) {
Нужно быть крайне аккуратным при использовании while. 
Попробуйте валидацию данной строки: "!!!!...   "

2023-12-22 12:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            while (!Character.isLetter(inputString.charAt(start))) {
При валидации данной строки: "!!!!... " вылетает исключение.

2023-12-22 15:07 UTC, EvgeneZhurov approved these changes

2023-12-22 15:07 UTC, closed without merging