task 4
KFalcon2022/intensive-tasks pull request #80
Opened 2023-11-20 10:25 UTC by lambo64

2023-11-20 21:48 UTC, EvgeneZhurov requested changes

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (a == 0 && b == 0 && c != 0) {
c != 0 это условие лишнее, ранее уже был return c = 0, значит условие должно выполниться автоматически.

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        if (d == 0)
Читайте требования к оформлению кода. Желательно ставить { } даже с 1 строкой ветвления.

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +
Много лишних пробелов

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
пробел не нужен

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
сразу после { пробел не нужен

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +
перед } пробел не нужен

2023-11-20 21:48 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
>      }
double a = 1;
            double b = 0;
            double c = 0;
Количество решений: 1. Корень:-0.0   откуда у 0 знак -?

2023-11-21 13:11 UTC, lambo64 commented
исправила

2023-11-22 15:09 UTC, EvgeneZhurov requested changes

2023-11-22 15:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if (d < 0) {
После return не ставят else. Поправьте везде.

2023-11-22 15:10 UTC, EvgeneZhurov commented
Засчитано.

2023-11-22 15:10 UTC, closed without merging