Chapter5 Task21
KFalcon2022/intensive-tasks pull request #835
Opened 2023-12-20 10:14 UTC by AkBoAl

2023-12-21 12:17 UTC, EvgeneZhurov requested changes

2023-12-21 12:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Parallelepiped parallelepiped1 = new Parallelepiped(1, 1, 1, 3, 3, 3);
Parallelepiped parallelepiped = new Parallelepiped(0, 0, 0, 2, 2, 2);
Sphere sphere = new Sphere(1, 3, 3, 1);
Результат: true
Ожидалось: false

2023-12-21 16:49 UTC, AkBoAl commented
Еще было бы круто, если кто-то посмотрит тест. Честно говоря я его просто слямзил с предыдущего теста и поправил под 21 задачу, вроде работает.

2023-12-25 15:40 UTC, DKagan495 requested changes

2023-12-25 15:40 UTC, DKagan495 commented on src/main/java/com/walking/intensive/chapter5/task21/Task21.java
> +        if (((parX1 - radius <= centerCircleX && centerCircleX <= parX1) || (parX2 <= centerCircleY && centerCircleY <= parX2 + radius)) && ((parY1 <= centerCircleY && centerCircleY <= parY2))) {
Я бы boolean expressions, что в скобках в if-стейтменте вынес в константы либо в переменные
Легче читать, что происходит

2023-12-25 15:40 UTC, DKagan495 commented on src/main/java/com/walking/intensive/chapter5/task21/Task21.java
> +        if ((parX1 <= centerCircleX && centerCircleX <= parX2) && ((parY1 - radius <= centerCircleY && centerCircleY <= parY1) || (parY2 <= centerCircleY && centerCircleY <= parY2 + radius))) {
isResult = выражению, что в скобках

2023-12-25 15:40 UTC, DKagan495 commented on src/main/java/com/walking/intensive/chapter5/task21/Task21.java
> +        return isResult;
Можно все булеан-экспрешены объединить (тут вроде дизъюнкия как раз вписывается) и сразу возвратить.
Опять же для читаемости поделить их на константы
Тем самым избавимся от множества if блоков

2023-12-25 15:40 UTC, DKagan495 commented on src/main/java/com/walking/intensive/chapter5/task21/Task21.java
> +        Sphere sphere1 = new Sphere(5, 5, 5, 1);
Нейминг лучше без единички

2024-01-08 18:43 UTC, closed without merging