Chapter1 task2
KFalcon2022/intensive-tasks pull request #839
Opened 2023-12-20 17:54 UTC by Egor1808

2023-12-21 06:16 UTC, ekolokolov requested changes
Ойойойойой. Ооооочень сложно. Надо на много проще. 
Циклы тут вообще не нужны. Тем более 3 вложенных друг в друга цикла, да еще и 2 раза.

2024-01-12 18:10 UTC, EvgeneZhurov requested changes

2024-01-12 18:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else{
после return не ставят else

2024-01-12 18:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (x % 10 > 4 && x % 10 < 10 || x % 10 == 0) {
блоки кода лучше отделять пустыми строками.

2024-01-12 18:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (x % 10 == 1) {
код нужно выравнивать: CTRL + ALT + L

2024-01-12 18:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Вам " + age + " лет";
1 pr - 1 задача.

2024-01-12 18:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String n = null;
System.out.println(getFlatLocation(-1,-1,1));
1 кв - 536870912 подъезд, 536870912 этаж, слева от лифта, влево
не проходит валидацию

2024-01-20 07:39 UTC, closed without merging