task 5
KFalcon2022/intensive-tasks pull request #86
Opened 2023-11-20 11:37 UTC by lambo64

2023-11-21 19:45 UTC, EvgeneZhurov requested changes

2023-11-21 19:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        else if (age == 1) return ("Вам " + age + " год");
После return не ставят if. Нужно исправить во всем коде

2023-11-21 19:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        }
} и else на одной строчке.

2023-11-21 19:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        int age =102;
не сделано выравнивание кода, Читайте правила оформления кода перед оправкой: https://github.com/KFalcon2022/intensive-tasks/tree/master#правила-оформления-кода

2023-11-21 19:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            if (lastAgeInt > 1 && lastAgeInt < 5) {
Попробуйте составить условия таким образом, чтобы было ровно 3 return в методе, по 1 на каждое нужное слово: год, лет, года.

2023-11-21 19:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
>          System.out.println(getAgeString(age));
пробел после int

2023-11-22 10:52 UTC, lambo64 commented
я очень извиняюсь, но я 1 ю задачу в 5ю отправила случайно(. 1ю уже исправила в первой, в этой ветке 5я задача, про треугольники...

2023-11-24 13:05 UTC, lambo64 commented
добрый день. я наверное снова что-то напутала и прислала лишнее, а как убрать еще не поняла. Но 5е задание тут тоже есть и оно проходит тесты

2023-11-24 18:59 UTC, EvgeneZhurov requested changes

2023-11-24 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(a + b < c) && !(a + c < b) && !(c + b < a);
!(a + b < c) - перепишите !< это >=

2023-11-24 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double p = (a + b + c) / 2;
давайте именам информативные имена, лучше завести метод, Вы используете полупериметр в качестве метода

2023-11-24 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static boolean testing(double a, double b, double c) {
testing - если метод возвращает boolean,то лучше название начинать со слова is

2023-11-24 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return Math.sqrt(a * b * (a + b + c) * (a + b - c)) / (a + b);
Вы написали метод Герона, пользуйтесь им. Не нужно копировать тело метода.

2023-11-24 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getMedian(double a, double b, double c) {
Не сделано выравнивание кода. Читайте требования к оформлению.

2023-11-25 12:16 UTC, lambo64 commented
все исправила, но не поняла как к биссектрисе прикрутить метод Герона(

2023-11-25 19:32 UTC, EvgeneZhurov commented
принято

2023-11-25 19:32 UTC, closed without merging