Chapter4 task19
KFalcon2022/intensive-tasks pull request #862
Opened 2024-01-11 07:08 UTC by madishkin2

Chapter 4 Task 19

2024-01-11 07:18 UTC, EvgeneZhurov requested changes

2024-01-11 07:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +
много лишних пустых строк

2024-01-11 07:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        for (int i = left; i <= right; i++) {
лучше отделять блоки кода пустыми строками

2024-01-11 07:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        if ((right - left) < 2) {
Условие выхода из рекурсии не совпадает с требованием в условии задачи. Выход из рекурсии: массив длины 2 – если нужно, меняем эти два элемента местами. Если длина входного массива меньше двух, выходим.

2024-01-11 07:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        System.out.println(Arrays.toString(sortByQuicksort(array)));
Результат: [-1, 1, 2, 3, 5, 10, 8]
Ожидалось:  [-1, 1, 2, 3, 5, 8, 10]
Новый год, понимаю :)

2024-01-12 08:44 UTC, madishkin2 commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        System.out.println(Arrays.toString(sortByQuicksort(array)));
теперь сортирует правильно)

2024-01-12 08:45 UTC, madishkin2 commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        if ((right - left) < 2) {
условие выхода поправил

2024-01-12 09:28 UTC, EvgeneZhurov requested changes

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int[] array = {10, 1, -1, 3, 2, 5, 8, -45, 59, -56, 26, 73, 89};
валится на пустом массиве, это единственная причина, почему отправлено на доработку.

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +    public static int partition(int[] array, int from, int to) {
в целом норм, но на самом деле метод должен выполнять 1 поставленную задачу, в данном случае выполняется 2 задачи: возвращает требуемое значение и перекидывает элементы внутри. Пока кода мало, это не критично, но как только его станет много вы не вспомните какой тайный смысл зашит в методе.

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +
пустую строку можно не ставить.

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        return leftIndex;
лучше поставить пустую строку после }

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        return (tmpMax + tmpMin) / 2;
лучше поставить пустую строку.

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +                return;
если убрать 30 строку с return ничего не изменится. :)

2024-01-12 09:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +    public static int partition(int[] array, int from, int to) {
слово partition существительное, обычно методы в java начинаются с глагола, потому что метод отвечает за поведение объекта.

2024-01-12 11:55 UTC, madishkin2 commented on src/main/java/com/walking/intensive/chapter4/task19/Task19.java
> +        int[] array = {10, 1, -1, 3, 2, 5, 8, -45, 59, -56, 26, 73, 89};
Добавил валидацию на массив с нулевой длинной

2024-01-12 12:00 UTC, EvgeneZhurov approved these changes

2024-01-12 12:00 UTC, closed without merging