Chapter5 task21
KFalcon2022/intensive-tasks pull request #867
Opened 2024-01-15 13:53 UTC by madishkin2

2024-01-15 21:23 UTC, EvgeneZhurov requested changes

2024-01-15 21:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Ball.java
> +    public int getxBallCenter() {
идея выдает варнинги. возможно хочет верблюжью нотацию. X - с большой буквы.

2024-01-15 21:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Parallelepiped.java
> +    private final int xPointA;
это не точка, это координата

2024-01-15 21:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Parallelepiped parallelepiped = new Parallelepiped(7,3,2, 12, 7, 5);
перед отправкой всегда делайте выравнивание кода.

2024-01-15 21:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +                & ((Math.min(parallelepiped.getyPointA(), parallelepiped.getyPointB()) <= (ball.getyBallCenter() + ball.getrBall()))
узнайте в чем различие & и &&

2024-01-15 21:23 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Parallelepiped parallelepiped = new Parallelepiped(7,3,2, 12, 7, 5);
Ball ball = new Ball(-1, -1, -1, 1);
        Parallelepiped parallelepiped = new Parallelepiped(0, 0, 0, 10, 10, 10);
результат true
ожидалось false 
без теоремы Пифагора задачу не решить. Советую подумать над случаями, когда шар коснется стороны, вершины и тд.

2024-01-25 15:15 UTC, madishkin2 commented on src/main/java/com/walking/intensive/chapter5/task21/Main.java
> +        Parallelepiped parallelepiped = new Parallelepiped(7,3,2, 12, 7, 5);
сделал поиск ближайшей точки через формулу сферы

2024-01-26 09:15 UTC, EvgeneZhurov commented
засчитано

2024-01-26 09:15 UTC, closed without merging