Feature1 Max Gerasimenko
KFalcon2022/intensive-tasks pull request #876
Opened 2024-02-06 16:02 UTC by Maximilyan91

Добрый день! В данном пулл реквесте решены задачи первого раздела. Тесты пройдены, но в некоторых тестах я имел смелость внести правки, так как эталонное решение было некорректным. Заранее благодарен за уделенное время.

2024-02-06 18:16 UTC, EvgeneZhurov requested changes

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
Лучше не делать 2 пустых строки подряд, здесь такое не ценят:)

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int temp = age;
лучше стараться давать максимально информативные имена

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int temp = age;
блоки кода лучше отделять с обеих сторон пустыми строками, если не стоит в самом начале или самом конце метода.

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return "Вам " + age + " лет";
тут можно пустую строку перед return

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int quantityOfFlatsOnFloor = 4;
лучше стараться избегать предлогов Of и On в названиях переменных, не является ошбкой, но код будет читаться чуть легче: flatsQuantitу....

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        }
System.out.println(getFlatLocation(10, 3, 88));
неверный ответ, такая квартира существует.

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 100 == 0 && year % 400 != 0) {
Здесь не нужен if, вы и так создаете логическое условие, которое ответит на вопрос true или false. Попробуйте соединить это логическое условие со следующим и верните результат из метода.

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant > 0 && a != 0) {
Обращайте внимание на варнинги идеи, она дает дельные советы, а всегда a != 0 :)

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        return null;
кидать из метода null без надобности зачем?

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant < 0) {
выше выполняться все остальные условия, это условие выполнится всегда, если код дойдет до этого if. здесь не нужен if, можно без дополнительных условий делать ретурн.

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double smallerResult;
если переменная объявляется без присвоения значения, это может указывать на ошибку. Чем меньше область видимости переменной, тем лучше. Чем ближе к 1 использованию объявляется переменная, тем лучше. ей место внутри if.

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int quantityOfFlatsOnFloor = 4;
лучше сделать константой, используйте модификатор доступа

2024-02-06 18:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            c = -c;
Лучше это в строке ниже написать поставив знак -

2024-02-07 19:19 UTC, EvgeneZhurov requested changes
нужно переделать

2024-02-07 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        for (int i = 1; i <= entranceAmount; i++) {
далее будет тема: алгоритмическая сложность, которая объяснит что сложность данного алгоритма: O(n^3), а можно реализовать за O(1). Просьба переделать без тройных вложенных циклов, это "плохой" способ решения. Нужно стремиться к нормальной производительности.

2024-02-07 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
обычно переменные заводят в минимальной области видимости, зачем ее делать полем класса? Попахивает джаварашем.

2024-02-10 13:21 UTC, Maximilyan91 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        for (int i = 1; i <= entranceAmount; i++) {
Приветствую Евгений Владимирович! Работаю в графике 2/2 поэтому смог вернуться к решению только сегодня. Алгоритм оптимизировал, работает правильно, справился без гугла, яндекса и иных подсказок =) Благодарю за уделенное время

2024-02-10 13:22 UTC, Maximilyan91 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
Хотел ее сделать константой, а переменные static final нельзя создавать в теле метода

2024-02-10 13:36 UTC, Maximilyan91 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double smallerResult;
Боюсь в таком случае область видимости переменных  smallerResult и biggerResult ограничится скобками внутри if  и опи не будут видны в теле оператора else
![Screenshot_1](https://github.com/KFalcon2022/intensive-tasks/assets/119339813/7830ea1d-d790-409f-a973-c9a3beee5df1)

2024-02-11 07:07 UTC, EvgeneZhurov approved these changes

2024-02-11 07:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>              return "Такой квартиры не существует";
у Вас 2 if подряд возвращают один и тот же результат. Их лучше объединить.

2024-02-11 07:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatsInOneEntrance = maxFlatNumber / entranceAmount;
лучше стараться избегать предлогов в названиях переменных.

2024-02-11 07:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        for (int i = 1; i != flatNumber; i++) {
алгоритмическая сложность O(n), можно погуглить метод, выделения целой части при делении с остатком Math.floor() например. тогда алгоритмическая сложность будет O(1)

2024-02-11 07:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
Вы заводили константу для 4 =FLATS_QUANTITY. Лучше использовать ее.

2024-02-11 07:07 UTC, EvgeneZhurov commented
засчитано.

2024-02-11 07:07 UTC, closed without merging