Task6
KFalcon2022/intensive-tasks pull request #885
Opened 2024-03-03 17:43 UTC by lion2500

2024-03-03 19:32 UTC, EvgeneZhurov requested changes

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return floor;
после return не пишут else

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int ceiling = Math.max(m, n),
не требуется вводить эти 3 переменные можно сразу делать остаток от деления. Искать максимальный и минимальный тоже не требуется.

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            ceiling = remainder;
это лишняя строка, можно в рекурсию вставлять нужное значение без переприсваивания.

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int noc;
почитайте тему области видимости переменных, чем она меньше, тем лучше. Вы используете переменную только внутри цикла, лучше ее там и объявлять. Код не будет работать при этом медленнее и есть памяти не будет больше. Если переменная при создании не присваивает какое либо значение это может указывать на то, что она не нужна здесь.

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i <= ceiling; i++) {
лучше идти по циклу в обратном направлении: от большего (минимального из двух чисел) к 1.

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>          return 0;
этот код не исполнится. Можно было например выйти из цикла брейком (хотя идея тоже может показаться не очень) и вернуть noc.

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        final int a = 42,
модификатор здесь не нужен

2024-03-03 19:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getNodByEuclideanAlgorithm(floor, ceiling); //рекурсия
суть проста, если m%n == 0 выходим, если нет (при этом не требуется else) то в качестве аргументов меняем n и m%n.

2024-03-06 17:07 UTC, lion2500 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>          return 0;
Переделал, пришлось вернуть int noc из цикла, тесты проходят успешно

2024-03-06 17:09 UTC, EvgeneZhurov requested changes
замечания не исправлены

2024-03-06 17:23 UTC, EvgeneZhurov approved these changes
Часть замечаний не исправлена, это не критично, но просьба исправлять или обсуждать все замечания.

2024-03-06 17:23 UTC, closed without merging

2024-03-06 17:32 UTC, lion2500 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i <= ceiling; i++) {
А если так?:)