Chapter 1. Task 4.
KFalcon2022/intensive-tasks pull request #89
Opened 2023-11-20 11:57 UTC by tvadim1

2023-11-21 12:15 UTC, PomidorkaYulia requested changes

2023-11-21 12:15 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if ((b == 0) && (a == 0) && (c != 0)) {
Не поняла это условие? у нас в условии задачи может такое быть, что коэффициенты a и b - нули и при этом коэффициент c - не равен нулю - это означает что у такого уравнения решений нет ( в рамках вещественных чисел)

2023-11-21 12:15 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            solution = "0 = 0";
Здесь тоже не поняла условие - при всех нулевых коэффициентах - бесконечное количество решений.

2023-11-21 12:15 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Выдает неверные решения, например при (0,1,2), при (1,0,-1)
В целом решение достаточно многословное и много ветвления, которого можно избежать.

2023-11-21 13:28 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
при (0, 1, 2) корректно же
![image](https://github.com/KFalcon2022/intensive-tasks/assets/9698419/528c4f5a-0fb0-484d-a413-408098cbc56c)
при (1,0,-1) действительно подправил в соответствующим if, забыл минус

а как можно избежать в конкретном случае, плохо представляю, как иначе описать все простые решения, могли бы передать пример или ссылку на гитхаб с эталонным или близким к нему решением

2023-11-21 13:28 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            solution = "0 = 0";
Исправил текст вывода

2023-11-21 13:28 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +        } else if ((b == 0) && (a == 0) && (c != 0)) {
Нет проблем, решений нет. 

Ого, а вещественных есть?  полином при a=0,b=0 принимает вид C * x^0 = 0, думал даже если вещественное подставить в степени 0 при С будет единица, какая-то логическая ошибка ввода данных от пользователя напрашивается.

и еще, конечно, может если пространство неевклидово :) а какое-то специфически искривленное и в обобщенных координатах, где при C=5 будет замыкаться на ноль, то решение будет(и в действительных, и в вещественных), но тогда его не будет для квадратного в таком виде каким оно представлено в евклидовом. хотя даже тогда скорее существует такое пространство, где конкретное квадратное уравнение будет решаться для конкретного случая как в евклидовом и при этом 5 будет равно 0. могу ошибаться. :)

2023-11-21 16:35 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Да согласна, при (0, 1, 2) корректно, моя ошибка.

2023-11-21 16:49 UTC, PomidorkaYulia requested changes

2023-11-21 16:49 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Чтобы сократить количество строк и используемых переменных можно сделать if-> return на каждое условие. По сути у нас может быть 5 вариантов:
1) все три коэффициента равны нулю - бесконечное множество решений;
2) коэффициенты а и b равны нулю, с не равен нулю ИЛИ дискриминант меньше нуля - решений нет
3) коэффициента а равен нулю - один корень =  -b/c
4) дискриминант равен нулю - один корень
5) дискриминант больше нуля - два корня 
Строго говоря в литературе часто упоминается нелюбовь к множественным ретернам из функций, но на мой взгляд здесь это будет меньшим злом. 
Попробуете переделать?

2023-11-22 10:23 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> -        //        Место для вашего кода
Вкладка была открытой, ждал эти сутки ваш ответ - синюю точку, следя за иконкой жесткого диска в правом верхнем углу, а он автоматически прочитался почему-то в этом ПР и я не заметил. Исрпавил текст кода, и удалил избыточные варианты, которые действительно включены в вариант с вычислением детерминанта. вывод теперь через return
     /*} else if ((b == 0) && (a != 0) && (c < 0)) {
            solutionNumber = 2;
            double x1 = Math.sqrt(-c);
            double x2 = -x1;
            solution = "Корни: " + x1 + ";" + x2;
        } else if ((b == 0) && (a != 0) && (c == 0)) {
            solutionNumber = 1;
            double x = 0;
            solution = "Корень: " + x;*/

2023-11-22 11:18 UTC, PomidorkaYulia commented
Уже посимпатичнее - еще раз попробуйте - если что приходите в личку вместе сделаем.

2023-11-22 11:18 UTC, PomidorkaYulia requested changes

2023-11-22 11:18 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            if (determinant > 0) {
уже более стройно выглядит - но все же, еще раз укажу на то что выше писала - после return  нет смысла в else - можно обойтись без него, то есть в Вашем же коде:
```
if ((a == 0) && (b != 0)) {
            double x = -c / b;
            return solution + "1. Корень: " + x;
        } else 
```- вот этот else избыточен, закончите этот иф и просто с новой строки начните как у вас и написано:
` if ((b == 0) && (a == 0) && (c != 0)) { // ваш дальнейший код
`
и так для каждого Вашего else - они здесь просто не нужны.

2023-11-22 11:18 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                if (x1 > x2) {
Здесь можно использовать тернарный оператор - запись будет короче, и вообще без ифов обойдетесь с одним return

2023-11-22 12:09 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                if (x1 > x2) {
ааа, я всё таки понял :D как приятнее выглядит код с if-return

2023-11-22 21:08 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +            if (determinant > 0) {
исправил:)

2023-11-23 10:05 UTC, PomidorkaYulia approved these changes

2023-11-23 10:07 UTC, PomidorkaYulia commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                if (x1 > x2) {
Мне кажется так стало посимпатичнее) Надеюсь вы тоже прониклись)

2023-11-23 10:07 UTC, closed without merging

2023-11-23 10:41 UTC, tvadim1 commented on src/main/java/com/walking/intensive/chapter1/task4/Main.java
> +                if (x1 > x2) {
благодарю за ревью, я не так понимал, как работает return, оказывается, теперь понял, благодарю и за это 👍