Initial commit
KFalcon2022/intensive-tasks pull request #90
Opened 2023-11-20 12:26 UTC by NightwolfCB

2023-11-20 19:28 UTC, ekolokolov requested changes
Не корректное исполнение на значениях:
111, 112, 113, 114

2023-11-20 19:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        String ageString = "";
Слишком сложно. Можно сделать сильно проще.

2023-11-20 19:28 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if ((age % 10) == 1 & age != 11) {
age % 10 можно вынести в переменную чтобы каждый раз не считать.

2023-11-21 12:06 UTC, ekolokolov approved these changes
Зачтено

2023-11-21 12:07 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if ((decadeRemain == 2 & centuryRemain != 12)
Вот эти проверки можно сделать немного проще (и читаться будет немного проще). Но тоже допустимо (хотя в продакшен такое не пустят)

2023-11-21 12:07 UTC, closed without merging

2023-11-21 15:14 UTC, NightwolfCB commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        } else if ((decadeRemain == 2 & centuryRemain != 12)
@ekolokolov а можно попродробнее, пожалуйста? Я пока еще не силен в синтаксических выкладках Java.