Решение задачи 1
KFalcon2022/intensive-tasks pull request #98
Opened 2023-11-20 15:37 UTC by sofajedi

2023-11-20 18:42 UTC, ekolokolov requested changes
Попробуй объединить некоторые проверки.

2023-11-20 18:42 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return "Вам " + age + " годa";
Английскую `а` в слове `года` надо заменить на русскую.

2023-11-20 18:42 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (lastTwoNumbers > 9 & lastTwoNumbers < 20) {
Если первая проверка `age==0` уже прошла, то условие `lastTwoNumbers > 9 & lastTwoNumbers < 20` уже не надо проверять, так как оно будет false.
По этому для взаимоисключающих проверок надо использовать if else

2023-11-20 19:32 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +        if (lastTwoNumbers > 9 & lastTwoNumbers < 20) {
Убрал проверку `age==0` т.к. избыточна

2023-11-20 19:32 UTC, sofajedi commented on src/main/java/com/walking/intensive/chapter1/task1/Main.java
> +            return "Вам " + age + " годa";
Поправил

2023-11-21 08:43 UTC, ekolokolov approved these changes
Зачтено

2023-11-21 08:43 UTC, closed without merging